program Cobranzas;

{$IFNDEF VER150}
  {$R *.dres}
{$ENDIF}

uses
  OneInstance,
  Forms,
  Controls,
  Windows,
  unCustomDataModule in '..\Comunes\unCustomDataModule.pas' {dmCustomDataModule: TDataModule},
  unDmPrincipal in '..\Comunes\ORACLE\unDmPrincipal.pas' {dmPrincipal: TDataModule},
  unDmFinancials in '..\Comunes\ORACLE\unDmFinancials.pas' {dmFinancials: TDataModule},
  unPrincipal in 'unPrincipal.pas' {frmPrincipal},
  unArtFrame in '..\Comunes\REPOSIT\unArtFrame.pas' {ArtFrame: TFrame},
  unArtDBAwareFrame in '..\Comunes\REPOSIT\unArtDBAwareFrame.pas' {ArtDBAwareFrame: TFrame},
  unArtDbFrame in '..\Comunes\REPOSIT\unArtDbFrame.pas' {ArtDbFrame: TFrame},
  unFraCodigoDescripcion in '..\Comunes\FRAMES\unFraCodigoDescripcion.pas' {fraCodigoDescripcion: TFrame},
  unFraCtbTablas in '..\Comunes\FRAMES\unFraCtbTablas.pas' {fraCtbTablas: TFrame},
  unFraTrabajador in '..\Comunes\FRAMES\NEW\unFraTrabajador.pas' {fraTrabajador: TFrame},
  unFraEmpresa in '..\Comunes\FRAMES\NEW\unFraEmpresa.pas' {fraEmpresa: TFrame},
  unFraEstablecimiento in '..\Comunes\FRAMES\NEW\unFraEstablecimiento.pas' {fraEstablecimiento: TFrame},
  unArtMessages in '..\..\Comunes\unArtMessages.pas',
  unFraStaticCodigoDescripcion in '..\Comunes\FRAMES\unFraStaticCodigoDescripcion.pas' {fraStaticCodigoDescripcion: TFrame},
  unFraStaticCTB_TABLAS in '..\Comunes\FRAMES\unFraStaticCTB_TABLAS.pas' {fraStaticCTB_TABLAS: TFrame},
  unCustomConsulta in '..\Comunes\REPOSIT\unCustomConsulta.pas' {frmCustomConsulta},
  unCustomGridABM in '..\Comunes\REPOSIT\unCustomGridABM.pas' {frmCustomGridABM},
  unCustomPanelABM in '..\Comunes\REPOSIT\unCustomPanelABM.pas' {frmCustomPanelABM},
  unConsultaPlanes in 'unConsultaPlanes.pas' {frmConsultaPlanes},
  unCargaPreAcuerdos in 'unCargaPreAcuerdos.pas' {frmCargaPreAcuerdos},
  unCargaCuotas in 'unCargaCuotas.pas' {frmCargaCuotas},
  unfraContactoEmpresa in '..\Comunes\FRAMES\unfraContactoEmpresa.pas' {fraContactoEmpresa: TFrame},
  unfraContacto in '..\Comunes\FRAMES\unfraContacto.pas' {fraContacto: TFrame},
  unQrEstadoCuentaPlan in 'Reports\unQrEstadoCuentaPlan.pas' {frmQrEstadoCuenta},
  unCargaDepositoManual in 'unCargaDepositoManual.pas' {frmCargaDepositoManual},
  unManCodigoMovimiento in '..\comunes\forms\unManCodigoMovimiento.pas' {frmManCodigoMovimiento},
  unManVencimientoCuota in 'unManVencimientoCuota.pas' {frmManVencimientoCuota},
  unManInteresPorMora in 'unManInteresPorMora.pas' {frmManInteresPorMora},
  unQrPlanFinanciamiento in 'Reports\unQrPlanFinanciamiento.pas' {frmQrPlanFinanciamiento},
  unConsultaEstadoDeCuenta in 'unConsultaEstadoDeCuenta.pas' {frmConsultaEstadoDeCuenta},
  unAdminEstadoDeCuenta in 'unAdminEstadoDeCuenta.pas' {frmAdminEstadoDeCuenta},
  unfraStaticActividad in '..\Comunes\FRAMES\unfraStaticActividad.pas' {fraStaticActividad: TFrame},
  unfraDireccion in '..\Comunes\FRAMES\unfraDireccion.pas' {fraDireccion: TFrame},
  unfraLocalidad in '..\Comunes\FRAMES\unfraLocalidad.pas' {fraLocalidad: TFrame},
  unFraEntidades in '..\Comunes\FRAMES\unFraEntidades.pas' {fraEntidades: TFrame},
  unfraVendedores in '..\Comunes\FRAMES\unfraVendedores.pas' {fraVendedores: TFrame},
  unManCtbTablas in '..\Comunes\Forms\unManCtbTablas.pas' {frmManCtbTablas},
  unManCTB_EVCHE in 'unManCTB_EVCHE.pas' {frmManCTB_EVCHE},
  unSeguimientoDeValores in 'unSeguimientoDeValores.pas' {frmSeguimientoDeValores},
  unfraEmpresaDeudora in '..\Comunes\FRAMES\NEW\unfraEmpresaDeudora.pas' {fraEmpresaDeudora: TFrame},
  unAdminReemplazoValores in 'unAdminReemplazoValores.pas' {frmAdminReemplazoValores},
  unVerReemplazos in 'unVerReemplazos.pas' {frmVerReemplazos},
  unQrEstadoCuentaResumen in 'Reports\unQrEstadoCuentaResumen.pas' {frmEstadoCuentaResumen},
  unImpresionEstadoDeCuenta in 'unImpresionEstadoDeCuenta.pas' {frmImpresionEstadodeCuenta},
  unfraCuentaBancariaRemesa in '..\Comunes\FRAMES\NEW\unfraCuentaBancariaRemesa.pas' {fraCuentaBancariaRemesa: TFrame},
  unQrConvenio in 'Reports\unQrConvenio.pas' {qrConvenio: TQuickRep},
  unFraUsuario in '..\Comunes\FRAMES\NEW\unFraUsuario.pas' {fraUsuarios: TFrame},
  unFraDomicilio in '..\Comunes\FRAMES\NEW\unFraDomicilio.pas' {fraDomicilio: TFrame},
  unBaseGeneracionCartas in '..\Comunes\Forms\unBaseGeneracionCartas.pas' {frmBaseGeneracionCartas},
  unFraToolbarRTF in '..\Comunes\FRAMES\unFraToolbarRTF.pas' {fraToolbarRTF: TFrame},
  unRptCartaDocHeader in '..\Comunes\REPORTS\unRptCartaDocHeader.pas' {rptCartaDocHeader: TQuickRep},
  unRptCartaDocumento in '..\Comunes\REPORTS\unRptCartaDocumento.pas' {rptCartaDocumento: TQuickRep},
  unManCTC_TEXTOCARTA in '..\Comunes\Forms\unManCTC_TEXTOCARTA.pas' {frmManCTC_TEXTOCARTA},
  unManCAT_AREATEXTO in '..\Comunes\Forms\unManCAT_AREATEXTO.pas' {frmManCAT_AREATEXTO},
  unManCTB_CODRE in '..\Comunes\Forms\unManCTB_CODRE.pas' {frmManCTB_CODRE},
  unManCFI_FIRMA in '..\Comunes\Forms\unManCFI_FIRMA.pas' {frmManCFI_FIRMA},
  unReclamoAFIP in 'unReclamoAFIP.pas' {frmReclamoAFIP},
  ArtMail in '..\..\Comunes\ArtMail.pas',
  unQrEstadoCuentaDetalle in 'Reports\unQrEstadoCuentaDetalle.pas' {frmEstadoCuentaDetalle},
  unGeneracionCartasEventos in 'unGeneracionCartasEventos.pas' {frmGeneracionCartasEventos},
  unGeneracionCartasAdmin in 'unGeneracionCartasAdmin.pas' {frmGeneracionCartasAdmin},
  unCobranzas in '..\..\Comunes\unCobranzas.pas',
  unIngresoValores in 'unIngresoValores.pas' {frmIngresoValores},
  unfraAGC_GESTORCUENTA in '..\Comunes\FRAMES\unfraAGC_GESTORCUENTA.pas' {fraAGC_GESTORCUENTA: TFrame},
  unfraCuentaBancaria in '..\Comunes\FRAMES\NEW\unfraCuentaBancaria.pas' {fraCuentaBancaria: TFrame},
  unBusquedaDomicilio in '..\Comunes\Forms\unBusquedaDomicilio.pas' {frmBusquedaDomicilio},
  uncomunes in '..\..\COMUNES\uncomunes.pas',
  unCompSelecionAprobacion in 'Compensacion\unCompSelecionAprobacion.pas' {frmCompSelecionAprobacion},
  unCompReimpresionCartas in 'Compensacion\unCompReimpresionCartas.pas' {frmCompReimpresionCartas},
  unRptCartaDocCompensacion in 'Compensacion\REPORTS\unRptCartaDocCompensacion.pas' {rptCartaDocCompensacion: TQuickRep},
  unGestionArmarSelEmpresas in 'unGestionArmarSelEmpresas.pas' {frmGestionArmarSelEmpresas},
  unFraDomicilioTrab in '..\Comunes\FRAMES\NEW\unFraDomicilioTrab.pas' {fraDomicilioTrab: TFrame},
  unEjecutivoCuenta in '..\Comunes\Forms\unEjecutivoCuenta.pas' {frmEjecutivoCuenta},
  unGestorCuenta in '..\Comunes\Forms\unGestorCuenta.pas' {frmGestorCuenta},
  unGestionArrancarAccion in 'unGestionArrancarAccion.pas' {frmGestionArrancarAccion},
  unSeleccionarEmpresasAccion in 'unSeleccionarEmpresasAccion.pas' {frmSeleccionarEmpresasAccion},
  unQRF817 in 'Reports\unQRF817.pas' {QRF817: TQuickRep},
  unQRCartaDocIntimacion in 'Reports\unQRCartaDocIntimacion.pas' {QRCartaDocIntimacion: TQuickRep},
  unBaseAdministracionCartas in '..\Comunes\Forms\unBaseAdministracionCartas.pas' {frmBaseAdministracionCartas},
  unCobAdministracionCartas in 'unCobAdministracionCartas.pas' {frmCobAdministracionCartas},
  unConvertirEnConvenio in 'unConvertirEnConvenio.pas' {frmConvertirEnConvenio},
  unfraInfoEmpresa in '..\Comunes\FRAMES\NEW\unfraInfoEmpresa.pas' {fraInfoEmpresa: TFrame},
  unConsultasAdicionales in '..\Comunes\Forms\unConsultasAdicionales.pas' {frmConsultasAdicionales},
  unImpoExpoWizard in '..\ImpoExpo\unImpoExpoWizard.pas' {frmImpoExpoWizard},
  unCargaManualMovimientos in 'Emision\unCargaManualMovimientos.pas' {frmCargaManualMovimientos},
  unNominaPeriodos in '..\Comunes\Forms\unNominaPeriodos.pas' {frmNominaPeriodos},
  unQRCartaAFIP in 'Reports\unQRCartaAFIP.pas' {rptCartaAFIP: TQuickRep},
  unMovimientosVistaPrevia in 'unMovimientosVistaPrevia.pas' {frmMovimientosVistaPrevia},
  unVisualizador in '..\Comunes\unVisualizador.pas' {frmVisualizador},
  unSesion in '..\..\Comunes\unSesion.pas',
  unMoldeEnvioMail in '..\Comunes\Envio de Mails\unMoldeEnvioMail.pas',
  unCustomForm in '..\Comunes\unCustomForm.pas' {frmCustomForm},
  unEnvioMail in '..\..\Comunes\unEnvioMail.pas',
  unqrImpresionRecibo in '..\Afiliaciones\TESORERIA\unqrImpresionRecibo.pas' {frmValImpresionRecibo},
  unLibretaDeDirecciones in '..\Comunes\Forms\unLibretaDeDirecciones.pas' {frmLibretaDeDirecciones},
  unContratoContacto in '..\comunes\forms\unContratoContacto.pas' {frmContratoContacto},
  unEstadoCuenta in 'unEstadoCuenta.pas',
  unRecaudacionAnalisis in 'unRecaudacionAnalisis.pas' {frmRecaudacionAnalisis},
  unEspera in '..\Comunes\Forms\unEspera.pas' {frmEspera},
  unCITRIX in '..\..\Comunes\unCITRIX.pas',
  unCompLstSiniestrosLiberar in 'Compensacion\unCompLstSiniestrosLiberar.pas' {QRlibera},
  CustomDlgs in '..\..\Comunes\CustomDlgs.pas',
  unFraCodDesc in '..\Comunes\FRAMES\NUEVOS\unFraCodDesc.pas' {fraCodDesc: TFrame},
  unfraEntidadCUIT in '..\Comunes\FRAMES\NEW\unfraEntidadCUIT.pas' {fraEntidadCUIT: TFrame},
  unfraVendedoresCUIT in '..\Comunes\FRAMES\NEW\unfraVendedoresCUIT.pas' {fraVendedoresCUIT: TFrame},
  unElementosEnviados in '..\Comunes\Forms\unElementosEnviados.pas' {frmElementosEnviados},
  unfraUsuarios in '..\Comunes\FRAMES\unfraUsuarios.pas' {fraUsuario: TFrame},
  unTesoreria in '..\Afiliaciones\TESORERIA\unTesoreria.pas',
  unOpcionesDeImpresion in 'unOpcionesDeImpresion.pas' {frmOpcionesDeImpresion},
  unCustomGridABMDetalle in '..\Comunes\REPOSIT\unCustomGridABMDetalle.pas' {frmCustomGridABMDetalle},
  unFraTelefono in '..\Comunes\FRAMES\NEW\unFraTelefono.pas' {fraTelefono: TFrame},
  unABMTelefonos in '..\Comunes\Forms\unABMTelefonos.pas' {frmTelefonos},
  unAlarmas in '..\..\Comunes\unAlarmas.pas',
  unDebug in '..\Comunes\unDebug.pas' {frmDebug},
  unManCRR_RESPUESTA in '..\Comunes\Forms\unManCRR_RESPUESTA.pas' {frmManCRR_RESPUESTA},
  unTelefonosCargaRapida in '..\Comunes\Forms\unTelefonosCargaRapida.pas' {frmTelefonosCargaRapida},
  unControlImputacion in 'unControlImputacion.pas' {frmControlImputacion},
  UnRptMoldeCarta in '..\Comunes\REPORTS\UnRptMoldeCarta.pas' {qrMoldeCarta: TQuickRep},
  unQrChequesReemplazados in 'Reports\unQrChequesReemplazados.pas' {qrChequesReemplazados: TQuickRep},
  unControlImputacionAFIP in 'unControlImputacionAFIP.pas' {frmControlImputacionAFIP},
  unManExclusionContratos in 'unManExclusionContratos.pas' {frmManExclusionContratos},
  unEmpresasEstado9 in 'unEmpresasEstado9.pas' {frmEmpresasEstado9},
  unEmpresasRescindidas in 'unEmpresasRescindidas.pas' {frmEmpresasBajaTraspaso},
  unExportaciones in 'unExportaciones.pas' {frmExportaciones},
  unQRF801C in 'reports\unQRF801C.pas' {QRF801C: TQuickRep},
  unRecibosValorPlanPago in '..\afiliaciones\tesoreria\unRecibosValorPlanPago.pas' {frmRecibosValorPlanPago},
  Strfuncs in '..\..\comunes\Strfuncs.pas',
  numeros in '..\..\comunes\numeros.pas',
  unExportPDF in '..\..\comunes\unExportPDF.pas',
  unManCTBRespReclAFIP in 'unManCTBRespReclAFIP.pas' {frmManCtbRespReclAFIP},
  General in '..\..\comunes\General.pas',
  ArchFuncs in '..\..\comunes\ArchFuncs.pas',
  unRemesasAFIP in 'unRemesasAFIP.pas' {frmRemesasAFIP},
  unImpoExpo in '..\..\comunes\unImpoExpo.pas',
  unManZRP_REDONDEOPLAN in 'unManZRP_REDONDEOPLAN.pas' {frmManZRP_REDONDEOPLAN},
  unCargaCertificadoRetencion in 'unCargaCertificadoRetencion.pas' {frmCargaCertificadoRetencion},
  unReversionMovimientos in 'unReversionMovimientos.pas' {frmReversionMovimientos},
  SpoolFuncs in '..\..\Comunes\SpoolFuncs.pas',
  unFraDigitalizacion in '..\comunes\frames\new\unFraDigitalizacion.pas' {fraDigitalizacion: TFrame},
  unFraRTD_TIPODOCUMENTO in '..\comunes\frames\new\unFraRTD_TIPODOCUMENTO.pas' {fraRTD_TIPODOCUMENTO: TFrame},
  libgfl in '..\..\Comunes\libgfl.pas',
  unFraVistaTIFF in '..\comunes\frames\new\unFraVistaTIFF.pas' {fraVistaTIFF: TFrame},
  ungrids in '..\..\Comunes\ungrids.pas',
  VCLExtra in '..\..\Comunes\VCLExtra.pas',
  unSeleccionDestinatarios in '..\comunes\unSeleccionDestinatarios.pas' {frmSeleccionDestinatarios},
  unValoresConciliados in 'unValoresConciliados.pas' {frmValoresConciliados},
  unConsultaCancelaciones in 'unConsultaCancelaciones.pas' {frmConsultaCancelaciones},
  unFaxEnviados in '..\comunes\forms\unFaxEnviados.pas' {frmFaxEnviados},
  unConsFax in '..\comunes\forms\unConsFax.pas' {frmConsFax},
  unfraFFO_FAXFORMULARIO in '..\comunes\frames\unfraFFO_FAXFORMULARIO.pas' {fraFFO_FAXFORMULARIO: TFrame},
  unEstrategiaTIFF in '..\fax\faxclient_new\unEstrategiaTIFF.pas',
  unCustomPrincipal in '..\comunes\reposit\unCustomPrincipal.pas' {frmCustomPrincipal},
  unManRDO_DOCUMENTO in '..\archivo_new\abm\unManRDO_DOCUMENTO.pas' {frmManRDO_DOCUMENTO: TFSForm},
  unfraCPR_PRESTADOR in '..\comunes\frames\new\unfraCPR_PRESTADOR.pas' {fraCPR_PRESTADOR: TFrame},
  unSiniestros in '..\siniestros\unSiniestros.pas',
  unNovedades in '..\..\comunes\unNovedades.pas',
  unQRCartaDocIntimacionNuevaGrilla in 'reports\unQRCartaDocIntimacionNuevaGrilla.pas' {QRCartaDocIntimacionNuevaGrilla: TQuickRep},
  unManRedondeosEmision in 'unManRedondeosEmision.pas' {frmManRedondeosEmision: TFSForm},
  unFormularioValidacionYRectificacionDatosEstablecimientos in '..\comunes\forms\unFormularioValidacionYRectificacionDatosEstablecimientos.pas' {frmFormularioValidacionYRectificacionDatosEstablecimientos},
  unRptFormularioValidacionYRectificacionDatosEstablecimientos in '..\comunes\reports\unRptFormularioValidacionYRectificacionDatosEstablecimientos.pas' {qrFormularioValidacionYRectificacionDatosEstablecimientos: TQuickRep},
  unFrmEmpresasABonificar in '..\emision\cliente\unFrmEmpresasABonificar.pas' {frmEmpresasABonificar: TFSForm},
  unEmpresasBajaTraspaso in 'unEmpresasBajaTraspaso.pas' {frmEmpresasBajaTraspaso},
  unDmEmision in '..\emision\comunes\unDmEmision.pas' {DmEmision: TDataModule},
  unLibreDeuda in 'unLibreDeuda.pas' {frmLibreDeuda: TFSForm},
  unQrLibreDeuda in 'reports\unQrLibreDeuda.pas' {qrLibreDeuda: TQuickRep},
  unRptGestionDeReclamos in '..\comunes\reports\unRptGestionDeReclamos.pas' {frmRptGestionDeReclamos},
  unFraTrabajadorSiniestro in '..\comunes\frames\new\unFraTrabajadorSiniestro.pas' {fraTrabajadorSiniestro: TFrame},
  unVentanillaElectronica in '..\comunes\forms\unVentanillaElectronica.pas' {frmVentanillaElectronica: TFSForm},
  unBajaOficioSRTPagos in 'unBajaOficioSRTPagos.pas' {frmBajaOficioSRTPagos},
  unAgendaTelefonica in '..\comunes\forms\unAgendaTelefonica.pas' {frmAgendaTelefonica: TFSForm},
  unFraNavegadorWEB in '..\comunes\frames\new\unFraNavegadorWEB.pas' {fraNavegadorWEB: TFrame},
  unGoogleMaps in '..\comunes\forms\unGoogleMaps.pas' {frmGoogleMaps},
  unFraDomicilioGIS in '..\comunes\frames\new\unFraDomicilioGIS.pas' {fraDomicilioGIS: TFrame},
  unExcel in '..\..\comunes\unExcel.pas',
  unManCGI_GIS in '..\comunes\forms\unManCGI_GIS.pas' {frmManCGI_GIS: TFSForm},
  unAnexoRes365 in '..\comunes\forms\unAnexoRes365.pas' {frmAnexoRes365},
  OneSession in '..\..\comunes\OneSession.pas',
  unRptAnexoRes365 in '..\comunes\reports\unRptAnexoRes365.pas' {qrAnexoRes365: TQuickRep},
  unCompensarDeuda in 'unCompensarDeuda.pas' {frmCompensarDeuda: TFSForm},
  unNivelAutorizacion in 'unNivelAutorizacion.pas' {frmNivelAutorizacion: TFSForm},
  unRptEstadisticasRGRL in '..\comunes\reports\unRptEstadisticasRGRL.pas' {qrEstadisticasRGRL: TQuickRep},
  unRptRGRL in '..\comunes\reports\unRptRGRL.pas' {qrRGRL: TQuickRep},
  unRGRL in '..\comunes\forms\unRGRL.pas' {frmRGRL},
  unFraEmpresaAfi in '..\comunes\frames\new\unFraEmpresaAfi.pas' {fraEmpresaAfi: TFrame},
  unManCPG_PLAZOGUARDA in '..\comunes\forms\unManCPG_PLAZOGUARDA.pas' {frmManCPG_PLAZOGUARDA: TFSForm},
  unManCTA_TIPOACTIVOS in '..\comunes\forms\unManCTA_TIPOACTIVOS.pas' {frmManCTA_TIPOACTIVOS: TFSForm},
  unClasificacionActivos in '..\comunes\forms\unClasificacionActivos.pas' {frmClasificacionActivos: TFSForm},
  unConsultaAutorizaciones in 'unConsultaAutorizaciones.pas' {frmConsultaAutorizaciones: TFSForm},
  unfraCodigoDescripcionExt in '..\comunes\frames\unfraCodigoDescripcionExt.pas' {fraCodigoDescripcionExt: TFrame},
  unSeleccionMultiple in '..\comunes\forms\unSeleccionMultiple.pas' {frmSeleccionUsuarios: TFrame},
  unConstEmision in '..\emision\comunes\unConstEmision.pas',
  unfraDelegacion in '..\comunes\frames\unfraDelegacion.pas' {fraDelegacion: TFrame},
  unCompensarIntereses in 'unCompensarIntereses.pas' {frmCompensarIntereses: TFSForm},
  unIndicadoresGestionTel in 'unIndicadoresGestionTel.pas' {frmIndicadoresGestionTel: TFSForm},
  unFondoGarantia in 'unFondoGarantia.pas' {frmFondoGarantia: TFSForm},
  unPagosFondoGarantia in 'unPagosFondoGarantia.pas' {frmPagosFondoGarantia: TFSForm},
  unDetallePagosFondoGarantia in 'unDetallePagosFondoGarantia.pas' {frmDetallePagosFondoGarantia: TFSForm},
  unRptDetallePagosFondoGarantia in 'reports\unRptDetallePagosFondoGarantia.pas' {qrDetallePagosFondoGarantia: TQuickRep},
  unManCCP_CUENTAPAGO in '..\Comunes\Forms\unManCCP_CUENTAPAGO.pas' {frmManCCP_CUENTAPAGO},
  unAltaModifCCP_CUENTAPAGO in '..\Comunes\Forms\unAltaModifCCP_CUENTAPAGO.pas' {frmAltaModifCCP_CUENTAPAGO},
  unAfiliaciones in '..\afiliaciones\unAfiliaciones.pas',
  unDevolPagoExcesoCons in 'unDevolPagoExcesoCons.pas' {frmDevolPagoExcesoCons: TFSForm},
  unDevolPagoExcesoPagos in 'unDevolPagoExcesoPagos.pas' {frmDevolPagoExcesoPagos: TFSForm},
  unDetallePagosExcesoPagos in 'unDetallePagosExcesoPagos.pas' {frmDetallePagosExcesoPagos: TFSForm},
  unRptDetallePagosExcesoPagos in 'reports\unRptDetallePagosExcesoPagos.pas' {qrDetallePagosExcesoPagos: TQuickRep},
  unVisor in '..\comunes\forms\unVisor.pas' {frmVisor},
  unArchivoVisor in '..\comunes\unArchivoVisor.pas',
  unVisorPDF in '..\comunes\forms\unVisorPDF.pas' {frmVisorPDF},
  unVisorExcel in '..\comunes\forms\unVisorExcel.pas' {frmVisorExcel},
  unAyuda in '..\comunes\unAyuda.pas' {frmAyuda},
  unQrEtiquetasDocCarpetas in '..\archivo_new\unQrEtiquetasDocCarpetas.pas' {qrEtiquetasDocCarpetas: TQuickRep},
  unRptPlantillaRGRL in '..\comunes\reports\unRptPlantillaRGRL.pas' {qrPlantillaRGRL: TQuickRep},
  unfraVistaEventos in '..\comunes\frames\modulosAgenda\unfraVistaEventos.pas' {fraVistaEventos: TFrame},
  unABMAgendaBase in '..\comunes\forms\unABMAgendaBase.pas' {frmABMAgendaBase},
  unfraContactoAGENDA in '..\comunes\frames\modulosAgenda\unfraContactoAGENDA.pas' {fraContactoAGENDA: TFrame},
  unfraContactoLibreAGENDA in '..\comunes\frames\modulosAgenda\unfraContactoLibreAGENDA.pas' {fraContactoLibreAGENDA: TFrame},
  unfraDomicilioAGENDA in '..\comunes\frames\modulosAgenda\unfraDomicilioAGENDA.pas' {fraDomicilioGISAGENDA: TFrame},
  unfraDomicilioEmpresaAGENDA in '..\comunes\frames\modulosAgenda\unfraDomicilioEmpresaAGENDA.pas' {fraDomicilioEmpresaAGENDA: TFrame},
  unfraDomicilioEstablecimientoAGENDA in '..\comunes\frames\modulosAgenda\unfraDomicilioEstablecimientoAGENDA.pas' {fraDomicilioEstablecimientoAGENDA: TFrame},
  unfraEmpresaAGENDA in '..\comunes\frames\modulosAgenda\unfraEmpresaAGENDA.pas' {fraEmpresaAGENDA: TFrame},
  unfraEntidadAGENDA in '..\comunes\frames\modulosAgenda\unfraEntidadAGENDA.pas' {fraEntidadAGENDA: TFrame},
  unfraEntidadVendedorAGENDA in '..\comunes\frames\modulosAgenda\unfraEntidadVendedorAGENDA.pas' {fraEntidadVendedorAGENDA: TFrame},
  unfraEstablecimientoAGENDA in '..\comunes\frames\modulosAgenda\unfraEstablecimientoAGENDA.pas' {fraEstablecimientoAGENDA: TFrame},
  unfraNumAutoAGENDA in '..\comunes\frames\modulosAgenda\unfraNumAutoAGENDA.pas' {fraNumAutoAGENDA: TFrame},
  unfraPrestadorAGENDA in '..\comunes\frames\modulosAgenda\unfraPrestadorAGENDA.pas' {fraPrestadorAGENDA: TFrame},
  unfraProspectosAGENDA in '..\comunes\frames\modulosAgenda\unfraProspectosAGENDA.pas' {fraProspectosAGENDA: TFrame},
  unfraTrabajadorAGENDA in '..\comunes\frames\modulosAgenda\unfraTrabajadorAGENDA.pas' {fraTrabajadorAGENDA: TFrame},
  unfraTrabajadorSiniestroAGENDA in '..\comunes\frames\modulosAgenda\unfraTrabajadorSiniestroAGENDA.pas' {fraTrabajadorSiniestroAGENDA: TFrame},
  unfraVendedorAGENDA in '..\comunes\frames\modulosAgenda\unfraVendedorAGENDA.pas' {fraVendedorAGENDA: TFrame},
  unABMAgendaBaseTarea in '..\comunes\forms\unABMAgendaBaseTarea.pas' {frmABMAgendaBaseTarea},
  unABMAgendaBaseEvento in '..\comunes\forms\unABMAgendaBaseEvento.pas' {frmABMAgendaBaseEvento},
  unContratoTrabajador in '..\afiliaciones\unContratoTrabajador.pas' {frmContratoTrabajador},
  unFraActividad in '..\comunes\frames\unFraActividad.pas' {fraActividad: TFrame},
  unfraInfoEmpresaExt in '..\comunes\frames\new\unfraInfoEmpresaExt.pas' {fraInfoEmpresaExt: TFrame},
  unFraDomicilioEmpresa in '..\comunes\frames\new\unFraDomicilioEmpresa.pas' {fraDomicilioEmpresa: TFrame},
  unFraValidacionDatosEmpresa in '..\comunes\frames\new\unFraValidacionDatosEmpresa.pas' {fraValidacionDatosEmpresa: TFrame},
  unFraTitulo in '..\comunes\frames\nuevos\unFraTitulo.pas' {fraTitulo: TFrame},
  unFraUsuarioConJerarquias in '..\comunes\frames\new\unFraUsuarioConJerarquias.pas' {fraUsuarioConJerarquias: TFrame},
  unFraUsuarioConSectorIntranet in '..\comunes\frames\new\unFraUsuarioConSectorIntranet.pas' {fraUsuarioConSectorIntranet: TFrame},
  unArbolSectores in '..\usuarios\unArbolSectores.pas' {frmArbolSectores},
  unEstablecimientosTrabajador in '..\afiliaciones\unEstablecimientosTrabajador.pas' {frmEstablecimientosTrabajador},
  unDlgBusSiniestro in '..\siniestros\unDlgBusSiniestro.pas' {frmDlgBusSiniestro: TFSForm},
  unAgendaVistaEmpresa in '..\comunes\forms\unAgendaVistaEmpresa.pas' {frmAgendaVistaEmpresa},
  unAgendaCargaConsulta in '..\comunes\forms\unAgendaCargaConsulta.pas' {frmAgendaCargaConsulta},
  unFiltros in '..\..\comunes\unFiltros.pas',
  unArt in '..\..\comunes\unArt.pas',
  DateTimeFuncs in '..\..\comunes\DateTimeFuncs.pas',
  unFraCanal in '..\comunes\frames\new\unFraCanal.pas' {fraCanal: TFrame},
  unfraSectores in '..\comunes\frames\unfraSectores.pas' {fraSectores: TFrame},
  unInterfaces in '..\..\comunes\interfaces\unInterfaces.pas',
  unAgenda in '..\..\comunes\interfaces\unAgenda.pas',
  unSIC in '..\..\comunes\unSIC.pas',
  unSeleccionTareas in '..\comunes\forms\unSeleccionTareas.pas' {frmSeleccionTareas},
  unDatosSiniestro in '..\comunes\forms\unDatosSiniestro.pas' {frmDatosSiniestro},
  unSeleccionResponsableHYS in '..\hys\unSeleccionResponsableHYS.pas' {frmSeleccionResponsableHYS: TFSForm},
  unArchivo in '..\archivo_new\unArchivo.pas',
  unConstantArchivo in '..\archivo_new\unConstantArchivo.pas',
  unNivelAutorizacionBonif in 'unNivelAutorizacionBonif.pas' {frmNivelAutorizacionBonif: TFSForm},
  unFrmConsultaCarpetas in '..\archivo_new\unFrmConsultaCarpetas.pas' {FrmConsultaCarpetas: TFSForm},
  unFrmSolicitudCarpeta in '..\archivo_new\unFrmSolicitudCarpeta.pas' {FrmSolicitudCarpeta: TFSForm},
  unQrEtiquetasCarpetas in '..\archivo_new\unQrEtiquetasCarpetas.pas' {qrEtiquetasCarpetas: TQuickRep},
  unFraDetalleArchivo in '..\archivo_new\frames\unFraDetalleArchivo.pas' {fraDetalleArchivo: TFrame},
  unFrmDetalleArchivo in '..\archivo_new\unFrmDetalleArchivo.pas' {FrmDetalleArchivo},
  unMovimientoCarpetas in '..\archivo_new\unMovimientoCarpetas.pas' {frmMovimientoCarpetas},
  unFrmCargaDocumentacion in '..\archivo_new\unFrmCargaDocumentacion.pas' {frmCargaDocumentacion},
  unQrDetalleLoteEstudio in '..\archivo_new\unQrDetalleLoteEstudio.pas' {QrDetalleLoteEstudio},
  unReemplazoCarpetas in '..\archivo_new\unReemplazoCarpetas.pas' {frmReemplazoCarpetas},
  unfrmUbicacionActual in '..\archivo_new\unfrmUbicacionActual.pas' {FrmUbicacionActual},
  unFraFiltroArchivo in '..\archivo_new\frames\unFraFiltroArchivo.pas' {fraFiltroArchivo: TFrame},
  unfraArchJuicio in '..\archivo_new\frames\unfraArchJuicio.pas' {fraArchJuicio: TFrame},
  unfraProveedor in '..\comunes\frames\new\unfraProveedor.pas' {fraProveedor: TFrame},
  unCapturarCodigoBarras in '..\comunes\unCapturarCodigoBarras.pas' {frmCapturarCodigoBarras},
  unImportFromSRTReclamos in '..\comunes\unImportFromSRTReclamos.pas' {frmImportFromSRTReclamos},
  unfraPrestador in '..\comunes\frames\unfraPrestador.pas' {fraPrestador: TFrame},
  unCustomSplash in '..\comunes\reposit\unCustomSplash.pas' {frmCustomSplash},
  unWelcomeSplash in '..\comunes\forms\unWelcomeSplash.pas' {frmWelcomeSplash},
  unAnularcionRemesas in 'unAnularcionRemesas.pas' {frmAnularcionRemesas: TFSForm},
  unDetalleRemesa in 'unDetalleRemesa.pas' {frmDetalleRemesa: TFSForm},
  ExportDialog in '..\..\paquetes\ExportDialog.pas',
  unCargaDocumentosDigitaliz in '..\comunes\forms\unCargaDocumentosDigitaliz.pas' {frmCargaDocumentosDigitaliz},
  unFraEmpresaSolicitud in '..\comunes\frames\new\unFraEmpresaSolicitud.pas' {fraEmpresaSolicitud: TFrame},
  unfraEmpresaSolicitudAGENDA in '..\comunes\frames\modulosagenda\unfraEmpresaSolicitudAGENDA.pas' {fraEmpresaSolicitudAGENDA: TFrame},
  unQrDetalleRemitoDevolucion in '..\archivo_new\unQrDetalleRemitoDevolucion.pas' {QrDetalleRemitoDevolucion},
  unfraFirmante in '..\comunes\frames\unfraFirmante.pas' {fraFirmante: TFrame},
  unManCVS_VENTANILLA_SUBTEMAS in '..\comunes\forms\unManCVS_VENTANILLA_SUBTEMAS.pas' {frmManCVS_VENTANILLA_SUBTEMAS: TFSForm},
  unfraDatoFechaAGENDA in '..\comunes\frames\modulosagenda\unfraDatoFechaAGENDA.pas' {fraDatoFecha: TFrame},
  unHistoricoPlanesPago in 'unHistoricoPlanesPago.pas' {frmHistoricoPlanesPago: TFSForm},
  unSeguimientoProcesos in 'unSeguimientoProcesos.pas' {frmSeguimientoProcesos: TFSForm},
  unConsultaBonificaciones in 'unConsultaBonificaciones.pas' {frmConsultaBonificaciones: TFSForm},
  unRptBonificacionesCuota in 'reports\unRptBonificacionesCuota.pas' {qrBonificacionesCuota: TQuickRep},
  unRptPlanesPago in 'reports\unRptPlanesPago.pas' {qrPlanesPago: TQuickRep},
  unFrmArmadoLote in '..\archivo_new\unFrmArmadoLote.pas' {FrmArmadoLote: TFSForm},
  unQrDetalleLote in '..\archivo_new\unQrDetalleLote.pas' {QrDetalleLote},
  unRptResumenLotes in '..\archivo_new\unRptResumenLotes.pas' {qrResumenLotes: TQuickRep},
  unVerImagenes in '..\archivo_new\unVerImagenes.pas' {frmVerImagenes},
  unComisiones in '..\afiliaciones\comisiones\unComisiones.pas',
  unMensajeAlertaAGA in '..\archivo_new\unMensajeAlertaAGA.pas',
  unFraSDA_DETALLEARCHIVO in '..\Comunes\FRAMES\unFraSDA_DETALLEARCHIVO.pas' {fraSDA_DETALLEARCHIVO: TFrame},
  unMensajeAlerta in '..\..\comunes\unMensajeAlerta.pas',
  unUtilsArchivo in '..\archivo_new\unUtilsArchivo.pas',
  unComunesArchivo in '..\archivo_new\unComunesArchivo.pas',
  unFraGIS_APIv3 in '..\comunes\frames\new\unFraGIS_APIv3.pas' {fraGIS_APIv3: TFrame},
  unGIS in '..\..\comunes\unGIS.pas',
  unFraWebBrowser in '..\comunes\frames\new\unFraWebBrowser.pas' {fraWebBrowser: TFrame},
  unEsperaSimple in '..\comunes\forms\unEsperaSimple.pas' {frmEsperaSimple},
  unfraFirmantes in '..\comunes\frames\new\unfraFirmantes.pas' {fraFirmantes: TFrame},
  UnFirmantes in '..\redpres\UnFirmantes.pas' {frmFirmantes},
  unImportCryptoSrt in '..\..\comunes\unImportCryptoSrt.pas',
  unSeleccionarCarpetaSRT in '..\afiliaciones\unSeleccionarCarpetaSRT.pas' {frmSeleccionarCarpetaSRT},
  unEnvioSMS in '..\comunes\forms\unEnvioSMS.pas' {frmEnvioSMS},
  unSMS in '..\..\comunes\unSMS.pas',
  IArtMail in '..\comunes\IArtMail.pas',
  unRptRemitoCartas in '..\redpres\reports\unRptRemitoCartas.pas' {qrRemitoCartas: TQuickRep},
  unFrmEmpresasRegla in '..\emision\cliente\unFrmEmpresasRegla.pas',
  unFraTipoRegimen in '..\comunes\frames\new\unFraTipoRegimen.pas' {fraTipoRegimen: TFrame},
  unMovimientosCUILAFIP in 'unMovimientosCUILAFIP.pas' {frmMovimientosCUILAFIP: TFSForm},
  unFuncionesEmision in '..\emision\comunes\unFuncionesEmision.pas',
  unManParametros in 'unManParametros.pas' {frmManParametros: TFSForm},
  unRptCompensacionesDepositar in 'reports\unRptCompensacionesDepositar.pas' {RptCompensacionesDepositar},
  unManAGC_GESTORCUENTA in '..\afiliaciones\abm\unManAGC_GESTORCUENTA.pas' {frmManAGC_GESTORCUENTA: TFSForm},
  unComisionGestor in '..\afiliaciones\unComisionGestor.pas' {frmComisionGestor},
  unDocumentacion in '..\comunes\forms\unDocumentacion.pas' {frmDocumentacion: TFSForm},
  unRemitoDocumentacion in '..\comunes\forms\unRemitoDocumentacion.pas' {frmRemitoDocumentacion},
  unHistoricoDocumentacion in '..\comunes\forms\unHistoricoDocumentacion.pas' {frmHistoricoDocumentacion: TFSForm},
  unLstRemitosnoRecepcionados in '..\comunes\reports\unLstRemitosnoRecepcionados.pas' {frmLstRemitosnoRecepcionados},
  unChat in '..\comunes\unChat.pas' {frmChat},
  unEnviosVentanillaElectronica in '..\comunes\forms\unEnviosVentanillaElectronica.pas' {frmEnviosVentanillaElectronica: TFSForm};

{$R *.RES}

begin
  OnlyOneInstance;
  Application.Initialize;
  Application.Title := 'Cobranzas';

  with TfrmWelcomeSplash.Create(Application) do
  try
    ShowOnTop;
    Application.CreateForm(TdmPrincipal, dmPrincipal);
  if dmPrincipal.sdbPrincipal.Connected then
      Application.CreateForm(TfrmPrincipal, frmPrincipal);

    OnlyOneSession;
  finally
    Free;
  end;

  MostrarNovedades;
  Application.Run;
end.
