program admgralarchivo;

{$R *.dres}

uses
  OneInstance,
  Forms,
  Controls,
  Windows,
  unDmPrincipal in '..\Comunes\ORACLE\unDmPrincipal.pas' {dmPrincipal: TDataModule},
  unPrincipal in 'unPrincipal.pas' {frmPrincipal},
  unArtFrame in '..\Comunes\REPOSIT\unArtFrame.pas' {ArtFrame: TFrame},
  unArtDBAwareFrame in '..\Comunes\REPOSIT\unArtDBAwareFrame.pas' {ArtDBAwareFrame: TFrame},
  unArtDbFrame in '..\Comunes\REPOSIT\unArtDbFrame.pas' {ArtDbFrame: TFrame},
  unFraCodigoDescripcion in '..\Comunes\FRAMES\unFraCodigoDescripcion.pas' {fraCodigoDescripcion: TFrame},
  unFraStaticCodigoDescripcion in '..\Comunes\FRAMES\unFraStaticCodigoDescripcion.pas' {fraStaticCodigoDescripcion: TFrame},
  unCustomConsulta in '..\Comunes\REPOSIT\unCustomConsulta.pas' {frmCustomConsulta},
  unCustomSplash in '..\Comunes\REPOSIT\unCustomSplash.pas' {frmCustomSplash},
  unWelcomeSplash in '..\Comunes\Forms\unWelcomeSplash.pas' {frmWelcomeSplash},
  unCustomGridABM in '..\Comunes\REPOSIT\unCustomGridABM.pas' {frmCustomGridABM},
  unManRTA_TIPOARCHIVO in 'ABM\unManRTA_TIPOARCHIVO.pas' {frmManRTA_TIPOARCHIVO},
  unCustomPanelABM in '..\Comunes\REPOSIT\unCustomPanelABM.pas' {frmCustomPanelABM},
  unManRAD_ARCHIVODOCUMENTO in 'ABM\unManRAD_ARCHIVODOCUMENTO.pas' {frmManRAD_ARCHIVODOCUMENTO},
  unFraUsuario in '..\Comunes\FRAMES\NEW\unFraUsuario.pas' {fraUsuarios: TFrame},
  unFraStaticCTB_TABLAS in '..\Comunes\FRAMES\unFraStaticCTB_TABLAS.pas' {fraStaticCTB_TABLAS: TFrame},
  unFraEmpresa in '..\Comunes\FRAMES\new\unFraEmpresa.pas' {fraEmpresa: TFrame},
  unFraTrabajador in '..\Comunes\FRAMES\NEW\unFraTrabajador.pas' {fraTrabajador: TFrame},
  unFraEstablecimiento in '..\Comunes\FRAMES\new\unFraEstablecimiento.pas' {fraEstablecimiento: TFrame},
  unRptEtiquetas in 'unRptEtiquetas.pas' {rptEtiquetas: TQuickRep},
  unfraArchJuicio in 'FRAMES\unfraArchJuicio.pas' {fraArchJuicio: TFrame},
  unManRDO_DOCUMENTO in 'ABM\unManRDO_DOCUMENTO.pas' {frmManRDO_DOCUMENTO},
  unManRAU_ARCHIVOUSUARIO in 'ABM\unManRAU_ARCHIVOUSUARIO.pas' {frmManRAU_ARCHIVOUSUARIO},
  unFraFiltroArchivo in 'frames\unFraFiltroArchivo.pas' {fraFiltroArchivo: TFrame},
  unFrmConsultaCarpetas in 'unFrmConsultaCarpetas.pas' {FrmConsultaCarpetas},
  unArchivo in 'unArchivo.pas',
  unFrmSolicitudCarpeta in 'unFrmSolicitudCarpeta.pas' {FrmSolicitudCarpeta},
  Email in '..\..\Paquetes\Temail\compon\Email.pas',
  unfraContacto in '..\Comunes\FRAMES\unfraContacto.pas' {fraContacto: TFrame},
  unFraTelefono in '..\Comunes\FRAMES\NEW\unFraTelefono.pas' {fraTelefono: TFrame},
  unABMTelefonos in '..\Comunes\Forms\unABMTelefonos.pas' {frmTelefonos},
  unFraCodDesc in '..\Comunes\FRAMES\NUEVOS\unFraCodDesc.pas' {fraCodDesc: TFrame},
  unCustomDataModule in '..\Comunes\unCustomDataModule.pas' {dmCustomDataModule: TDataModule},
  unQrDetalleLote in 'unQrDetalleLote.pas' {QrDetalleLote: TQuickRep},
  unART in '..\..\Comunes\unART.pas',
  unFraCtbTablas in '..\Comunes\Frames\unFraCtbTablas.pas' {fraCtbTablas: TFrame},
  unfraUsuarios in '..\Comunes\Frames\unfraUsuarios.pas' {fraUsuario: TFrame},
  unfraSectores in '..\Comunes\Frames\unfraSectores.pas' {fraSectores: TFrame},
  unFrmDetalleArchivo in 'unFrmDetalleArchivo.pas' {FrmDetalleArchivo},
  unConstantArchivo in 'unConstantArchivo.pas',
  unUtilsArchivo in 'unUtilsArchivo.pas',
  unfrmUbicacionActual in 'unfrmUbicacionActual.pas' {FrmUbicacionActual},
  unFraParametroValor in '..\Comunes\Frames\unFraParametroValor.pas' {fraParametroValor: TFrame},
  unFrmAdministracionParametros in 'unFrmAdministracionParametros.pas' {FrmAdministracionParametros},
  unfraCodigoDescripcionExt in '..\Comunes\Frames\unfraCodigoDescripcionExt.pas' {fraCodigoDescripcionExt: TFrame},
  unComunesMail in '..\..\Comunes\unComunesMail.pas',
  unFrmCargaDocumentacion in 'unFrmCargaDocumentacion.pas' {frmCargaDocumentacion},
  unFrmArmadoLote in 'unFrmArmadoLote.pas' {FrmArmadoLote: TFSForm},
  unFrmArmadoRemito in 'unFrmArmadoRemito.pas' {FrmConsultaLotes: TFSForm},
  unQrDetalleRemito in 'unQrDetalleRemito.pas' {QrDetalleRemito},
  unFraDetalleArchivo in 'frames\unFraDetalleArchivo.pas' {fraDetalleArchivo: TFrame},
  unTelefonosCargaRapida in '..\comunes\forms\unTelefonosCargaRapida.pas' {frmTelefonosCargaRapida},
  unDebug in '..\comunes\unDebug.pas' {frmDebug},
  General in '..\..\comunes\General.pas',
  unCustomForm in '..\comunes\unCustomForm.pas' {frmCustomForm},
  unFraToolbarRTF in '..\comunes\frames\unFraToolbarRTF.pas' {fraToolbarRTF: TFrame},
  unContratoContacto in '..\comunes\forms\unContratoContacto.pas' {frmContratoContacto},
  unFraStaticCodDesc in '..\comunes\frames\nuevos\unFraStaticCodDesc.pas' {fraStaticCodDesc: TFrame},
  unSesion in '..\..\comunes\unSesion.pas',
  unMoldeEnvioMail in '..\comunes\envio de mails\unMoldeEnvioMail.pas' {frmMoldeEnvioMail},
  unLibretaDeDirecciones in '..\comunes\forms\unLibretaDeDirecciones.pas' {frmLibretaDeDirecciones},
  unElementosEnviados in '..\comunes\forms\unElementosEnviados.pas' {frmElementosEnviados},
  unEspera in '..\comunes\forms\unEspera.pas' {frmEspera},
  unCapturarCodigoBarras in '..\comunes\unCapturarCodigoBarras.pas' {frmCapturarCodigoBarras},
  unManCtbTablas in '..\Comunes\Forms\unManCtbTablas.pas' {frmManCtbTablas},
  unMovimientoCarpetas in 'unMovimientoCarpetas.pas' {frmMovimientoCarpetas},
  unManUbicacionArchivos in 'abm\unManUbicacionArchivos.pas' {frmManUbicacionArchivos: TFSForm},
  VCLExtra in '..\..\comunes\VCLExtra.pas',
  unFraRTD_TIPODOCUMENTO in '..\comunes\frames\new\unFraRTD_TIPODOCUMENTO.pas' {fraRTD_TIPODOCUMENTO: TFrame},
  unFraVistaTIFF in '..\comunes\frames\new\unFraVistaTIFF.pas' {fraVistaTIFF: TFrame},
  unDocumentacionPorSector in 'unDocumentacionPorSector.pas' {frmDocumentacionPorSector},
  unSeleccionDestinatarios in '..\comunes\unSeleccionDestinatarios.pas' {frmSeleccionDestinatarios: TFSForm},
  unEstrategiaTIFF in '..\fax\faxclient_new\unEstrategiaTIFF.pas',
  unConsFax in '..\comunes\forms\unConsFax.pas' {frmConsFax},
  unfraFFO_FAXFORMULARIO in '..\fax\faxclient_new\frames\unfraFFO_FAXFORMULARIO.pas' {fraFFO_FAXFORMULARIO: TFrame},
  unFaxEnviados in '..\comunes\forms\unFaxEnviados.pas' {frmFaxEnviados},
  unManCRR_RESPUESTA in '..\comunes\forms\unManCRR_RESPUESTA.pas' {frmManCRR_RESPUESTA},
  unfraVendedores in '..\comunes\frames\unfraVendedores.pas' {fraVendedores: TFrame},
  unfraVendedoresCUIT in '..\comunes\frames\new\unfraVendedoresCUIT.pas' {fraVendedoresCUIT: TFrame},
  unfraEntidadCUIT in '..\comunes\frames\new\unfraEntidadCUIT.pas' {fraEntidadCUIT: TFrame},
  unfraCPR_PRESTADOR in '..\comunes\frames\new\unfraCPR_PRESTADOR.pas' {fraCPR_PRESTADOR: TFrame},
  CustomDlgs in '..\..\Comunes\CustomDlgs.pas',
  unSiniestros in '..\siniestros\unSiniestros.pas',
  unComunesArchivo in 'unComunesArchivo.pas',
  ungrids in '..\..\comunes\ungrids.pas',
  unFraTrabajadorSiniestro in '..\Comunes\FRAMES\NEW\unFraTrabajadorSiniestro.pas' {fraTrabajadorSiniestro: TFrame},
  unFraNavegadorWEB in '..\comunes\frames\new\unFraNavegadorWEB.pas' {fraNavegadorWEB: TFrame},
  unGoogleMaps in '..\comunes\forms\unGoogleMaps.pas' {frmGoogleMaps},
  unFraDomicilioGIS in '..\comunes\frames\new\unFraDomicilioGIS.pas' {fraDomicilioGIS: TFrame},
  unBusquedaDomicilio in '..\comunes\forms\unBusquedaDomicilio.pas' {frmBusquedaDomicilio: TFSForm},
  unFraDomicilio in '..\comunes\frames\new\unFraDomicilio.pas' {fraDomicilio: TFrame},
  unComunes in '..\..\comunes\unComunes.pas',
  unRptCartaDocHeader in '..\comunes\reports\unRptCartaDocHeader.pas' {rptCartaDocHeader: TQuickRep},
  unVisorPDF in '..\comunes\forms\unVisorPDF.pas' {frmVisorPDF},
  unVisualizador in '..\comunes\unVisualizador.pas' {frmVisualizador},
  Sendkey in '..\..\comunes\Sendkey.pas',
  OneSession in '..\..\comunes\OneSession.pas',
  unDmFinancials in '..\comunes\oracle\unDmFinancials.pas' {dmFinancials: TDataModule},
  unQrDetalleLoteEstudio in 'unQrDetalleLoteEstudio.pas' {QrDetalleLoteEstudio: TQuickRep},
  unfraProveedor in '..\comunes\frames\new\unfraProveedor.pas' {fraProveedor: TFrame},
  unSolicitudCarpetaUsuario in 'unSolicitudCarpetaUsuario.pas' {frmSolicitudCarpetaUsuario},
  unImpoExpoWizard in '..\ImpoExpo\unImpoExpoWizard.pas' {frmImpoExpoWizard},
  unRptResumenLotes in 'unRptResumenLotes.pas' {qrResumenLotes: TQuickRep},
  unComisiones in '..\afiliaciones\comisiones\unComisiones.pas',
  unTercerizadoras in '..\..\Comunes\unTercerizadoras.pas',
  unVisor in '..\comunes\forms\unVisor.pas' {frmVisor},
  unArchivoVisor in '..\comunes\unArchivoVisor.pas',
  unVisorExcel in '..\comunes\forms\unVisorExcel.pas' {frmVisorExcel},
  unStockLotes in 'unStockLotes.pas' {frmStockLotes: TFSForm},
  unHistoricoLote in 'unHistoricoLote.pas' {frmHistoricoLote: TFSForm},
  unRptResumenLotesEnviados in 'unRptResumenLotesEnviados.pas' {qrResumenLotesEnviados: TQuickRep},
  unQrEtiquetasDocCarpetas in 'unQrEtiquetasDocCarpetas.pas' {qrEtiquetasDocCarpetas: TQuickRep},
  unQrEtiquetasCarpetas in 'unQrEtiquetasCarpetas.pas' {qrEtiquetasCarpetas: TQuickRep},
  unReemplazoCarpetas in 'unReemplazoCarpetas.pas' {frmReemplazoCarpetas},
  unNovedades in '..\..\comunes\unNovedades.pas',
  unClasificacionActivos in '..\comunes\forms\unClasificacionActivos.pas' {frmClasificacionActivos: TFSForm},
  unSeleccionMultiple in '..\comunes\forms\unSeleccionMultiple.pas' {frmSeleccionUsuarios: TFrame},
  unManCGI_GIS in '..\comunes\forms\unManCGI_GIS.pas' {frmManCGI_GIS: TFSForm},
  unAnexoRes365 in '..\comunes\forms\unAnexoRes365.pas' {frmAnexoRes365},
  unVentanillaElectronica in '..\comunes\forms\unVentanillaElectronica.pas' {frmVentanillaElectronica: TFSForm},
  unAgendaTelefonica in '..\comunes\forms\unAgendaTelefonica.pas' {frmAgendaTelefonica: TFSForm},
  unfraDelegacion in '..\comunes\frames\unfraDelegacion.pas' {fraDelegacion: TFrame},
  unRptGestionDeReclamos in '..\comunes\reports\unRptGestionDeReclamos.pas' {frmRptGestionDeReclamos},
  unFormularioValidacionYRectificacionDatosEstablecimientos in '..\comunes\forms\unFormularioValidacionYRectificacionDatosEstablecimientos.pas' {frmFormularioValidacionYRectificacionDatosEstablecimientos},
  unRptFormularioValidacionYRectificacionDatosEstablecimientos in '..\comunes\reports\unRptFormularioValidacionYRectificacionDatosEstablecimientos.pas' {qrFormularioValidacionYRectificacionDatosEstablecimientos: TQuickRep},
  unRptEstadisticasRGRL in '..\comunes\reports\unRptEstadisticasRGRL.pas' {qrEstadisticasRGRL: TQuickRep},
  unRptRGRL in '..\comunes\reports\unRptRGRL.pas' {qrRGRL: TQuickRep},
  unRGRL in '..\comunes\forms\unRGRL.pas' {frmRGRL},
  unManCPG_PLAZOGUARDA in '..\comunes\forms\unManCPG_PLAZOGUARDA.pas' {frmManCPG_PLAZOGUARDA: TFSForm},
  unManCTA_TIPOACTIVOS in '..\comunes\forms\unManCTA_TIPOACTIVOS.pas' {frmManCTA_TIPOACTIVOS: TFSForm},
  unFraEmpresaAfi in '..\comunes\frames\new\unFraEmpresaAfi.pas' {fraEmpresaAfi: TFrame},
  unRptAnexoRes365 in '..\comunes\reports\unRptAnexoRes365.pas' {qrAnexoRes365: TQuickRep},
  unCustomPrincipal in '..\comunes\reposit\unCustomPrincipal.pas' {frmCustomPrincipal},
  unControlVersion in '..\..\comunes\unControlVersion.pas',
  unRptPlantillaRGRL in '..\comunes\reports\unRptPlantillaRGRL.pas' {qrPlantillaRGRL: TQuickRep},
  unVerImagenes in 'unVerImagenes.pas' {frmVerImagenes},
  GraphicUtils in '..\..\comunes\GraphicUtils.pas',
  unImageFunctions in '..\..\comunes\unImageFunctions.pas',
  unEnviosRecepcionDoc in 'unEnviosRecepcionDoc.pas' {frmEnviosRecepcionDoc: TFSForm},
  unQrRemitoEnvioRecepcionDoc in 'unQrRemitoEnvioRecepcionDoc.pas' {qrRemitoEnvioRecepcionDoc},
  unCargaDocumentosDigitaliz in '..\comunes\forms\unCargaDocumentosDigitaliz.pas' {frmCargaDocumentosDigitaliz},
  unDigitalizacion in '..\..\comunes\unDigitalizacion.pas',
  unfraPrestador in '..\comunes\frames\unfraPrestador.pas' {fraPrestador: TFrame},
  unMigracionBANK in 'unMigracionBANK.pas' {frmMigracionBANK},
  unImportarImagRepositorio in 'unImportarImagRepositorio.pas' {frmImportarImagRepositorio: TFSForm},
  unConsultarRepositorio in 'unConsultarRepositorio.pas' {frmConsultarRepositorio: TFSForm},
  unRptResumenRepositorio in 'unRptResumenRepositorio.pas' {qrResumenRepositorio: TQuickRep},
  unTesoreria in '..\afiliaciones\tesoreria\unTesoreria.pas',
  unConsultaCartasDoc in 'unConsultaCartasDoc.pas' {frmConsultaCartasDoc: TFSForm},
  unManErroresUsuarios in 'abm\unManErroresUsuarios.pas' {frmManErroresUsuarios: TFSForm},
  unSeguimientoErroresUsuarios in 'unSeguimientoErroresUsuarios.pas' {frmSeguimientoErroresUsuarios: TFSForm},
  unQrResumenErrores in 'unQrResumenErrores.pas' {qrResumenErrores: TQuickRep},
  unQrResumenErroresUsuario in 'unQrResumenErroresUsuario.pas' {qrResumenErroresUsuario: TQuickRep},
  FormPanel in '..\..\paquetes\FormPanel.pas',
  unRTTI in '..\..\comunes\unRTTI.pas',
  unEstadisticasImagenes in 'unEstadisticasImagenes.pas' {frmEstadisticasImagenes: TFSForm},
  unRptCartaDocumento in '..\Comunes\REPORTS\unRptCartaDocumento.pas' {rptCartaDocumento: TQuickRep},
  unAfiliaciones in '..\afiliaciones\unAfiliaciones.pas',
  unSIC in '..\..\comunes\unSIC.pas',
  unQrDetalleRemitoDevolucion in 'unQrDetalleRemitoDevolucion.pas' {QrDetalleRemitoDevolucion},
  unManCVS_VENTANILLA_SUBTEMAS in '..\comunes\forms\unManCVS_VENTANILLA_SUBTEMAS.pas' {frmManCVS_VENTANILLA_SUBTEMAS: TFSForm},
  unQrRemitoAdminEnvioRecepcionDoc in 'unQrRemitoAdminEnvioRecepcionDoc.pas' {qrRemitoAdminEnvioRecepcionDoc},
  unConsErroresUsuarios in 'unConsErroresUsuarios.pas' {frmConsErroresUsuarios: TFSForm},
  unManCriticidadSectores in 'abm\unManCriticidadSectores.pas',
  unCargaUbicCarpetasAdmin in 'unCargaUbicCarpetasAdmin.pas' {frmCargaUbicCarpetasAdmin},
  unErroresUbicCarpetas in 'unErroresUbicCarpetas.pas' {frmErroresUbicCarpetas: TFSForm},
  unControlStockCajas in 'unControlStockCajas.pas' {frmControlStockCajas: TFSForm},
  unQrResumenControlStockCajas in 'unQrResumenControlStockCajas.pas' {qrResumenControlStockCajas: TQuickRep},
  libgfl in '..\..\comunes\libgfl.pas',
  unMensajeAlerta in '..\..\comunes\unMensajeAlerta.pas',
  unAlarmas in '..\..\comunes\unAlarmas.pas',
  unMensajeAlertaAGA in 'unMensajeAlertaAGA.pas',
  unFraGIS_APIv3 in '..\comunes\frames\new\unFraGIS_APIv3.pas' {fraGIS_APIv3: TFrame},
  unGIS in '..\..\comunes\unGIS.pas',
  unFraWebBrowser in '..\comunes\frames\new\unFraWebBrowser.pas' {fraWebBrowser: TFrame},
  unExportPDF in '..\..\comunes\unExportPDF.pas',
  unEsperaSimple in '..\comunes\forms\unEsperaSimple.pas' {frmEsperaSimple},
  IArtMail in '..\comunes\IArtMail.pas',
  unEnvioSMS in '..\comunes\forms\unEnvioSMS.pas' {frmEnvioSMS},
  unManCajas in 'abm\unManCajas.pas' {frmManCajas: TFSForm},
  unTableroControl in 'unTableroControl.pas' {frmTableroControl: TFSForm},
  unFraActividad in '..\comunes\frames\unFraActividad.pas' {fraActividad: TFrame},
  unEstablecimientosTrabajador in '..\Afiliaciones\unEstablecimientosTrabajador.pas' {frmEstablecimientosTrabajador},
  unContratoTrabajador in '..\Afiliaciones\unContratoTrabajador.pas' {frmContratoTrabajador},
  unFraDomicilioTrab in '..\Comunes\FRAMES\NEW\unFraDomicilioTrab.pas' {fraDomicilioTrab: TFrame},
  unManCCP_CUENTAPAGO in '..\Comunes\Forms\unManCCP_CUENTAPAGO.pas' {frmManCCP_CUENTAPAGO},
  unAltaModifCCP_CUENTAPAGO in '..\Comunes\Forms\unAltaModifCCP_CUENTAPAGO.pas' {frmAltaModifCCP_CUENTAPAGO},
  unDlgBusSiniestro in '..\siniestros\unDlgBusSiniestro.pas' {frmDlgBusSiniestro: TFSForm},
  unArmadoSQL in '..\comunes\forms\unArmadoSQL.pas' {frmArmadoSQL};

{$R *.RES}

begin
  OnlyOneInstance ;
  Application.Initialize;
  Application.Title := 'Administrador de Carpetas';

  with TfrmWelcomeSplash.Create(Application) do
  try
    ShowOnTop;
    Application.CreateForm(TdmPrincipal, dmPrincipal);
  Application.CreateForm(TdmFinancials, dmFinancials);
  if dmPrincipal.sdbPrincipal.Connected then
    begin
      OnlyOneSession;
      if GetTienePerfil then
        Application.CreateForm(TfrmPrincipal, frmPrincipal)
      else
      begin
        Hide;
        MessageBox(0, 'No posee perfil de usuario de archivo ' + #13+#10 +
                      'para operar con esta aplicación.',
                      'Ingreso al Sistema de Archivo', MB_ICONSTOP or MB_OK);
      end;
    end;
  finally
    Free;
  end;
  MostrarNovedades;
  Application.Run;
end.

