program Dinerarias;

{$R *.dres}

uses
  OneInstance,
  Forms,
  Controls,
  Windows,
  unPrincipal in 'unPrincipal.pas' {frmPrincipal},
  unCustomDataModule in '..\comunes\unCustomDataModule.pas' {dmCustomDataModule: TDataModule},
  unCustomConsulta in '..\comunes\reposit\unCustomConsulta.pas' {frmCustomConsulta: TFSForm},
  unDebug in '..\comunes\unDebug.pas' {frmDebug},
  unEspera in '..\comunes\forms\unEspera.pas' {frmEspera},
  unArt in '..\..\Comunes\unArt.pas',
  unCustomSplash in '..\Comunes\REPOSIT\unCustomSplash.pas' {frmCustomSplash},
  unWelcomeSplash in '..\Comunes\Forms\unWelcomeSplash.pas' {frmWelcomeSplash},
  VCLExtra in '..\..\Comunes\VCLExtra.pas',
  AnsiSql in '..\..\Comunes\AnsiSql.pas',
  DbFuncs in '..\..\Comunes\DbFuncs.pas',
  unSesion in '..\..\Comunes\unSesion.pas',
  CustomDlgs in '..\..\Comunes\CustomDlgs.pas',
  unCustomForm in '..\comunes\unCustomForm.pas' {frmCustomForm},
  General in '..\..\Comunes\General.pas',
  unCITRIX in '..\..\Comunes\unCITRIX.pas',
  DateTimeFuncs in '..\..\Comunes\DateTimeFuncs.pas',
  Cuit in '..\..\Comunes\Cuit.pas',
  strfuncs in '..\..\Comunes\strfuncs.pas',
  numeros in '..\..\Comunes\numeros.pas',
  unNovedades in '..\..\Comunes\unNovedades.pas',
  unDmFinancials in '..\comunes\oracle\unDmFinancials.pas' {dmFinancials: TDataModule},
  unDmPrincipal in '..\comunes\oracle\unDmPrincipal.pas' {dmPrincipal: TDataModule},
  unArtDbFrame in '..\Comunes\REPOSIT\unArtDbFrame.pas' {ArtDbFrame: TFrame},
  unArtFrame in '..\Comunes\REPOSIT\unArtFrame.pas' {ArtFrame: TFrame},
  unArtDBAwareFrame in '..\Comunes\REPOSIT\unArtDBAwareFrame.pas' {ArtDBAwareFrame: TFrame},
  unFraTrabajador in '..\Comunes\FRAMES\NEW\unFraTrabajador.pas' {fraTrabajador: TFrame},
  unFraTrabajadorSiniestro in '..\Comunes\FRAMES\NEW\unFraTrabajadorSiniestro.pas' {fraTrabajadorSiniestro: TFrame},
  unFraCtbTablas in '..\Comunes\FRAMES\unFraCtbTablas.pas' {fraCtbTablas: TFrame},
  unFraCodigoDescripcion in '..\Comunes\FRAMES\unFraCodigoDescripcion.pas' {fraCodigoDescripcion: TFrame},
  unFraEmpresa in '..\Comunes\FRAMES\NEW\unFraEmpresa.pas' {fraEmpresa: TFrame},
  unBusquedaDomicilio in '..\Comunes\Forms\unBusquedaDomicilio.pas' {frmBusquedaDomicilio},
  unCustomPanelABM in '..\Comunes\REPOSIT\unCustomPanelABM.pas' {frmCustomPanelABM},
  unCustomGridABM in '..\Comunes\REPOSIT\unCustomGridABM.pas' {frmCustomGridABM},
  unFraDomicilio in '..\Comunes\FRAMES\NEW\unFraDomicilio.pas' {fraDomicilio: TFrame},
  UnBeneficiarios in 'UnBeneficiarios.pas' {frmBeneficiarios: TFSForm},
  UnLiqBeneficiarios in 'UnLiqBeneficiarios.pas' {frmLiqBeneficiarios: TFSForm},
  unRPTPagoAdic in 'reports\unRPTPagoAdic.pas' {qrPagoAdic},
  unrptliq53 in 'reports\unrptliq53.pas' {Rpt531: TQuickRep},
  unrptliq53b in 'reports\unrptliq53b.pas' {rpt532: TQuickRep},
  unrptliq8 in 'reports\unrptliq8.pas' {Rpt81: TQuickRep},
  unrptliq8b in 'reports\unrptliq8b.pas' {rpt82: TQuickRep},
  unrptliq8Rep in 'reports\unrptliq8Rep.pas' {Rpt8Rep: TQuickRep},
  unrptliq8repb in 'reports\unrptliq8repb.pas' {rpt8rep2: TQuickRep},
  unrptSolicitudCotizacionRentaVit in 'reports\unrptSolicitudCotizacionRentaVit.pas' {rptSolicitudCotizacionRentaVit: TQuickRep},
  unRptLiqReciboPagoUnico in 'reports\unRptLiqReciboPagoUnico.pas' {frmRptReciboPagoUnico},
  unRptAnticipoRentaVit in 'reports\unRptAnticipoRentaVit.pas' {frmRptAnticipoRentaVit},
  unCancelarLiquidacion in 'unCancelarLiquidacion.pas' {frmCancelarLiquidacion},
  unfraPrestador in '..\comunes\frames\unfraPrestador.pas' {fraPrestador: TFrame},
  OneSession in '..\..\comunes\OneSession.pas',
  unSeleccionDestinatarios in '..\comunes\unSeleccionDestinatarios.pas' {frmSeleccionDestinatarios: TFSForm},
  unFraDigitalizacion in '..\comunes\frames\new\unFraDigitalizacion.pas' {fraDigitalizacion: TFrame},
  unFraEntidades in '..\comunes\frames\unFraEntidades.pas' {fraEntidades: TFrame},
  unfraVendedores in '..\comunes\frames\unfraVendedores.pas' {fraVendedores: TFrame},
  unfraVendedoresCUIT in '..\comunes\frames\new\unfraVendedoresCUIT.pas' {fraVendedoresCUIT: TFrame},
  unfraEntidadCUIT in '..\comunes\frames\new\unfraEntidadCUIT.pas' {fraEntidadCUIT: TFrame},
  unFraCodDesc in '..\comunes\frames\nuevos\unFraCodDesc.pas' {fraCodDesc: TFrame},
  unContratoContacto in '..\comunes\forms\unContratoContacto.pas' {frmContratoContacto},
  unfraContacto in '..\comunes\frames\unfraContacto.pas' {fraContacto: TFrame},
  unFraStaticCodigoDescripcion in '..\comunes\frames\unFraStaticCodigoDescripcion.pas' {fraStaticCodigoDescripcion: TFrame},
  unFraStaticCTB_TABLAS in '..\comunes\frames\unFraStaticCTB_TABLAS.pas' {fraStaticCTB_TABLAS: TFrame},
  unFraRTD_TIPODOCUMENTO in '..\comunes\frames\new\unFraRTD_TIPODOCUMENTO.pas' {fraRTD_TIPODOCUMENTO: TFrame},
  unFraTelefono in '..\comunes\frames\new\unFraTelefono.pas' {fraTelefono: TFrame},
  unABMTelefonos in '..\comunes\forms\unABMTelefonos.pas' {frmTelefonos},
  unTelefonosCargaRapida in '..\comunes\forms\unTelefonosCargaRapida.pas' {frmTelefonosCargaRapida},
  unLibretaDeDirecciones in '..\comunes\forms\unLibretaDeDirecciones.pas' {frmLibretaDeDirecciones: TFSForm},
  unFraUsuario in '..\comunes\frames\new\unFraUsuario.pas' {fraUsuarios: TFrame},
  unFraToolbarRTF in '..\comunes\frames\unFraToolbarRTF.pas' {fraToolbarRTF: TFrame},
  unFraEstablecimiento in '..\comunes\frames\new\unFraEstablecimiento.pas' {fraEstablecimiento: TFrame},
  unfraCPR_PRESTADOR in '..\comunes\frames\new\unfraCPR_PRESTADOR.pas' {fraCPR_PRESTADOR: TFrame},
  unRptCartaDocHeader in '..\comunes\reports\unRptCartaDocHeader.pas' {rptCartaDocHeader: TQuickRep},
  unMoldeEnvioMail in '..\comunes\envio de mails\unMoldeEnvioMail.pas' {frmMoldeEnvioMail},
  unVisualizadorDigitalizacion in '..\comunes\forms\unVisualizadorDigitalizacion.pas' {frmVisualizadorDigitalizacion: TFSForm},
  unFraVistaTIFF in '..\comunes\frames\new\unFraVistaTIFF.pas' {fraVistaTIFF: TFrame},
  unCustomPrincipal in '..\comunes\reposit\unCustomPrincipal.pas' {frmCustomPrincipal},
  unFaxEnviados in '..\comunes\forms\unFaxEnviados.pas' {frmFaxEnviados: TFSForm},
  unfraUsuarios in '..\comunes\frames\unfraUsuarios.pas' {fraUsuario: TFrame},
  unEstrategiaTIFF in '..\fax\faxclient_new\unEstrategiaTIFF.pas',
  unElementosEnviados in '..\comunes\forms\unElementosEnviados.pas' {frmElementosEnviados: TFSForm},
  unConsFax in '..\comunes\forms\unConsFax.pas' {frmConsFax: TFSForm},
  unfraFFO_FAXFORMULARIO in '..\comunes\frames\unfraFFO_FAXFORMULARIO.pas' {fraFFO_FAXFORMULARIO: TFrame},
  unfraCuentaBancaria in '..\comunes\frames\new\unfraCuentaBancaria.pas' {fraCuentaBancaria: TFrame},
  unFraNavegadorWEB in '..\comunes\frames\new\unFraNavegadorWEB.pas' {fraNavegadorWEB: TFrame},
  unfraCodigoDescripcionExt in '..\comunes\frames\unfraCodigoDescripcionExt.pas' {fraCodigoDescripcionExt: TFrame},
  unFraDomicilioGIS in '..\comunes\frames\new\unFraDomicilioGIS.pas' {fraDomicilioGIS: TFrame},
  unSeleccionMultiple in '..\comunes\forms\unSeleccionMultiple.pas' {frmSeleccionUsuarios: TFrame},
  unClasificacionActivos in '..\comunes\forms\unClasificacionActivos.pas' {frmClasificacionActivos: TFSForm},
  unGoogleMaps in '..\comunes\forms\unGoogleMaps.pas' {frmGoogleMaps},
  unFraEmpresaAfi in '..\comunes\frames\new\unFraEmpresaAfi.pas' {fraEmpresaAfi: TFrame},
  unAnexoRes365 in '..\comunes\forms\unAnexoRes365.pas' {frmAnexoRes365},
  unFormularioValidacionYRectificacionDatosEstablecimientos in '..\comunes\forms\unFormularioValidacionYRectificacionDatosEstablecimientos.pas' {frmFormularioValidacionYRectificacionDatosEstablecimientos},
  unRGRL in '..\comunes\forms\unRGRL.pas' {frmRGRL},
  unManCTA_TIPOACTIVOS in '..\comunes\forms\unManCTA_TIPOACTIVOS.pas' {frmManCTA_TIPOACTIVOS: TFSForm},
  unVisorPDF in '..\comunes\forms\unVisorPDF.pas' {frmVisorPDF},
  unManCGI_GIS in '..\comunes\forms\unManCGI_GIS.pas' {frmManCGI_GIS: TFSForm},
  unVisualizador in '..\comunes\unVisualizador.pas' {frmVisualizador},
  unRptRGRL in '..\comunes\reports\unRptRGRL.pas' {qrRGRL: TQuickRep},
  unRptAnexoRes365 in '..\comunes\reports\unRptAnexoRes365.pas' {qrAnexoRes365: TQuickRep},
  unRptFormularioValidacionYRectificacionDatosEstablecimientos in '..\comunes\reports\unRptFormularioValidacionYRectificacionDatosEstablecimientos.pas' {qrFormularioValidacionYRectificacionDatosEstablecimientos: TQuickRep},
  unAgendaTelefonica in '..\comunes\forms\unAgendaTelefonica.pas' {frmAgendaTelefonica: TFSForm},
  unManCPG_PLAZOGUARDA in '..\comunes\forms\unManCPG_PLAZOGUARDA.pas' {frmManCPG_PLAZOGUARDA: TFSForm},
  unVentanillaElectronica in '..\comunes\forms\unVentanillaElectronica.pas' {frmVentanillaElectronica: TFSForm},
  unRptEstadisticasRGRL in '..\comunes\reports\unRptEstadisticasRGRL.pas' {qrEstadisticasRGRL: TQuickRep},
  unRptGestionDeReclamos in '..\comunes\reports\unRptGestionDeReclamos.pas' {frmRptGestionDeReclamos},
  unManRDO_DOCUMENTO in '..\archivo_new\abm\unManRDO_DOCUMENTO.pas' {frmManRDO_DOCUMENTO: TFSForm},
  unAfiliaciones in '..\Afiliaciones\unAfiliaciones.pas',
  unContratoTrabajador in '..\Afiliaciones\unContratoTrabajador.pas' {frmContratoTrabajador},
  unFraDomicilioTrab in '..\Comunes\FRAMES\NEW\unFraDomicilioTrab.pas' {fraDomicilioTrab: TFrame},
  unFraActividad in '..\comunes\frames\unFraActividad.pas' {fraActividad: TFrame},
  unRptCartaDocumento in '..\comunes\reports\unRptCartaDocumento.pas' {rptCartaDocumento: TQuickRep},
  unEstablecimientosTrabajador in '..\Afiliaciones\unEstablecimientosTrabajador.pas' {frmEstablecimientosTrabajador},
  unManCCP_CUENTAPAGO in '..\Comunes\Forms\unManCCP_CUENTAPAGO.pas' {frmManCCP_CUENTAPAGO},
  unAltaModifCCP_CUENTAPAGO in '..\Comunes\Forms\unAltaModifCCP_CUENTAPAGO.pas' {frmAltaModifCCP_CUENTAPAGO},
  unDlgBusSiniestro in '..\siniestros\unDlgBusSiniestro.pas' {frmDlgBusSiniestro: TFSForm},
  unSiniestros in '..\siniestros\unSiniestros.pas',
  unUtilsArchivo in '..\archivo_new\unUtilsArchivo.pas',
  unDatosSiniestro in '..\comunes\forms\unDatosSiniestro.pas' {frmDatosSiniestro},
  unImpoExpoWizard in '..\impoexpo\unImpoExpoWizard.pas' {frmImpoExpoWizard},
  unfraDelegacion in '..\comunes\frames\unfraDelegacion.pas' {fraDelegacion: TFrame},
  unListPagosDirILT in 'listados\unListPagosDirILT.pas' {frmListPagosDirILT: TFSForm},
  unListLiqDocUsuario in 'listados\unListLiqDocUsuario.pas' {frmListLiqDocUsuario},
  unListLiqIncapacidades in 'listados\unListLiqIncapacidades.pas' {frmListLiqIncapacidades},
  unLiquidacionesCompensables in 'listados\unLiquidacionesCompensables.pas' {frmLiquidacionesCompensables: TFSForm},
  unRptLiquidacionesCompensables in 'reports\unRptLiquidacionesCompensables.pas' {rptLiquidacionesCompensables: TQuickRep},
  unLiquidacionesAprobadas in '..\siniestros\unLiquidacionesAprobadas.pas' {frmLiquidacionesAprobadas},
  unManZonasAFIP in 'abm\unManZonasAFIP.pas' {frmManZonasAFIP: TFSForm},
  unManMotivoBajaLiqAut in 'abm\unManMotivoBajaLiqAut.pas' {frmManMotivoBajaLiqAut: TFSForm},
  unManCAN_CHEQUEANOMBRE in '..\comunes\forms\unManCAN_CHEQUEANOMBRE.pas' {frmManCAN_CHEQUEANOMBRE: TFSForm},
  unListGralLiquidaciones in 'listados\unListGralLiquidaciones.pas' {frmListGralLiquidaciones: TFSForm},
  unAperturaSiniestro in 'unAperturaSiniestro.pas' {frmAperturaSiniestro: TFSForm},
  uncomunes in '..\..\comunes\uncomunes.pas',
  unManSegRetiro in 'abm\unManSegRetiro.pas' {frmManSegRetiro},
  unManAFJP in 'abm\unManAFJP.pas' {frmManAFJP},
  unManEmpresasBloqueoILT in 'abm\unManEmpresasBloqueoILT.pas' {frmManEmpresasBloqueoILT: TFSForm},
  unMantMontosAsigFam in 'abm\unMantMontosAsigFam.pas' {frmMantMontosAsigFam},
  unMantTiposAsigFam in 'abm\unMantTiposAsigFam.pas' {frmMantTiposAsigFam},
  unMantEmpresasSinTopeAMPO in 'abm\unMantEmpresasSinTopeAMPO.pas' {frmMantEmpresasSinTopeAMPO},
  unMantImportesValoresAmpo in 'abm\unMantImportesValoresAmpo.pas' {frmMantImportesValoresAmpo},
  unLiqAprobacion in '..\siniestros\unLiqAprobacion.pas' {frmLiqAprobacion},
  unManObrasSociales in 'abm\unManObrasSociales.pas' {frmManObrasSociales: TFSForm},
  SqlFuncs in '..\..\comunes\SqlFuncs.pas',
  unLiqCartasDocumento in 'unLiqCartasDocumento.pas' {frmLiqCartasDoc: TFSForm},
  unCartasDocSinDDJJ in 'unCartasDocSinDDJJ.pas' {frmCartasDocSinDDJJ: TFSForm},
  unCartaDocumento in '..\comunes\reports\unCartaDocumento.pas',
  unRptCartDocCorreoArgentinoHeader in '..\comunes\reports\unRptCartDocCorreoArgentinoHeader.pas' {rptCartDocCorreoArgentinoHeader: TQuickRep},
  unRptCartDocCorreoArgentino in '..\comunes\reports\unRptCartDocCorreoArgentino.pas' {rptCartDocCorreoArgentino: TQuickRep},
  unfraFirmante in '..\comunes\frames\unfraFirmante.pas' {fraFirmante: TFrame},
  unClassEmpresa in '..\..\comunes\clases\unClassEmpresa.pas',
  unClassTrabajador in '..\..\comunes\clases\unClassTrabajador.pas',
  unRptResumen in '..\siniestros\reports\unRptResumen.pas' {rptResumen: TQuickRep},
  unClassExpediente in '..\..\comunes\clases\unClassExpediente.pas',
  unRptIncapacidadRecibo in 'reports\unRptIncapacidadRecibo.pas' {qrIncapacidadRecibo: TQuickRep},
  unRptResumenILT in 'reports\unRptResumenILT.pas' {qrResumenILT: TQuickRep},
  unLiqIncapacidades in 'unLiqIncapacidades.pas' {frmLiqIncapacidades},
  unClassLiquidacion in '..\..\comunes\clases\unClassLiquidacion.pas',
  unRptReciboILT in 'reports\unRptReciboILT.pas' {qrReciboILT: TQuickRep},
  unRptReciboILPPerDef in 'reports\unRptReciboILPPerDef.pas' {qrReciboILPPerDef: TQuickRep},
  unRptOrdenDePago in 'reports\unRptOrdenDePago.pas' {qrOrdenDePago: TQuickRep},
  unRptRemuneraciones in 'reports\unRptRemuneraciones.pas' {qrRemuneraciones: TQuickRep},
  unRptReciboOtrosConceptos in '..\siniestros\reports\unRptReciboOtrosConceptos.pas' {qrReciboOtrosConceptos: TQuickRep},
  unRptLiqOtrosConceptos in '..\siniestros\reports\unRptLiqOtrosConceptos.pas' {qrLiqOtrosConceptos: TQuickRep},
  unManAsigHijos in 'abm\unManAsigHijos.pas' {frmManAsigHijos},
  unManAsigEspeciales in 'abm\unManAsigEspeciales.pas' {frmManAsigEspeciales},
  unLiqAsigFam in 'unLiqAsigFam.pas' {frmLiqAsigFam},
  unCompaniaSeguroRetiro in 'unCompaniaSeguroRetiro.pas' {frmCompaniaSeguroRetiro},
  unConsultaNomina in '..\siniestros\unConsultaNomina.pas' {frmConsultaNomina: TFSForm},
  unRptFormSelRetiro in '..\comunes\reports\unRptFormSelRetiro.pas' {rptFormSelRetiro: TQuickRep},
  unRptFormularioCotizacion in 'reports\unRptFormularioCotizacion.pas' {rptFormularioCotizacion: TQuickRep},
  unRptResumenILP in 'reports\unRptResumenILP.pas' {qrResumenILP: TQuickRep},
  unLiqAutomaticas in 'unLiqAutomaticas.pas' {frmLiqAutomaticas},
  unfraInfoEmpresa in '..\comunes\frames\new\unfraInfoEmpresa.pas' {fraInfoEmpresa: TFrame},
  unOpcionesDeImpresion in '..\cobranzas\unOpcionesDeImpresion.pas' {frmOpcionesDeImpresion},
  unImpresionEstadoDeCuenta in '..\cobranzas\unImpresionEstadoDeCuenta.pas' {frmImpresionEstadodeCuenta},
  unQRF817 in '..\cobranzas\reports\unQRF817.pas' {QRF817: TQuickRep},
  unQRCartaDocIntimacion in '..\cobranzas\reports\unQRCartaDocIntimacion.pas' {QRCartaDocIntimacion: TQuickRep},
  unRptCartaDocCompensacion in '..\cobranzas\compensacion\reports\unRptCartaDocCompensacion.pas' {rptCartaDocCompensacion: TQuickRep},
  unQrLibreDeuda in '..\cobranzas\reports\unQrLibreDeuda.pas' {qrLibreDeuda: TQuickRep},
  unQrEstadoCuentaResumen in '..\cobranzas\reports\unQrEstadoCuentaResumen.pas' {frmEstadoCuentaResumen},
  unQRF801C in '..\cobranzas\reports\unQRF801C.pas' {QRF801C: TQuickRep},
  unQRCartaDocIntimacionNuevaGrilla in '..\cobranzas\reports\unQRCartaDocIntimacionNuevaGrilla.pas' {QRCartaDocIntimacionNuevaGrilla: TQuickRep},
  unConsultasAdicionales in '..\comunes\forms\unConsultasAdicionales.pas' {frmConsultasAdicionales},
  unEjecutivoCuenta in '..\comunes\forms\unEjecutivoCuenta.pas' {frmEjecutivoCuenta},
  unGestorCuenta in '..\comunes\forms\unGestorCuenta.pas' {frmGestorCuenta},
  unQrEstadoCuentaDetalle in '..\cobranzas\reports\unQrEstadoCuentaDetalle.pas' {frmEstadoCuentaDetalle},
  unfraInfoEmpresaExt in '..\comunes\frames\new\unfraInfoEmpresaExt.pas' {fraInfoEmpresaExt: TFrame},
  unConsultaEmpresa in '..\siniestros\unConsultaEmpresa.pas' {frmConsultaEmpresa: TFSForm},
  unTercerizadoras in '..\..\comunes\unTercerizadoras.pas',
  unEstadoCuenta in '..\cobranzas\unEstadoCuenta.pas',
  unRptCaratulaMortales in 'reports\unRptCaratulaMortales.pas' {qrCaratulaMortales: TQuickRep},
  unDinerarias in 'unDinerarias.pas',
  unListResumenDinerarias in 'listados\unListResumenDinerarias.pas' {frmListResumenDinerarias: TFSForm},
  unManLiquidadoresxCUIT in 'abm\unManLiquidadoresxCUIT.pas' {frmManLiquidadoresxCUIT: TFSForm},
  unSeguimientoDocumentacion in 'unSeguimientoDocumentacion.pas' {frmSeguimientoDocumentacion: TFSForm},
  unImpoExpoUtils in '..\impoexpo\unImpoExpoUtils.pas',
  unManEmpresasPagoDirectoILT in 'abm\unManEmpresasPagoDirectoILT.pas' {frmManEmpresasPagoDirectoILT: TFSForm},
  unSeguimientoCasosLiquidar in 'unSeguimientoCasosLiquidar.pas' {frmSeguimientoCasosLiquidar: TFSForm},
  unManTipoDocumento in 'abm\unManTipoDocumento.pas' {frmManTipoDocumento: TFSForm},
  unListAportesContribuciones in 'listados\unListAportesContribuciones.pas' {frmListAportesContribuciones: TFSForm},
  unManMotivosAportes in '..\redpres\abm\unManMotivosAportes.pas' {frmManMotivosAportes: TFSForm},
  ungrids in '..\..\comunes\ungrids.pas',
  unGeneracionIntereses in 'admliq\unGeneracionIntereses.pas' {frmGeneracionIntereses},
  unGeneracionOPagos in 'admliq\unGeneracionOPagos.pas' {frmGeneracionOPagos},
  unListControversiaReserva in 'listados\unListControversiaReserva.pas' {frmListControversiaReserva: TFSForm},
  unGeneracionTasaJusticia in 'admliq\unGeneracionTasaJusticia.pas' {frmGeneracionTasaJusticia},
  unfraFirmantes in '..\comunes\frames\new\unfraFirmantes.pas' {fraFirmantes: TFrame},
  unListSiniestrosConEmbargo in 'listados\unListSiniestrosConEmbargo.pas' {frmListSiniestrosConEmbargo: TFSForm},
  unManAcreedores in '..\comunes\forms\unManAcreedores.pas' {frmManAcreedores: TFSForm},
  unRptFormularioCotizacionTot in 'reports\unRptFormularioCotizacionTot.pas' {rptFormularioCotizacionTot: TQuickRep},
  unRptReciboRetiraDocum in 'reports\unRptReciboRetiraDocum.pas' {rptReciboRetiraDocum: TQuickRep},
  unAgenda in '..\..\comunes\interfaces\unAgenda.pas',
  unfraContactoAGENDA in '..\comunes\frames\modulosAgenda\unfraContactoAGENDA.pas' {fraContactoAGENDA: TFrame},
  unfraContactoLibreAGENDA in '..\comunes\frames\modulosAgenda\unfraContactoLibreAGENDA.pas' {fraContactoLibreAGENDA: TFrame},
  unfraDomicilioAGENDA in '..\comunes\frames\modulosAgenda\unfraDomicilioAGENDA.pas' {fraDomicilioGISAGENDA: TFrame},
  unfraDomicilioEmpresaAGENDA in '..\comunes\frames\modulosAgenda\unfraDomicilioEmpresaAGENDA.pas' {fraDomicilioEmpresaAGENDA: TFrame},
  unfraDomicilioEstablecimientoAGENDA in '..\comunes\frames\modulosAgenda\unfraDomicilioEstablecimientoAGENDA.pas' {fraDomicilioEstablecimientoAGENDA: TFrame},
  unfraEmpresaAGENDA in '..\comunes\frames\modulosAgenda\unfraEmpresaAGENDA.pas' {fraEmpresaAGENDA: TFrame},
  unfraEntidadAGENDA in '..\comunes\frames\modulosAgenda\unfraEntidadAGENDA.pas' {fraEntidadAGENDA: TFrame},
  unfraEntidadVendedorAGENDA in '..\comunes\frames\modulosAgenda\unfraEntidadVendedorAGENDA.pas' {fraEntidadVendedorAGENDA: TFrame},
  unfraVendedorAGENDA in '..\comunes\frames\modulosAgenda\unfraVendedorAGENDA.pas' {fraVendedorAGENDA: TFrame},
  unfraTrabajadorSiniestroAGENDA in '..\comunes\frames\modulosAgenda\unfraTrabajadorSiniestroAGENDA.pas' {fraTrabajadorSiniestroAGENDA: TFrame},
  unfraTrabajadorAGENDA in '..\comunes\frames\modulosAgenda\unfraTrabajadorAGENDA.pas' {fraTrabajadorAGENDA: TFrame},
  unfraPrestadorAGENDA in '..\comunes\frames\modulosAgenda\unfraPrestadorAGENDA.pas' {fraPrestadorAGENDA: TFrame},
  unfraNumAutoAGENDA in '..\comunes\frames\modulosAgenda\unfraNumAutoAGENDA.pas' {fraNumAutoAGENDA: TFrame},
  unfraEstablecimientoAGENDA in '..\comunes\frames\modulosAgenda\unfraEstablecimientoAGENDA.pas' {fraEstablecimientoAGENDA: TFrame},
  unFraTitulo in '..\comunes\frames\nuevos\unFraTitulo.pas' {fraTitulo: TFrame},
  unAgendaCargaConsulta in '..\comunes\forms\unAgendaCargaConsulta.pas' {frmAgendaCargaConsulta},
  unFraUsuarioConSectorIntranet in '..\comunes\frames\new\unFraUsuarioConSectorIntranet.pas' {fraUsuarioConSectorIntranet: TFrame},
  unFraUsuarioConJerarquias in '..\comunes\frames\new\unFraUsuarioConJerarquias.pas' {fraUsuarioConJerarquias: TFrame},
  unFraValidacionDatosEmpresa in '..\comunes\frames\new\unFraValidacionDatosEmpresa.pas' {fraValidacionDatosEmpresa: TFrame},
  unArbolSectores in '..\usuarios\unArbolSectores.pas' {frmArbolSectores},
  unAyuda in '..\comunes\unAyuda.pas' {frmAyuda},
  unSeleccionTareas in '..\comunes\forms\unSeleccionTareas.pas' {frmSeleccionTareas},
  unABMAgendaBase in '..\comunes\forms\unABMAgendaBase.pas' {frmABMAgendaBase},
  unABMAgendaBaseEvento in '..\comunes\forms\unABMAgendaBaseEvento.pas' {frmABMAgendaBaseEvento},
  unABMAgendaBaseTarea in '..\comunes\forms\unABMAgendaBaseTarea.pas' {frmABMAgendaBaseTarea},
  unSeleccionResponsableHYS in '..\hys\unSeleccionResponsableHYS.pas' {frmSeleccionResponsableHYS: TFSForm},
  unInterfaces in '..\..\comunes\interfaces\unInterfaces.pas',
  unFraDomicilioEmpresa in '..\comunes\frames\new\unFraDomicilioEmpresa.pas' {fraDomicilioEmpresa: TFrame},
  unVisor in '..\comunes\forms\unVisor.pas' {frmVisor},
  unArchivoVisor in '..\comunes\unArchivoVisor.pas',
  unVisorExcel in '..\comunes\forms\unVisorExcel.pas' {frmVisorExcel},
  unFraCanal in '..\comunes\frames\new\unFraCanal.pas' {fraCanal: TFrame},
  unRptAportesContrib in 'reports\unRptAportesContrib.pas' {RptAportesContrib: TQuickRep},
  unfraProspectosAGENDA in '..\comunes\frames\modulosagenda\unfraProspectosAGENDA.pas' {fraProspectosAGENDA: TFrame},
  unQrEtiquetasDocCarpetas in '..\archivo_new\unQrEtiquetasDocCarpetas.pas' {qrEtiquetasDocCarpetas: TQuickRep},
  unfraSectores in '..\comunes\frames\unfraSectores.pas' {fraSectores: TFrame},
  unRptPlantillaRGRL in '..\comunes\reports\unRptPlantillaRGRL.pas' {qrPlantillaRGRL: TQuickRep},
  unfraVistaEventos in '..\comunes\frames\modulosagenda\unfraVistaEventos.pas' {fraVistaEventos: TFrame},
  unAgendaVistaEmpresa in '..\comunes\forms\unAgendaVistaEmpresa.pas' {frmAgendaVistaEmpresa},
  unArchivo in '..\archivo_new\unArchivo.pas',
  unFrmConsultaCarpetas in '..\archivo_new\unFrmConsultaCarpetas.pas' {FrmConsultaCarpetas: TFSForm},
  unFrmSolicitudCarpeta in '..\archivo_new\unFrmSolicitudCarpeta.pas' {FrmSolicitudCarpeta: TFSForm},
  unQrEtiquetasCarpetas in '..\archivo_new\unQrEtiquetasCarpetas.pas' {qrEtiquetasCarpetas: TQuickRep},
  unFraDetalleArchivo in '..\archivo_new\frames\unFraDetalleArchivo.pas' {fraDetalleArchivo: TFrame},
  unFrmDetalleArchivo in '..\archivo_new\unFrmDetalleArchivo.pas' {FrmDetalleArchivo},
  unMovimientoCarpetas in '..\archivo_new\unMovimientoCarpetas.pas' {frmMovimientoCarpetas},
  unFrmCargaDocumentacion in '..\archivo_new\unFrmCargaDocumentacion.pas' {frmCargaDocumentacion},
  unQrDetalleLoteEstudio in '..\archivo_new\unQrDetalleLoteEstudio.pas' {QrDetalleLoteEstudio},
  unReemplazoCarpetas in '..\archivo_new\unReemplazoCarpetas.pas' {frmReemplazoCarpetas},
  unfrmUbicacionActual in '..\archivo_new\unfrmUbicacionActual.pas' {FrmUbicacionActual},
  unFraFiltroArchivo in '..\archivo_new\frames\unFraFiltroArchivo.pas' {fraFiltroArchivo: TFrame},
  unfraArchJuicio in '..\archivo_new\frames\unfraArchJuicio.pas' {fraArchJuicio: TFrame},
  unfraProveedor in '..\comunes\frames\new\unfraProveedor.pas' {fraProveedor: TFrame},
  unCapturarCodigoBarras in '..\comunes\unCapturarCodigoBarras.pas' {frmCapturarCodigoBarras},
  unCargaDocumentosDigitaliz in '..\comunes\forms\unCargaDocumentosDigitaliz.pas' {frmCargaDocumentosDigitaliz},
  unComisiones in '..\afiliaciones\comisiones\unComisiones.pas',
  unConstantArchivo in '..\archivo_new\unConstantArchivo.pas',
  unFraGrupoTrabajo in '..\comunes\frames\unFraGrupoTrabajo.pas' {fraGrupoTrabajo: TFrame},
  unActInfoDictamen in 'unActInfoDictamen.pas' {frmActInfoDictamen: TFSForm},
  unSinGranInvalidez in 'abm\unSinGranInvalidez.pas' {frmSinGranInvalidez: TFSForm},
  unRTTI in '..\..\comunes\unRTTI.pas',
  unTesoreria in '..\afiliaciones\tesoreria\unTesoreria.pas',
  unSIC in '..\..\comunes\unSIC.pas',
  unManBenefChequePorCuit in 'abm\unManBenefChequePorCuit.pas' {frmManBenefChequePorCuit: TFSForm},
  unManMotivoCancLiquidaciones in 'abm\unManMotivoCancLiquidaciones.pas' {frmManMotivoCancLiquidaciones: TFSForm},
  unMotivoCancelacionLiq in 'unMotivoCancelacionLiq.pas' {frmMotivoCancelacionLiq},
  unManMotivosDeDiferencia in 'abm\unManMotivosDeDiferencia.pas' {frmManMotivosDeDiferencia: TFSForm},
  unManMontoMaxAprobPorUsuario in 'abm\unManMontoMaxAprobPorUsuario.pas' {frmManMontoMaxAprobPorUsuario: TFSForm},
  unManImportesValoresAmpo in 'abm\unManImportesValoresAmpo.pas' {frmManImportesValoresAmpo: TFSForm},
  unFraEmpresaSolicitud in '..\comunes\frames\new\unFraEmpresaSolicitud.pas' {fraEmpresaSolicitud: TFrame},
  unfraEmpresaSolicitudAGENDA in '..\comunes\frames\modulosagenda\unfraEmpresaSolicitudAGENDA.pas' {fraEmpresaSolicitudAGENDA: TFrame},
  unQrDetalleRemitoDevolucion in '..\archivo_new\unQrDetalleRemitoDevolucion.pas' {QrDetalleRemitoDevolucion},
  unManCVS_VENTANILLA_SUBTEMAS in '..\comunes\forms\unManCVS_VENTANILLA_SUBTEMAS.pas' {frmManCVS_VENTANILLA_SUBTEMAS: TFSForm},
  Periodos in '..\..\comunes\Periodos.pas',
  unfraDatoFechaAGENDA in '..\comunes\frames\modulosagenda\unfraDatoFechaAGENDA.pas' {fraDatoFecha: TFrame},
  unFrmArmadoLote in '..\archivo_new\unFrmArmadoLote.pas' {FrmArmadoLote: TFSForm},
  unQrDetalleLote in '..\archivo_new\unQrDetalleLote.pas' {QrDetalleLote},
  unRptResumenLotes in '..\archivo_new\unRptResumenLotes.pas' {qrResumenLotes: TQuickRep},
  unListPagosJudiciales in 'listados\unListPagosJudiciales.pas' {frmListPagosJudiciales: TFSForm},
  unVerImagenes in '..\archivo_new\unVerImagenes.pas' {frmVerImagenes},
  unListSiniConLiqMensuales in 'listados\unListSiniConLiqMensuales.pas' {frmListSiniConLiqMensuales: TFSForm},
  unMensajeAlertaAGA in '..\archivo_new\unMensajeAlertaAGA.pas',
  unManActualizacionValores in 'abm\unManActualizacionValores.pas' {frmManActualizacionValores: TFSForm},
  unFraWebBrowser in '..\comunes\frames\new\unFraWebBrowser.pas' {fraWebBrowser: TFrame},
  unFraGIS_APIv3 in '..\comunes\frames\new\unFraGIS_APIv3.pas' {fraGIS_APIv3: TFrame},
  unExportPDF in '..\..\comunes\unExportPDF.pas',
  unPuestaDisposicion in 'unPuestaDisposicion.pas' {frmPuestaDisposicion},
  unEsperaSimple in '..\comunes\forms\unEsperaSimple.pas' {frmEsperaSimple},
  unDireccionCDO in 'unDireccionCDO.pas' {frmDireccionCDO},
  UnRptCartaDocPuestaDisp in 'reports\UnRptCartaDocPuestaDisp.pas' {RptCartaDocPuestaDisp: TQuickRep},
  unFraSDA_DETALLEARCHIVO in '..\comunes\frames\unFraSDA_DETALLEARCHIVO.pas' {fraSDA_DETALLEARCHIVO: TFrame},
  unRptDomiciliosIncompletos in '..\redpres\reports\unRptDomiciliosIncompletos.pas' {qrDireccionesFaltantes: TQuickRep},
  unfraDireccion in '..\comunes\frames\unfraDireccion.pas' {fraDireccion: TFrame},
  unBaseGeneracionCartas in '..\comunes\forms\unBaseGeneracionCartas.pas' {frmBaseGeneracionCartas},
  unGeneracionCartasAdmin in '..\redpres\unGeneracionCartasAdmin.pas' {frmGeneracionCartasAdmin},
  unImportCryptoSrt in '..\..\comunes\unImportCryptoSrt.pas',
  unSeleccionarCarpetaSRT in '..\afiliaciones\unSeleccionarCarpetaSRT.pas' {frmSeleccionarCarpetaSRT},
  unRptCartaDocSinDDJJ in '..\redpres\reports\unRptCartaDocSinDDJJ.pas' {rptCartaDocSinDDJJ: TQuickRep},
  unManMotBajaPuestaDisp in 'abm\unManMotBajaPuestaDisp.pas' {frmMotBajaPuestaDisp: TFSForm},
  unBaseAdministracionCartas in '..\comunes\forms\unBaseAdministracionCartas.pas' {frmBaseAdministracionCartas: TFSForm},
  unDinerariasAdministracionCartas in 'unDinerariasAdministracionCartas.pas' {frmDinerariasAdministracionCartas: TFSForm},
  unEnvioSMS in '..\comunes\forms\unEnvioSMS.pas' {frmEnvioSMS},
  unRptRemitoCartas in '..\redpres\reports\unRptRemitoCartas.pas' {qrRemitoCartas: TQuickRep},
  unTableroControl in 'unTableroControl.pas' {frmTableroControl: TFSForm},
  unJustificacionILT in '..\siniestros\unJustificacionILT.pas' {frmJustificacionILT},
  unSeguimientoCasosMortales in 'abm\unSeguimientoCasosMortales.pas' {frmSeguimCasosMortales: TFSForm},
  unRptCasosPorLiquidador in 'reports\unRptCasosPorLiquidador.pas' {frmRptCasosPorLiquidador},
  unManLiquidadores in 'abm\unManLiquidadores.pas' {frmManLiquidadores: TFSForm},
  unMotivosBajaCasos in 'abm\unMotivosBajaCasos.pas' {frmMotivosBajaCasos: TFSForm},
  unRptReciboILP in 'reports\unRptReciboILP.pas' {qrReciboILP: TQuickRep},
  unSeguimientoCasosPagoDir in 'abm\unSeguimientoCasosPagoDir.pas' {frmSeguimCasosPagoDir: TFSForm},
  unConsultaTIFF in 'unConsultaTIFF.pas' {frmConsultaTIFF},
  unFraTipoRegimen in '..\comunes\frames\new\unFraTipoRegimen.pas' {fraTipoRegimen: TFrame},
  unSiniestrosNoAutorizados in 'unSiniestrosNoAutorizados.pas' {frmSiniestrosNoAutorizados: TFSForm},
  unSeguimientoCasosILP in 'abm\unSeguimientoCasosILP.pas' {frmSeguimCasosILP: TFSForm},
  unLiquidacionesModificadas in 'unLiquidacionesModificadas.pas' {frmLiquidacionesModificadas: TFSForm},
  unSegRemisionFondos in 'listados\unSegRemisionFondos.pas' {frmSegRemisionFondos: TFSForm},
  unAccionesRemisionFondos in 'abm\unAccionesRemisionFondos.pas' {frmAccionesRemisionFondos: TFSForm};

{$R *.res}
{$R *.dres}

begin
  OnlyOneInstance;
  Application.Initialize;
  Application.Title := 'Prestaciones Dinerarias';

  with TfrmWelcomeSplash.Create(Application) do
  try
    ShowOnTop;
    Application.CreateForm(TdmFinancials, dmFinancials);
  Application.CreateForm(TdmPrincipal, dmPrincipal);
  if dmPrincipal.sdbPrincipal.Connected then
    begin
      OnlyOneSession;
      Application.CreateForm(TfrmPrincipal, frmPrincipal);
    end;
  finally
    Free;
  end;

  MostrarNovedades;
  Application.Run;
end.
