program RedPres;

{$R *.dres}

uses
  Forms,
  Controls,
  Windows,
  OneInstance,
  unPrincipal in 'unPrincipal.pas' {frmPrincipal},
  unCustomDataModule in '..\comunes\unCustomDataModule.pas' {dmCustomDataModule: TDataModule},
  unDmPrincipal in '..\comunes\oracle\unDmPrincipal.pas' {dmPrincipal: TDataModule},
  unDmFinancials in '..\Comunes\ORACLE\unDmFinancials.pas' {dmFinancials: TDataModule},
  unfraDelegacion in '..\Comunes\FRAMES\unfraDelegacion.pas' {fraDelegacion: TFrame},
  unBusqSini in 'unBusqSini.pas' {dlgBusqSini},
  unAutCarga in 'unAutCarga.pas' {frmAutCarga},
  unFraTrabajadorSIN in '..\Comunes\FRAMES\unFraTrabajadorSIN.pas' {fraTrabajadorSIN: TFrame},
  unAutSelPorSiniestro in 'unAutSelPorSiniestro.pas' {frmAutSelPorSiniestro},
  unAutAprob in 'unAutAprob.pas' {frmAutAprob},
  unfraPrestaciones in '..\Comunes\FRAMES\unfraPrestaciones.pas' {fraPrestacion: TFrame},
  unRecepcion in 'unRecepcion.pas' {frmRecepcion},
  unLiqCarga in 'unLiqCarga.pas' {frmLiquiCarga},
  unfraVolante in 'unfraVolante.pas' {fraVolantes: TFrame},
  unRTF in 'Mortales\unRTF.pas' {frmRTF},
  unPedidoInfo in 'unPedidoInfo.pas' {frmPedidoInfo},
  unRptVolante in 'REPORTS\unRptVolante.pas' {rptVolante: TQuickRep},
  unLiqAprob in 'unLiqAprob.pas' {frmLiquiAprob},
  unPedidosInfo in 'unPedidosInfo.pas' {frmPedidosInfo},
  unLiqNotaDebito in 'unLiqNotaDebito.pas' {frmLiqNotaDebito},
  unRptNotaDebito in 'unRptNotaDebito.pas' {rptNotaDebito: TQuickRep},
  unLiqAutPago in 'unLiqAutPago.pas' {frmLiquiAutPago},
  unLiqCargaGen in 'unLiqCargaGen.pas' {frmLiquiCargaGen},
  unfraNomenclador in '..\Comunes\FRAMES\unfraNomenclador.pas' {fraNomenclador: TFrame},
  unMantFirmantes in 'unMantFirmantes.pas' {frmMantFirmantes},
  unABMFirmantes in 'unABMFirmantes.pas' {frmABMFirmantes},
  unRepAutoriza in 'unRepAutoriza.pas' {qrpAutoriza},
  unMantDocumentos in 'unMantDocumentos.pas' {frmManDocumentos},
  unABMDocumentos in 'unABMDocumentos.pas' {frmABMDocumentos},
  unParteEvolutivo in 'unParteEvolutivo.pas' {frmParteEvolutivo},
  unRepEvol in 'unRepEvol.pas' {frmRepEvol},
  unImpParteEvolutivo in 'unImpParteEvolutivo.pas' {dlgImpParteEvolutivo},
  unRptPedInfo in 'REPORTS\unRptPedInfo.pas' {rptPedInfo: TQuickRep},
  unManPrestador in 'unManPrestador.pas' {frmManPrestador},
  unDetFact in 'unDetFact.pas' {frmDetFact},
  unLiqListApro in 'unLiqListApro.pas' {frmLiqListApro},
  unRptFKT in 'REPORTS\unRptFKT.pas' {rptFKT: TQuickRep},
  unListPasSinEvol in 'unListPasSinEvol.pas' {frmListPasSinEvol},
  unManRangos in 'unManRangos.pas' {frmManRangos},
  unLiquiImputPagos in 'unLiquiImputPagos.pas' {frmLiquiImputPagos},
  unResMontosSaldos in 'REPORTS\unResMontosSaldos.pas' {rptResMontosSaldos: TQuickRep},
  unListDiasCaidos in 'unListDiasCaidos.pas' {frmListDiasCaidos},
  unManPrestaciones in 'unManPrestaciones.pas' {frmManPrestaciones},
  unCambGrupoTrabajo in 'unCambGrupoTrabajo.pas' {frmCambGrupoTrabajo},
  unConsSin in 'unConsSin.pas' {frmConsSin},
  unFraCIE10 in '..\Comunes\FRAMES\unFraCIE10.pas' {fraCIE10: TFrame},
  unFraEmpresa in '..\Comunes\FRAMES\NEW\unFraEmpresa.pas' {fraEmpresa: TFrame},
  unListOperProg in 'unListOperProg.pas' {frmListOperProg},
  unListCostoPorCIE10 in 'unListCostoPorCIE10.pas' {frmListCostoPorCIE10},
  UnListPorEmpr in 'UnListPorEmpr.pas' {frmListPorEmpr},
  UnManTipoPrestador in 'UnManTipoPrestador.pas' {frmManTipoPrestador},
  unManTextosCartasDoc in 'unManTextosCartasDoc.pas' {frmManTextosCartasDoc},
  unManTextosCartasDocTrab in 'unManTextosCartasDocTrab.pas' {frmManTextosCartasDocTrab},
  unfraFormCartasDoc in 'SegExpe\unfraFormCartasDoc.pas' {fraFormCartasDoc: TFrame},
  unfraFirmante in '..\Comunes\FRAMES\unfraFirmante.pas' {fraFirmante: TFrame},
  unfraFormCartasDocTrab in 'SegExpe\unfraFormCartasDocTrab.pas' {fraFormCartasDocTrab: TFrame},
  UnRepManPrestador in 'UnRepManPrestador.pas' {rptManPrestador: TQuickRep},
  UnListConsPrest in 'UnListConsPrest.pas' {frmConsPrest},
  unfraDireccion in '..\Comunes\FRAMES\unfraDireccion.pas' {fraDireccion: TFrame},
  UnRptFormulioRPT in 'UnRptFormulioRPT.pas' {rptFormularioSRT},
  UnListSiniSinAltaMed in 'UnListSiniSinAltaMed.pas' {frmListSiniSinAltaMed},
  UnManProtesisOrtesis in 'UnManProtesisOrtesis.pas' {frmManProtesisOrtesis},
  UnManEspecialidades in 'UnManEspecialidades.pas' {frmManEspecialidades},
  unListInternadosb in 'unListInternadosb.pas' {frmListInternadosb},
  UnRptPedidoEntregaNuevo in 'UnRptPedidoEntregaNuevo.pas' {rptPedidoEntregaNuevo: TQuickRep},
  UnManSubPrestaciones in 'UnManSubPrestaciones.pas' {frmManSubPrestaciones},
  unManUnidadesMedicas in 'unManUnidadesMedicas.pas' {frmManUnidadesMedicas},
  unManNomenclador in 'unManNomenclador.pas' {frmManNomenclador},
  unManAuditores in 'unManAuditores.pas' {frmManAuditores},
  UnTraslados in 'UnTraslados.pas' {frmTraslados},
  UnManTiposTraslado in 'UnManTiposTraslado.pas' {frmManTiposTraslado},
  UnManSolicitantes in 'UnManSolicitantes.pas' {frmManSolicitantes},
  UnRepTraslados in 'UnRepTraslados.pas' {rptTraslados: TQuickRep},
  unReimprimirVolantes in 'unReimprimirVolantes.pas' {frmReimprimirVolante},
  UnDocumentos in 'UnDocumentos.pas' {frmDocumentos},
  unfraSubPrestacion in '..\Comunes\FRAMES\unfraSubPrestacion.pas' {fraSubPrestacion: TFrame},
  unRecVolantes in 'unRecVolantes.pas' {frmRecVolantes},
  UnFirmantes in 'UnFirmantes.pas' {frmFirmantes},
  UnManEmpresasVIP in 'UnManEmpresasVIP.pas' {frmManEmpresasVIP},
  unfraUsuarios in '..\Comunes\FRAMES\unfraUsuarios.pas' {fraUsuario: TFrame},
  UnManCIE10 in 'UnManCIE10.pas' {frmManCIE10},
  unFraCtbTablas in '..\Comunes\FRAMES\unFraCtbTablas.pas' {fraCtbTablas: TFrame},
  unCustomConsulta in '..\Comunes\REPOSIT\unCustomConsulta.pas' {frmCustomConsulta},
  UnDestPapl in 'UnDestPapl.pas' {FrmDestinoPapel},
  UnSinSEvo in 'UnSinSEvo.pas' {frmSinSEvo},
  unArtFrame in '..\Comunes\REPOSIT\unArtFrame.pas' {ArtFrame: TFrame},
  unFraCodigoDescripcion in '..\Comunes\FRAMES\unFraCodigoDescripcion.pas' {fraCodigoDescripcion: TFrame},
  UnConsTlgCartas in 'UnConsTlgCartas.pas' {frmConsTlgCartas},
  unManGrupoTrabajo in 'ABM\unManGrupoTrabajo.pas' {frmManGrupoTrabajo},
  UnListSinxEmpv2 in 'UnListSinxEmpv2.pas' {frmListxEmpr2},
  unListRecalGen in 'unListRecalGen.pas' {frmListRecalGen},
  unListRecalPev in 'unListRecalPev.pas' {frmListRecalPev},
  unPorTratamiento in 'unPorTratamiento.pas' {frmPorTratamiento},
  unTrabExt in 'unTrabExt.pas' {frmTrabExt},
  unCostosxSin in 'unCostosxSin.pas' {frmCostosxSin},
  unFraTrabajador in '..\Comunes\FRAMES\NEW\unFraTrabajador.pas' {fraTrabajador: TFrame},
  unCustomGridABM in '..\Comunes\REPOSIT\unCustomGridABM.pas' {frmCustomGridABM},
  unRatificaAlta in 'unRatificaAlta.pas' {frmRatificaAlta},
  unCustomPanelABM in '..\Comunes\REPOSIT\unCustomPanelABM.pas' {frmCustomPanelABM},
  unCostosxSiniestro in 'unCostosxSiniestro.pas' {frmCostosxSiniestro},
  unConsultorio in 'unConsultorio.pas' {frmConsultorio},
  unABMUsugrp in 'unABMUsugrp.pas' {frmUsugrp},
  unContTratSA in 'unContTratSA.pas' {frmContTratSA},
  unCartaRechPr in 'unCartaRechPr.pas' {frmCartaRechPr},
  unRptRechPr in 'unRptRechPr.pas' {rptCartaRech: TQuickRep},
  unPresupuestos in 'unPresupuestos.pas' {frmPresupuestos},
  unRptSolicitudPresupuesto in 'REPORTS\unRptSolicitudPresupuesto.pas' {qrpSolicitudPresupuesto: TQuickRep},
  unSeleccionarPresupuesto in 'unSeleccionarPresupuesto.pas' {frmSeleccionarPresupuesto},
  unConfidencial in 'unConfidencial.pas',
  unFraStaticCodigoDescripcion in '..\Comunes\FRAMES\unFraStaticCodigoDescripcion.pas' {fraStaticCodigoDescripcion: TFrame},
  unFraStaticCTB_TABLAS in '..\Comunes\FRAMES\unFraStaticCTB_TABLAS.pas' {fraStaticCTB_TABLAS: TFrame},
  unManCCP_CUENTAPAGO in '..\Comunes\Forms\unManCCP_CUENTAPAGO.pas' {frmManCCP_CUENTAPAGO},
  unRequerimientosSRT in 'unRequerimientosSRT.pas' {frmRequerimientosSRT},
  unArtDBAwareFrame in '..\Comunes\REPOSIT\unArtDBAwareFrame.pas' {ArtDBAwareFrame: TFrame},
  unArtDbFrame in '..\Comunes\REPOSIT\unArtDbFrame.pas' {ArtDbFrame: TFrame},
  unAltaModifCCP_CUENTAPAGO in '..\Comunes\Forms\unAltaModifCCP_CUENTAPAGO.pas' {frmAltaModifCCP_CUENTAPAGO},
  unfraVendedores in '..\Comunes\FRAMES\unfraVendedores.pas' {fraVendedores: TFrame},
  unfraVendedoresCUIT in '..\Comunes\FRAMES\NEW\unfraVendedoresCUIT.pas' {fraVendedoresCUIT: TFrame},
  unfraConPago in '..\Comunes\FRAMES\unfraConPago.pas' {fraConPago: TFrame},
  unCartaDocumento in '..\Comunes\REPORTS\unCartaDocumento.pas',
  unWebMigracion in 'unWebMigracion.pas' {frmWebMigracion},
  unRptDenuncia in 'REPORTS\unRptDenuncia.pas' {rptDenuncia: TQuickRep},
  unRptParteMedicoIngreso in 'REPORTS\unRptParteMedicoIngreso.pas' {rptParteMedicoIngreso: TQuickRep},
  unRptParteMedicoEgreso in 'REPORTS\unRptParteMedicoEgreso.pas' {rptParteMedicoEgreso: TQuickRep},
  unSuspensionPlazos in 'unSuspensionPlazos.pas' {frmSuspensionPlazos},
  unfraCPR_PRESTADOR in '..\Comunes\FRAMES\NEW\unfraCPR_PRESTADOR.pas' {fraCPR_PRESTADOR: TFrame},
  unRecepPartes in 'unRecepPartes.pas' {frmPartesReceptadas},
  unSesion in '..\..\Comunes\unSesion.pas',
  unReingresoParte in 'unReingresoParte.pas' {frmReingresoParte},
  numeros in '..\..\Comunes\numeros.pas',
  unVisualizador in '..\Comunes\unVisualizador.pas' {frmVisualizador},
  UnRptMoldeCarta in '..\Comunes\REPORTS\UnRptMoldeCarta.pas' {qrMoldeCarta: TQuickRep},
  unFraToolbarRTF in '..\Comunes\FRAMES\unFraToolbarRTF.pas' {fraToolbarRTF: TFrame},
  unManCtbTablas in '..\Comunes\Forms\unManCtbTablas.pas' {frmManCtbTablas},
  UnManCompaniasAseguradoras in 'UnManCompaniasAseguradoras.pas' {frmManCompaniasAseguradoras},
  unCustomForm in '..\Comunes\unCustomForm.pas' {frmCustomForm},
  unManPoliza in 'unManPoliza.pas' {frmManPolizas},
  unPlanDePagosDePolizas in 'unPlanDePagosDePolizas.pas' {frmPlanDePagosDePolizas},
  DateTimeFuncs in '..\..\Comunes\DateTimeFuncs.pas',
  unRptAvisoFaltaSeguro in 'REPORTS\unRptAvisoFaltaSeguro.pas' {qrAvisoFaltaSeguro: TQuickRep},
  unConfiguracionScoring in 'unConfiguracionScoring.pas' {frmConfiguracionScoring},
  unReport in '..\Comunes\unReport.pas' {rptReport: TQuickRep},
  unRptNotaAprobacion in 'unRptNotaAprobacion.pas' {rptNotaAprobacion},
  unManDerivacionVolantes in 'ABM\unManDerivacionVolantes.pas' {frmManDerivacionVolantes},
  unABMUsuDerivacionVolantes in 'ABM\unABMUsuDerivacionVolantes.pas' {frmABMUsuDerivacionVolantes},
  unEnvioMail in '..\..\Comunes\unEnvioMail.pas',
  unRptParteEvolutivo in 'REPORTS\unRptParteEvolutivo.pas' {rptParteEvolutivo: TQuickRep},
  unMoldeEnvioMail in '..\Comunes\Envio de Mails\unMoldeEnvioMail.pas' {frmMoldeEnvioMail},
  Internet in '..\..\Comunes\Internet.pas',
  unElementosEnviados in '..\Comunes\Forms\unElementosEnviados.pas' {frmElementosEnviados},
  WinShell in '..\..\Comunes\WinShell.pas',
  unAgendaProtocolo in 'unAgendaProtocolo.pas' {frmAgenda},
  unFraCodDesc in '..\Comunes\FRAMES\NUEVOS\unFraCodDesc.pas' {fraCodDesc: TFrame},
  unfraAlarmasPorProtocolo in 'FRAMES\unfraAlarmasPorProtocolo.pas' {fraAlarmasPorProtocolo: TFrame},
  unLibretaDeDirecciones in '..\Comunes\Forms\unLibretaDeDirecciones.pas' {frmLibretaDeDirecciones},
  unListCargaDiaria in 'unListCargaDiaria.pas' {frmListCargaDiaria},
  unRedPres in '..\..\comunes\unRedPres.pas',
  unCITRIX in '..\..\Comunes\unCITRIX.pas',
  UnManMotivosNoCarga in 'UnManMotivosNoCarga.pas' {frmManMotivosNoCarga},
  unRecepPartesGrales in 'unRecepPartesGrales.pas' {frmRecepcionPartesGrales},
  Cuit in '..\..\comunes\Cuit.pas',
  unManCtbMotivosRechazo in 'abm\unManCtbMotivosRechazo.pas' {frmManCtbMotivosRechazo},
  unManCtbMotivosAnulacion in 'abm\unManCtbMotivosAnulacion.pas' {frmManCtbMotivosAnulacion},
  unSolicitudAuditoria in 'unSolicitudAuditoria.pas' {frmSolicitudAuditoria},
  unEnviarSolicitudAuditoria in 'unEnviarSolicitudAuditoria.pas' {frmEnviarSolicitudAuditoria},
  unRptSolicitudAuditoriaGrave in 'unRptSolicitudAuditoriaGrave.pas' {rptSolicitudAuditoriaGrave: TQuickRep},
  General in '..\..\comunes\General.pas',
  CustomDlgs in '..\..\comunes\CustomDlgs.pas',
  ArchFuncs in '..\..\comunes\ArchFuncs.pas',
  unSegMedRecalif in 'unSegMedRecalif.pas' {FrmSegMedRecalif},
  unManMotivosDebito in 'unManMotivosDebito.pas' {frmManMotivosDebito},
  unRecalificacionSRT in 'unRecalificacionSRT.pas' {FrmRecalificacionSRT},
  unSeleccionDestinatarios in '..\comunes\unSeleccionDestinatarios.pas' {frmSeleccionDestinatarios},
  unManPracticasModulos in 'unManPracticasModulos.pas' {frmManPracticasModulos},
  strfuncs in '..\..\comunes\strfuncs.pas',
  unCapturarCodigoBarras in '..\comunes\unCapturarCodigoBarras.pas' {frmCapturarCodigoBarras},
  unDebug in '..\comunes\unDebug.pas' {frmDebug},
  unManTurnosMedicos in 'unManTurnosMedicos.pas' {frmManTurnosMedicos},
  unfraContacto in '..\comunes\frames\unfraContacto.pas' {fraContacto: TArtFrame},
  unFraTelefono in '..\comunes\frames\new\unFraTelefono.pas' {fraTelefono: TFrame},
  unABMTelefonos in '..\comunes\forms\unABMTelefonos.pas' {frmTelefonos},
  unTelefonosCargaRapida in '..\comunes\forms\unTelefonosCargaRapida.pas' {frmTelefonosCargaRapida},
  unCartaNotificacionAltas in 'unCartaNotificacionAltas.pas' {frmCartaNotificacionAltas},
  unManCTC_TEXTOCARTA in '..\comunes\forms\unManCTC_TEXTOCARTA.pas' {frmManCTC_TEXTOCARTA},
  uncomunes in '..\..\comunes\uncomunes.pas',
  unManCAT_AREATEXTO in '..\comunes\forms\unManCAT_AREATEXTO.pas' {frmManCAT_AREATEXTO},
  unManCTB_CODRE in '..\comunes\forms\unManCTB_CODRE.pas' {frmManCTB_CODRE},
  unRptInformeSRT in 'reports\unRptInformeSRT.pas' {RptInformeSRT},
  unListPresupuestos in 'unListPresupuestos.pas' {frmListPresupuestos},
  unListSiniestrosConInternacion in 'unListSiniestrosConInternacion.pas' {frmListSiniestrosConInternacion},
  unCambioCuitSin in 'unCambioCuitSin.pas' {frmCambioCuitSin},
  unTelefonogramas in 'unTelefonogramas.pas' {frmTelefonogramas},
  unFraUsuario in '..\comunes\frames\new\unFraUsuario.pas' {fraUsuarios: TFrame},
  unFraDomicilio in '..\comunes\frames\new\unFraDomicilio.pas' {fraDomicilio: TFrame},
  unFraDomicilioTrab in '..\comunes\frames\new\unFraDomicilioTrab.pas' {fraDomicilioTrab: TFrame},
  unBusquedaDomicilio in '..\comunes\forms\unBusquedaDomicilio.pas' {frmBusquedaDomicilio},
  unBaseAdministracionCartas in '..\comunes\forms\unBaseAdministracionCartas.pas' {frmBaseAdministracionCartas},
  unQRF817 in '..\cobranzas\reports\unQRF817.pas' {QRF817: TQuickRep},
  unQRCartaDocIntimacion in '..\cobranzas\reports\unQRCartaDocIntimacion.pas' {QRCartaDocIntimacion: TQuickRep},
  unQrEstadoCuentaDetalle in '..\cobranzas\reports\unQrEstadoCuentaDetalle.pas' {frmEstadoCuentaDetalle},
  unQrEstadoCuentaResumen in '..\cobranzas\reports\unQrEstadoCuentaResumen.pas' {frmEstadoCuentaResumen},
  unQRF801C in '..\cobranzas\reports\unQRF801C.pas' {QRF801C: TQuickRep},
  unRptCartaDocCompensacion in '..\cobranzas\compensacion\reports\unRptCartaDocCompensacion.pas' {rptCartaDocCompensacion: TQuickRep},
  unImpresionEstadoDeCuenta in '..\cobranzas\unImpresionEstadoDeCuenta.pas' {frmImpresionEstadodeCuenta},
  unOpcionesDeImpresion in '..\cobranzas\unOpcionesDeImpresion.pas' {frmOpcionesDeImpresion},
  unRedPresAdministracionCartas in 'unRedPresAdministracionCartas.pas' {frmRedPresAdministracionCartas},
  unBaseGeneracionCartas in '..\comunes\forms\unBaseGeneracionCartas.pas' {frmBaseGeneracionCartas},
  unGeneracionCartasAdmin in 'unGeneracionCartasAdmin.pas' {frmGeneracionCartasAdmin},
  unManCFI_FIRMA in '..\comunes\forms\unManCFI_FIRMA.pas' {frmManCFI_FIRMA},
  unRptCartaDocumento in '..\comunes\reports\unRptCartaDocumento.pas',
  unRptCartaDocHeader in '..\comunes\reports\unRptCartaDocHeader.pas' {rptCartaDocHeader: TQuickRep},
  libgfl in '..\..\comunes\libgfl.pas',
  unImageFunctions in '..\..\comunes\unImageFunctions.pas',
  unRptDomiciliosIncompletos in 'reports\unRptDomiciliosIncompletos.pas' {qrDireccionesFaltantes: TQuickRep},
  unFraDigitalizacion in '..\comunes\frames\NEW\unFraDigitalizacion.pas' {fraDigitalizacion: TFrame},
  unFraRTD_TIPODOCUMENTO in '..\comunes\frames\new\unFraRTD_TIPODOCUMENTO.pas' {fraRTD_TIPODOCUMENTO: TFrame},
  unFraVistaTIFF in '..\comunes\frames\new\unFraVistaTIFF.pas' {fraVistaTIFF: TFrame},
  ungrids in '..\..\Comunes\ungrids.pas',
  VCLExtra in '..\..\Comunes\VCLExtra.pas',
  unFaxFuncs in '..\..\Comunes\unFaxFuncs.pas',
  unFaxEnviados in '..\comunes\forms\unFaxEnviados.pas' {frmFaxEnviados},
  unManAsigEspeciales in 'unManAsigEspeciales.pas' {frmManAsigEspeciales},
  unManAsigHijos in 'unManAsigHijos.pas' {frmManAsigHijos},
  unPracticasPrestador in 'unPracticasPrestador.pas' {frmPracticasPrestador},
  unEstadoCuenta in '..\cobranzas\unEstadoCuenta.pas',
  unRptCartaDocSinDDJJ in 'reports\unRptCartaDocSinDDJJ.pas' {rptCartaDocSinDDJJ: TQuickRep},
  unSeleccionTurnosTraslados in 'unSeleccionTurnosTraslados.pas' {frmSeleccionTurnosTraslados},
  unListAlquilerOrtopedia in 'unListAlquilerOrtopedia.pas' {frmListAlquilerOrtopedia},
  unListRecuperoOrtopedia in 'unListRecuperoOrtopedia.pas' {frmListRecuperoOrtopedia},
  unListStockOrtopedia in 'unListStockOrtopedia.pas' {frmListStockOrtopedia},
  unListSeguimientoMedico in 'unListSeguimientoMedico.pas' {frmListSeguimientoMedico},
  unCustomPrincipal in '..\comunes\reposit\unCustomPrincipal.pas' {frmCustomPrincipal},
  unfraEstablecimiento in '..\comunes\frames\unfraEstablecimiento.pas' {fraEstablecimiento: TFrame},
  unConsFax in '..\comunes\forms\unConsFax.pas' {frmConsFax: TFSForm},
  unfraFFO_FAXFORMULARIO in '..\fax\faxclient_new\frames\unfraFFO_FAXFORMULARIO.pas' {fraFFO_FAXFORMULARIO: TFrame},
  unEstrategiaTIFF in '..\fax\faxclient_new\unEstrategiaTIFF.pas',
  unManRDO_DOCUMENTO in '..\archivo_new\abm\unManRDO_DOCUMENTO.pas' {frmManRDO_DOCUMENTO: TFSForm},
  unEspera in '..\comunes\forms\unEspera.pas' {frmEspera},
  unParams in '..\..\Comunes\unParams.pas',
  unReingresoParteMedicoEvol in 'unReingresoParteMedicoEvol.pas' {frmReingresoParteMedicoEvol},
  unReingresoParteMedico in 'unReingresoParteMedico.pas' {frmReingresoParteMedico},
  unImportarPrestadores in 'unImportarPrestadores.pas' {frmImportarPrestadores},
  unListInternados in 'unListInternados.pas' {frmListInternados},
  unListRecepcionPartes in 'unListRecepcionPartes.pas' {frmListRecepcionPartes: TFSForm},
  unDocumentacion in 'unDocumentacion.pas' {frmDocumentacion: TFSForm},
  unfraSectores in '..\comunes\frames\unfraSectores.pas' {fraSectores: TFrame},
  unRptRemito in 'unRptRemito.pas' {qrRemito: TQuickRep},
  unfraEntidadCUIT in '..\comunes\frames\new\unfraEntidadCUIT.pas' {fraEntidadCUIT: TFrame},
  unSiniestros in '..\Siniestros\unSiniestros.pas',
  unNovedades in '..\..\Comunes\unNovedades.pas',
  unEvaluacionMedica in 'unEvaluacionMedica.pas' {frmEvaluacionMedica: TFSForm},
  unRptEvolucion in '..\comunes\reports\unRptEvolucion.pas' {qrEvolucion: TQuickRep},
  unDatosSiniestro in '..\comunes\forms\unDatosSiniestro.pas' {frmDatosSiniestro},
  unSolicitarPresupuesto in 'unSolicitarPresupuesto.pas' {frmSolicitarPresupuesto: TFSForm},
  unFiltros in '..\..\Comunes\unFiltros.pas',
  unListHistoricoVolante in 'unListHistoricoVolante.pas' {frmListHistoricoVolante: TFSForm},
  unRptSolicitudPresupuestoAMP in 'reports\unRptSolicitudPresupuestoAMP.pas' {qrSolicitudPresupuestoAMP: TQuickRep},
  AnsiSql in '..\..\Comunes\AnsiSql.pas',
  SqlFuncs in '..\..\Comunes\SqlFuncs.pas',
  unImpoExpoUtils in '..\impoexpo\unImpoExpoUtils.pas',
  unfraEstudio in 'frames\unfraEstudio.pas' {fraEstudio: TFrame},
  unImpoExpoWizard in '..\impoexpo\unImpoExpoWizard.pas' {frmImpoExpoWizard},
  unManMotAnulCitaciones in 'unManMotAnulCitaciones.pas' {frmManMotAnulCitaciones},
  unMoldeAbmAnalisis in '..\adminanalisis\unMoldeAbmAnalisis.pas' {frmMoldeAbmAnalisis},
  unfraPrestadorAMP in '..\adminanalisis\frames\unfraPrestadorAMP.pas' {fraPrestadorAMP: TFrame},
  unFraTipoEstudio in '..\adminanalisis\frames\unFraTipoEstudio.pas' {fraTipoEstudio: TFrame},
  unfraOperativo in '..\amp\frames\unfraOperativo.pas' {fraOperativo: TFrame},
  unfraEstablecimiento_OLD in '..\comunes\frames\unfraEstablecimiento_OLD.pas' {fraEstablecimiento_OLD: TFrame},
  unFormEstudios in '..\adminanalisis\unFormEstudios.pas',
  unHistoriaClinica in '..\adminanalisis\unHistoriaClinica.pas' {frmHistoriaClinica},
  unFraReconfirmacion in '..\adminanalisis\frames\unFraReconfirmacion.pas' {fraReconfirmacion: TFrame},
  unfraMedico in '..\amp\frames\unfraMedico.pas' {fraMedico: TFrame},
  unEstudiosDef in '..\adminanalisis\unEstudiosDef.pas' {frmEstudioDef},
  unEstRespiratorio in '..\adminanalisis\unEstRespiratorio.pas' {frmEstRespiratorio},
  unEstAudiometria in '..\adminanalisis\unEstAudiometria.pas' {frmEstAudiometria},
  unMotivoEstudio in '..\adminanalisis\unMotivoEstudio.pas' {frmMotivoEstudio: TFSForm},
  unFraRiesgo in '..\comunes\frames\unFraRiesgo.pas' {fraRiesgo: TFrame},
  unSegReconfirmaciones in '..\adminanalisis\unSegReconfirmaciones.pas' {frmSegReconfirmaciones: TFSForm},
  unMoverEstudio in '..\adminanalisis\unMoverEstudio.pas' {frmMoverEstudio},
  unFraTrabajadorAMP in '..\comunes\frames\unFraTrabajadorAMP.pas' {fraTrabajadorAMP: TFrame},
  unSegRecEstudios in '..\adminanalisis\unSegRecEstudios.pas' {frmSegRecEstudios: TFSForm},
  unABMAnalisis in 'abm\unABMAnalisis.pas' {frmAbmAnalisis},
  TBL_PerdAudi2 in '..\adminanalisis\TBL_PerdAudi2.pas',
  unRptSolicitudAsistencia in 'reports\unRptSolicitudAsistencia.pas' {rptSolicitudAsistencia: TQuickRep},
  unCalendarioPrestacional in 'unCalendarioPrestacional.pas' {frmCalendarioPrestacional},
  unCeseILT in 'unCeseILT.pas' {frmCeseILT: TFSForm},
  unCobranzas in '..\..\Comunes\unCobranzas.pas',
  unQRCartaDocIntimacionNuevaGrilla in '..\cobranzas\reports\unQRCartaDocIntimacionNuevaGrilla.pas' {QRCartaDocIntimacionNuevaGrilla: TQuickRep},
  unFraGrupoTrabajo in '..\comunes\frames\unFraGrupoTrabajo.pas' {fraGrupoTrabajo: TFrame},
  unRptParteEgreso in '..\siniestros\reports\unRptParteEgreso.pas' {rptParteEgreso: TQuickRep},
  unConstantArchivo in '..\archivo_new\unConstantArchivo.pas',
  unRemitosCartas in 'unRemitosCartas.pas' {frmRemitosCartas: TFSForm},
  unRptRemitoCartas in 'reports\unRptRemitoCartas.pas' {qrRemitoCartas: TQuickRep},
  unFormularioValidacionYRectificacionDatosEstablecimientos in '..\comunes\forms\unFormularioValidacionYRectificacionDatosEstablecimientos.pas' {frmFormularioValidacionYRectificacionDatosEstablecimientos},
  unRptFormularioValidacionYRectificacionDatosEstablecimientos in '..\comunes\reports\unRptFormularioValidacionYRectificacionDatosEstablecimientos.pas' {qrFormularioValidacionYRectificacionDatosEstablecimientos: TQuickRep},
  unSeguimientoCronicos in 'unSeguimientoCronicos.pas' {frmSeguimientoCronicos: TFSForm},
  unManCuentaUsuario in 'abm\unManCuentaUsuario.pas' {frmManCuentaUsuario},
  unRptInformeParteEvol in 'reports\unRptInformeParteEvol.pas' {rptInformeParteEvol: TQuickRep},
  unAutTurnos in 'unAutTurnos.pas' {frmAutTurnos},
  unManSDT_DETALLETRANSPORTE in 'abm\unManSDT_DETALLETRANSPORTE.pas' {frmManSDT_DETALLETRANSPORTE: TFSForm},
  unManSHT_HORARIOSTRASLADOS in 'abm\unManSHT_HORARIOSTRASLADOS.pas' {frmManSHT_HORARIOSTRASLADOS: TFSForm},
  unCalendarioMediosDeTransporte in 'unCalendarioMediosDeTransporte.pas' {frmCalendarioMediosDeTransporte: TFSForm},
  unRptTrasladosMediosDeTransporte in 'reports\unRptTrasladosMediosDeTransporte.pas' {qrTrasladosMediosDeTransporte: TQuickRep},
  unRptRemitoMalaPraxis in 'reports\unRptRemitoMalaPraxis.pas' {qrRemitoMalaPraxis: TQuickRep},
  unQrLibreDeuda in '..\cobranzas\reports\unQrLibreDeuda.pas' {qrLibreDeuda: TQuickRep},
  unVentanillaElectronica in '..\comunes\forms\unVentanillaElectronica.pas' {frmVentanillaElectronica: TFSForm},
  unFraTrabajadorSiniestro in '..\comunes\frames\new\unFraTrabajadorSiniestro.pas' {fraTrabajadorSiniestro: TFrame},
  unRptGestionDeReclamos in '..\comunes\reports\unRptGestionDeReclamos.pas' {frmRptGestionDeReclamos},
  unLiqAMPNotaDebito in 'unLiqAMPNotaDebito.pas' {frmLiqAMPNotaDebito},
  unLiqAMPAprob in 'unLiqAMPAprob.pas' {frmLiqAMPAprob},
  unLiqAMPAutPago in 'unLiqAMPAutPago.pas' {frmLiqAMPAutPago},
  unLiqAMPCarga in 'unLiqAMPCarga.pas' {frmLiqAMPCarga},
  unfraFirmantes in '..\comunes\frames\new\unfraFirmantes.pas' {fraFirmantes: TFrame},
  unMedicamentosCronicos in 'unMedicamentosCronicos.pas' {frmMedicamentosCronicos: TFSForm},
  unAgendaTelefonica in '..\comunes\forms\unAgendaTelefonica.pas' {frmAgendaTelefonica: TFSForm},
  unManGruposPrestaciones in 'abm\unManGruposPrestaciones.pas' {frmManGruposPrestaciones: TFSForm},
  unPresupuestosCargados in 'unPresupuestosCargados.pas' {frmPresupuestosCargados: TFSForm},
  unRptEstudiosVolante in 'reports\unRptEstudiosVolante.pas' {rptEstudiosVolante: TQuickRep},
  unManCTB_CUBIC in 'unManCTB_CUBIC.pas' {frmManCTB_CUBIC: TFSForm},
  unManResponsable in 'unManResponsable.pas' {frmManResponsable},
  unFraWebBrowser in '..\comunes\frames\new\unFraWebBrowser.pas' {fraWebBrowser: TFrame},
  unGoogleMaps in '..\comunes\forms\unGoogleMaps.pas' {frmGoogleMaps},
  unFraDomicilioGIS in '..\comunes\frames\new\unFraDomicilioGIS.pas' {fraDomicilioGIS: TFrame},
  unFraDomicilioTrabajador in '..\comunes\frames\new\unFraDomicilioTrabajador.pas' {fraDomicilioTrabajador: TFrame},
  unFraDomicilioEmpresa in '..\comunes\frames\new\unFraDomicilioEmpresa.pas' {fraDomicilioEmpresa: TFrame},
  unManCGI_GIS in '..\comunes\forms\unManCGI_GIS.pas' {frmManCGI_GIS: TFSForm},
  unEnviosSRT in '..\comunes\forms\unEnviosSRT.pas' {frmEnviosSRT: TFSForm},
  unVisorPDF in '..\comunes\forms\unVisorPDF.pas' {frmVisorPDF},
  unFraEstablecimientoContrato in '..\comunes\frames\unFraEstablecimientoContrato.pas' {fraEstablecimientoContrato: TFrame},
  unAnexoRes365 in '..\comunes\forms\unAnexoRes365.pas' {frmAnexoRes365},
  unRptAnexoRes365 in '..\comunes\reports\unRptAnexoRes365.pas' {qrAnexoRes365: TQuickRep},
  OneSession in '..\..\comunes\OneSession.pas',
  unManPresupuestoMensual in 'unManPresupuestoMensual.pas' {frmManPresupuestoMensual: TFSForm},
  unRGRL in '..\comunes\forms\unRGRL.pas' {frmRGRL},
  unRptRGRL in '..\comunes\reports\unRptRGRL.pas' {qrRGRL: TQuickRep},
  unFraEmpresaAfi in '..\comunes\frames\new\unFraEmpresaAfi.pas' {fraEmpresaAfi: TFrame},
  unManCTA_TIPOACTIVOS in '..\comunes\forms\unManCTA_TIPOACTIVOS.pas' {frmManCTA_TIPOACTIVOS: TFSForm},
  unManCPG_PLAZOGUARDA in '..\comunes\forms\unManCPG_PLAZOGUARDA.pas' {frmManCPG_PLAZOGUARDA: TFSForm},
  unClasificacionActivos in '..\comunes\forms\unClasificacionActivos.pas' {frmClasificacionActivos: TFSForm},
  unfraCodigoDescripcionExt in '..\comunes\frames\unfraCodigoDescripcionExt.pas' {fraCodigoDescripcionExt: TFrame},
  unSeleccionMultiple in '..\comunes\forms\unSeleccionMultiple.pas' {frmSeleccionUsuarios: TFrame},
  unListRecalSeguimiento in 'unListRecalSeguimiento.pas' {frmListRecalSeguimiento: TFSForm},
  unfraPrestador in '..\comunes\frames\unfraPrestador.pas' {fraPrestador: TFrame},
  unRptDenunciaStandard in '..\comunes\reports\unRptDenunciaStandard.pas' {rptDenunciaStandard: TQuickRep},
  unImpoExpo in '..\..\comunes\unImpoExpo.pas',
  unRptCeseDeILT in 'reports\unRptCeseDeILT.pas' {rptCeseDeILT: TQuickRep},
  unManAuditoresVolantes in 'unManAuditoresVolantes.pas' {frmManAuditoresVolantes},
  unCartaAuditConsultorio in 'unCartaAuditConsultorio.pas' {frmCartaAuditConsultorio: TFSForm},
  unRptAuditConsultorio in 'reports\unRptAuditConsultorio.pas' {rptAuditConsultorio: TQuickRep},
  unProtPosForzadas in '..\adminanalisis\unProtPosForzadas.pas' {frmProtPosForzadas: TFSForm},
  unEstExamPeriodORL in '..\adminanalisis\unEstExamPeriodORL.pas' {frmEstExamenORL},
  unEstIluminacion in '..\adminanalisis\unEstIluminacion.pas' {frmEstIluminacion},
  unVisor in '..\comunes\forms\unVisor.pas' {frmVisor},
  unArchivoVisor in '..\comunes\unArchivoVisor.pas',
  unVisorExcel in '..\comunes\forms\unVisorExcel.pas' {frmVisorExcel},
  unManMotivosDebitoAuditoria in 'abm\unManMotivosDebitoAuditoria.pas' {frmManMotivoDebitoAuditoria},
  unDebitosAuditoria in 'unDebitosAuditoria.pas' {frmDebitosAuditoria: TFSForm},
  unTercerizadoras in '..\..\comunes\unTercerizadoras.pas',
  unDiscrepanciasAuditoria in 'unDiscrepanciasAuditoria.pas' {frmDiscrepanciasAuditoria: TFSForm},
  unControlVersion in '..\..\comunes\unControlVersion.pas',
  unFraSDA_DETALLEARCHIVO in '..\comunes\frames\unFraSDA_DETALLEARCHIVO.pas' {fraSDA_DETALLEARCHIVO: TFrame},
  unGrabarDocumentoCarpeta in '..\comunes\forms\unGrabarDocumentoCarpeta.pas' {frmGrabarDocumentoCarpeta},
  unListExamenesPreocupacionales in 'unListExamenesPreocupacionales.pas' {frmListExamenesPreocupacionales: TFSForm},
  unDevolucionFacturas in 'unDevolucionFacturas.pas' {frmDevolucionFacturas: TFSForm},
  unManTipoFacturas in 'unManTipoFacturas.pas' {frmManTipoFacturas},
  unFraOPV_PROVEEDOR in '..\afiliaciones\tesoreria\frames\unFraOPV_PROVEEDOR.pas' {fraOPV_PROVEEDOR: TFrame},
  unRptDevolucionFacturas in 'reports\unRptDevolucionFacturas.pas' {qrDevolucionFacturas: TQuickRep},
  unManMotivosBajaSeguimiento in 'abm\unManMotivosBajaSeguimiento.pas' {frmMotivosBajaSeguimientos: TFSForm},
  UnManAbandEventos in 'abm\UnManAbandEventos.pas' {frmManAbandEventos: TFSForm},
  unFrmDetalleArchivo in '..\archivo_new\unFrmDetalleArchivo.pas',
  unFraDetalleArchivo in '..\archivo_new\frames\unFraDetalleArchivo.pas' {fraDetalleArchivo: TFrame},
  unFrmConsultaCarpetas in '..\archivo_new\unFrmConsultaCarpetas.pas' {FrmConsultaCarpetas: TFSForm},
  unFraFiltroArchivo in '..\archivo_new\frames\unFraFiltroArchivo.pas' {fraFiltroArchivo: TFrame},
  unFrmSolicitudCarpeta in '..\archivo_new\unFrmSolicitudCarpeta.pas' {FrmSolicitudCarpeta: TFSForm},
  unQrEtiquetasCarpetas in '..\archivo_new\unQrEtiquetasCarpetas.pas' {qrEtiquetasCarpetas: TQuickRep},
  unMovimientoCarpetas in '..\archivo_new\unMovimientoCarpetas.pas' {frmMovimientoCarpetas},
  unFrmCargaDocumentacion in '..\archivo_new\unFrmCargaDocumentacion.pas' {frmCargaDocumentacion},
  unQrDetalleLoteEstudio in '..\archivo_new\unQrDetalleLoteEstudio.pas' {QrDetalleLoteEstudio},
  unReemplazoCarpetas in '..\archivo_new\unReemplazoCarpetas.pas' {frmReemplazoCarpetas},
  unfrmUbicacionActual in '..\archivo_new\unfrmUbicacionActual.pas' {FrmUbicacionActual},
  unfraArchJuicio in '..\archivo_new\frames\unfraArchJuicio.pas' {fraArchJuicio: TFrame},
  unfraProveedor in '..\comunes\frames\new\unfraProveedor.pas' {fraProveedor: TFrame},
  unComisiones in '..\afiliaciones\comisiones\unComisiones.pas',
  unAbandonoTratamiento in 'unAbandonoTratamiento.pas' {frmAbandonoTratamiento: TFSForm},
  UnRptFonoaudiologia in 'reports\UnRptFonoaudiologia.pas' {rptFonoaudiologia: TQuickRep},
  unRptRegRehabilitacion in 'reports\unRptRegRehabilitacion.pas' {qrRegRehabilitacion: TQuickRep},
  unRptMoldeReporteRTF in 'reports\unRptMoldeReporteRTF.pas' {qrMoldeReporteRTF: TQuickRep},
  unRptFKTNuevo in 'unRptFKTNuevo.pas' {rptFKTNuevo: TQuickRep},
  UnRptInvestAdmNuevo in 'UnRptInvestAdmNuevo.pas' {rptInvestAdminNueva},
  unRptRegRehabNuevo in 'unRptRegRehabNuevo.pas' {rptRegRehabNuevo: TQuickRep},
  UnRptFonoaudNuevo in 'UnRptFonoaudNuevo.pas' {rptFonoaudNuevo: TQuickRep},
  unRptMatOrtNuevo in 'unRptMatOrtNuevo.pas' {rptMatOrtNuevo: TQuickRep},
  UnRptPedidoEntrega in 'UnRptPedidoEntrega.pas' {rptPedidoEntrega: TQuickRep},
  UnRptInvestAdministrativa in 'UnRptInvestAdministrativa.pas' {rptInvestAdministrativas},
  unRptTrasladosPlataforma in 'unRptTrasladosPlataforma.pas' {rptTrasladosPlataforma: TQuickRep},
  unRptComunes in 'unRptComunes.pas',
  unCustomSplash in '..\comunes\reposit\unCustomSplash.pas' {frmCustomSplash},
  unWelcomeSplash in '..\comunes\forms\unWelcomeSplash.pas' {frmWelcomeSplash},
  unReferentesDelegacion in 'abm\unReferentesDelegacion.pas' {frmReferentesDel: TFSForm},
  unCambioDelegacion in 'unCambioDelegacion.pas' {frmCambioDelegacion},
  unCargaDocumentosDigitaliz in '..\comunes\forms\unCargaDocumentosDigitaliz.pas' {frmCargaDocumentosDigitaliz},
  unTesoreria in '..\afiliaciones\tesoreria\unTesoreria.pas',
  unFraActividad in '..\comunes\frames\unFraActividad.pas' {fraActividad: TFrame},
  unContratoTrabajador in '..\afiliaciones\unContratoTrabajador.pas' {frmContratoTrabajador},
  unEstablecimientosTrabajador in '..\afiliaciones\unEstablecimientosTrabajador.pas' {frmEstablecimientosTrabajador},
  unAfiliaciones in '..\afiliaciones\unAfiliaciones.pas',
  unMotivosBajaPrest in 'abm\unMotivosBajaPrest.pas' {frmMotivosBajaPrest: TFSForm},
  unPrestadorAuditoria in 'abm\unPrestadorAuditoria.pas' {frmPrestadorAuditoria: TFSForm},
  unManIIBBProvincias in 'abm\unManIIBBProvincias.pas' {frmIIBBProvincias: TFSForm},
  unEventosAutorizacion in 'unEventosAutorizacion.pas' {frmEventosAutorizacion: TFSForm},
  unfraContactoAGENDA in '..\comunes\frames\modulosagenda\unfraContactoAGENDA.pas' {fraContactoAGENDA: TFrame},
  unfraContactoLibreAGENDA in '..\comunes\frames\modulosagenda\unfraContactoLibreAGENDA.pas' {fraContactoLibreAGENDA: TFrame},
  unfraDomicilioAGENDA in '..\comunes\frames\modulosagenda\unfraDomicilioAGENDA.pas' {fraDomicilioGISAGENDA: TFrame},
  unfraDomicilioEmpresaAGENDA in '..\comunes\frames\modulosagenda\unfraDomicilioEmpresaAGENDA.pas' {fraDomicilioEmpresaAGENDA: TFrame},
  unfraDomicilioEstablecimientoAGENDA in '..\comunes\frames\modulosagenda\unfraDomicilioEstablecimientoAGENDA.pas' {fraDomicilioEstablecimientoAGENDA: TFrame},
  unfraEmpresaAGENDA in '..\comunes\frames\modulosagenda\unfraEmpresaAGENDA.pas' {fraEmpresaAGENDA: TFrame},
  unfraEntidadAGENDA in '..\comunes\frames\modulosagenda\unfraEntidadAGENDA.pas' {fraEntidadAGENDA: TFrame},
  unfraEntidadVendedorAGENDA in '..\comunes\frames\modulosagenda\unfraEntidadVendedorAGENDA.pas' {fraEntidadVendedorAGENDA: TFrame},
  unfraEstablecimientoAGENDA in '..\comunes\frames\modulosagenda\unfraEstablecimientoAGENDA.pas' {fraEstablecimientoAGENDA: TFrame},
  unfraNumAutoAGENDA in '..\comunes\frames\modulosagenda\unfraNumAutoAGENDA.pas' {fraNumAutoAGENDA: TFrame},
  unfraPrestadorAGENDA in '..\comunes\frames\modulosagenda\unfraPrestadorAGENDA.pas' {fraPrestadorAGENDA: TFrame},
  unfraProspectosAGENDA in '..\comunes\frames\modulosagenda\unfraProspectosAGENDA.pas' {fraProspectosAGENDA: TFrame},
  unfraTrabajadorAGENDA in '..\comunes\frames\modulosagenda\unfraTrabajadorAGENDA.pas' {fraTrabajadorAGENDA: TFrame},
  unfraTrabajadorSiniestroAGENDA in '..\comunes\frames\modulosagenda\unfraTrabajadorSiniestroAGENDA.pas' {fraTrabajadorSiniestroAGENDA: TFrame},
  unfraVendedorAGENDA in '..\comunes\frames\modulosagenda\unfraVendedorAGENDA.pas' {fraVendedorAGENDA: TFrame},
  unfraInfoEmpresa in '..\comunes\frames\new\unfraInfoEmpresa.pas' {fraInfoEmpresa: TFrame},
  unfraVistaEventos in '..\comunes\frames\modulosagenda\unfraVistaEventos.pas' {fraVistaEventos: TFrame},
  unfraInfoEmpresaExt in '..\comunes\frames\new\unfraInfoEmpresaExt.pas' {fraInfoEmpresaExt: TFrame},
  unAgenda in '..\..\comunes\interfaces\unAgenda.pas',
  unContratoContacto in '..\comunes\forms\unContratoContacto.pas' {frmContratoContacto},
  unFraValidacionDatosEmpresa in '..\comunes\frames\new\unFraValidacionDatosEmpresa.pas' {fraValidacionDatosEmpresa: TFrame},
  unDlgBusSiniestro in '..\siniestros\unDlgBusSiniestro.pas' {frmDlgBusSiniestro: TFSForm},
  unFraUsuarioConJerarquias in '..\comunes\frames\new\unFraUsuarioConJerarquias.pas' {fraUsuarioConJerarquias: TFrame},
  unABMAgendaBase in '..\comunes\forms\unABMAgendaBase.pas' {frmABMAgendaBase},
  unABMAgendaBaseEvento in '..\comunes\forms\unABMAgendaBaseEvento.pas' {frmABMAgendaBaseEvento},
  unABMAgendaBaseTarea in '..\comunes\forms\unABMAgendaBaseTarea.pas' {frmABMAgendaBaseTarea},
  unFraTitulo in '..\comunes\frames\nuevos\unFraTitulo.pas' {fraTitulo: TFrame},
  unAyuda in '..\comunes\unAyuda.pas' {frmAyuda},
  unSeleccionResponsableHYS in '..\hys\unSeleccionResponsableHYS.pas' {frmSeleccionResponsableHYS: TFSForm},
  unAgendaVistaGenerica in '..\comunes\forms\unAgendaVistaGenerica.pas' {frmAgendaVistaGenerica},
  unAgendaVistaPrestador in '..\comunes\forms\unAgendaVistaPrestador.pas' {frmAgendaVistaPrestador},
  unEjecutivoCuenta in '..\comunes\forms\unEjecutivoCuenta.pas' {frmEjecutivoCuenta},
  unGestorCuenta in '..\comunes\forms\unGestorCuenta.pas' {frmGestorCuenta},
  unAgendaVistaEmpresa in '..\comunes\forms\unAgendaVistaEmpresa.pas' {frmAgendaVistaEmpresa},
  unSeleccionTareas in '..\comunes\forms\unSeleccionTareas.pas' {frmSeleccionTareas},
  unConsultasAdicionales in '..\comunes\forms\unConsultasAdicionales.pas' {frmConsultasAdicionales},
  unManMEP_EMPRESAPRESTADOR in 'abm\unManMEP_EMPRESAPRESTADOR.pas' {frmManMEP_EMPRESAPRESTADOR: TFSForm},
  unManSiniestrosTopeados in 'unManSiniestrosTopeados.pas' {frmManSiniestrosTopeados: TFSForm},
  unArt in '..\..\comunes\unArt.pas',
  unArchivo in '..\archivo_new\unArchivo.pas',
  unRptResumen in '..\siniestros\reports\unRptResumen.pas' {rptResumen: TQuickRep},
  unQrDetalleRemitoDevolucion in '..\archivo_new\unQrDetalleRemitoDevolucion.pas' {QrDetalleRemitoDevolucion},
  unFraEmpresaSolicitud in '..\comunes\frames\new\unFraEmpresaSolicitud.pas' {fraEmpresaSolicitud: TFrame},
  unfraEmpresaSolicitudAGENDA in '..\comunes\frames\modulosagenda\unfraEmpresaSolicitudAGENDA.pas' {fraEmpresaSolicitudAGENDA: TFrame},
  unServiciosAEmpresas in 'unServiciosAEmpresas.pas' {frmServiciosAEmpresas: TFSForm},
  unEmpresasPrestadoras in 'abm\unEmpresasPrestadoras.pas' {frmEmpresasPrestadoras: TFSForm},
  Periodo in '..\..\comunes\Periodo.pas',
  unManCVS_VENTANILLA_SUBTEMAS in '..\comunes\forms\unManCVS_VENTANILLA_SUBTEMAS.pas' {frmManCVS_VENTANILLA_SUBTEMAS: TFSForm},
  unfraDatoFechaAGENDA in '..\comunes\frames\modulosagenda\unfraDatoFechaAGENDA.pas' {fraDatoFecha: TFrame},
  unManEventosReca in 'abm\unManEventosReca.pas' {frmManEventosReca: TFSForm},
  unManPrestadoresPorGTrabajo in 'abm\unManPrestadoresPorGTrabajo.pas' {frmPrestadoresPorGtrabajo: TFSForm},
  unMensajeAlerta in '..\..\comunes\unMensajeAlerta.pas',
  unAlarmas in '..\..\comunes\unAlarmas.pas',
  unMensajeAlertaAGA in '..\archivo_new\unMensajeAlertaAGA.pas',
  unManPrestadorUsuario in 'abm\unManPrestadorUsuario.pas' {frmManPrestadorUsuario: TFSForm},
  unFraGIS_APIv3 in '..\comunes\frames\new\unFraGIS_APIv3.pas' {fraGIS_APIv3: TFrame},
  unGIS in '..\..\comunes\unGIS.pas',
  unFraNavegadorWEB in '..\comunes\frames\new\unFraNavegadorWEB.pas' {fraNavegadorWEB: TFrame},
  unEsperaSimple in '..\comunes\forms\unEsperaSimple.pas' {frmEsperaSimple},
  unManGrupoTrabajo2 in 'abm\unManGrupoTrabajo2.pas' {frmManGrupoTrabajo2: TFSForm},
  unControlGIS in '..\sistemas\unControlGIS.pas' {frmControlGIS: TFSForm},
  unImportCryptoSrt in '..\..\comunes\unImportCryptoSrt.pas',
  unConsVol in 'unConsVol.pas' {frmConsVol},
  unSeleccionarCarpetaSRT in '..\afiliaciones\unSeleccionarCarpetaSRT.pas' {frmSeleccionarCarpetaSRT},
  unEnvioMailTipoPres in 'unEnvioMailTipoPres.pas' {frmEnvioMailTipoPres},
  unEnvioSMS in '..\comunes\forms\unEnvioSMS.pas' {frmEnvioSMS},
  unSMS in '..\..\comunes\unSMS.pas',
  IArtMail in '..\Comunes\IArtMail.pas',
  unManCTS_TEXTOSMS in '..\comunes\forms\unManCTS_TEXTOSMS.pas' {frmManCTS_TEXTOSMS: TFSForm},
  unAuditoresPrestador in 'abm\unAuditoresPrestador.pas' {frmAuditoresPorPrestador: TFSForm},
  unfraZonasPrestador in 'frames\unfraZonasPrestador.pas' {fraZonasPrestador: TFrame},
  unAgendaVistaExpediente in '..\comunes\forms\unAgendaVistaExpediente.pas' {frmAgendaVistaExpediente},
  unSeleccionarFechaFinTrat in '..\siniestros\unSeleccionarFechaFinTrat.pas' {frmSeleccionarFechaFinTrat},
  unRptSolicitudReingreso in 'reports\unRptSolicitudReingreso.pas' {frmRptSolicitudReingreso},
  unFraTipoRegimen in '..\comunes\frames\new\unFraTipoRegimen.pas' {fraTipoRegimen: TFrame},
  UnReportePLA in 'UnReportePLA.pas' {frmReportePLA: TFSForm},
  unRptInfoPLA in 'reports\unRptInfoPLA.pas' {frmRptInfoPLA},
  unRptDeclaracionAccidentado in 'reports\unRptDeclaracionAccidentado.pas' {rptDeclaracionAccidentado: TQuickRep},
  unRptSolicitudAuditoria in 'unRptSolicitudAuditoria.pas' {rptSolicitudAuditoria: TQuickRep},
  unEgresosSemanales in 'unEgresosSemanales.pas' {frmEgresosSemanales},
  unRptEgresosSemanales in 'reports\unRptEgresosSemanales.pas' {rptEgresosSemanales: TQuickRep},
  unUsuariosPorGrupo in 'abm\unUsuariosPorGrupo.pas' {frmUsuariosPorGrupo: TFSForm},
  unGruposPrestador in 'abm\unGruposPrestador.pas' {frmGruposPrestador: TFSForm},
  unReportePorAuditor in 'unReportePorAuditor.pas' {frmReportePorAuditor: TFSForm},
  unUtilsArchivo in '..\archivo_new\unUtilsArchivo.pas',
  unQrEtiquetasDocCarpetas in '..\archivo_new\unQrEtiquetasDocCarpetas.pas' {qrEtiquetasDocCarpetas: TQuickRep};

{$R *.RES}

begin
  OnlyOneInstance;
  Application.Initialize;
  Application.Title := 'Prestaciones Médicas';

  with TfrmWelcomeSplash.Create(Application) do
  try
    ShowOnTop;
    Application.CreateForm(TdmPrincipal, dmPrincipal);
  Application.CreateForm(TdmFinancials, dmFinancials);
  if dmPrincipal.sdbPrincipal.Connected then
      Application.CreateForm(TfrmPrincipal, frmPrincipal);
    //OnlyOneSession;
  finally
    Free;
  end;

  MostrarNovedades;
  Application.Run;
end.
