program Siniestros;

{$R *.dres}

uses
  OneInstance,
  Forms,
  Controls,
  Windows,
  unArt in '..\..\Comunes\unArt.pas',
  unCustomDataModule in '..\Comunes\unCustomDataModule.pas' {dmCustomDataModule: TDataModule},
  unDmPrincipal in '..\Comunes\ORACLE\unDmPrincipal.pas' {dmPrincipal: TDataModule},
  unPrincipal in 'unPrincipal.pas' {frmPrincipal},
  unArtFrame in '..\Comunes\REPOSIT\unArtFrame.pas' {ArtFrame: TFrame},
  unArtDBAwareFrame in '..\Comunes\REPOSIT\unArtDBAwareFrame.pas' {ArtDBAwareFrame: TFrame},
  unFraCodigoDescripcion in '..\Comunes\FRAMES\unFraCodigoDescripcion.pas' {fraCodigoDescripcion: TFrame},
  unFraCtbTablas in '..\Comunes\FRAMES\unFraCtbTablas.pas' {fraCtbTablas: TFrame},
  unArtDbFrame in '..\Comunes\REPOSIT\unArtDbFrame.pas' {ArtDbFrame: TFrame},
  unFraEmpresa in '..\Comunes\FRAMES\NEW\unFraEmpresa.pas' {fraEmpresa: TFrame},
  unFraEmpresaAfi in '..\Comunes\FRAMES\NEW\unFraEmpresaAfi.pas' {fraEmpresaAfi: TFrame},
  unFraEmpresaSolicitud in '..\Comunes\FRAMES\NEW\unFraEmpresaSolicitud.pas' {fraEmpresaSolicitud: TFrame},
  unCustomConsulta in '..\Comunes\REPOSIT\unCustomConsulta.pas' {frmCustomConsulta},
  unCustomPanelABM in '..\Comunes\REPOSIT\unCustomPanelABM.pas' {frmCustomPanelABM},
  unCustomGridABM in '..\Comunes\REPOSIT\unCustomGridABM.pas' {frmCustomGridABM},
  unAdmSiniestros in 'unAdmSiniestros.pas' {frmAdmSiniestros},
  unFraTrabajador in '..\Comunes\FRAMES\NEW\unFraTrabajador.pas' {fraTrabajador: TFrame},
  unFraTrabajadorSiniestro in '..\Comunes\FRAMES\NEW\unFraTrabajadorSiniestro.pas' {fraTrabajadorSiniestro: TFrame},
  unDenunciaGrave in 'ADMSIN\unDenunciaGrave.pas' {frmDenunciaGrave},
  unfraCPR_PRESTADOR in '..\Comunes\FRAMES\NEW\unfraCPR_PRESTADOR.pas' {fraCPR_PRESTADOR: TFrame},
  unFraStaticCodigoDescripcion in '..\Comunes\FRAMES\unFraStaticCodigoDescripcion.pas' {fraStaticCodigoDescripcion: TFrame},
  unFraStaticCTB_TABLAS in '..\Comunes\FRAMES\unFraStaticCTB_TABLAS.pas' {fraStaticCTB_TABLAS: TFrame},
  unParteEvolutivo in 'ADMSIN\unParteEvolutivo.pas' {frmParteEvolutivo},
  unSinForm in 'ADMSIN\unSinForm.pas' {SinForm},
  unSinFormNavigator in 'ADMSIN\unSinFormNavigator.pas' {SinFormNavigator},
  unFraDomicilio in '..\Comunes\FRAMES\NEW\unFraDomicilio.pas' {fraDomicilio: TFrame},
  unFraDomicilioTrab in '..\Comunes\FRAMES\NEW\unFraDomicilioTrab.pas' {fraDomicilioTrab: TFrame},
  unFraEstablecimiento in '..\Comunes\FRAMES\NEW\unFraEstablecimiento.pas' {fraEstablecimiento: TFrame},
  unContratoTrabajador in '..\Afiliaciones\unContratoTrabajador.pas' {frmContratoTrabajador},
  unBusquedaDomicilio in '..\Comunes\Forms\unBusquedaDomicilio.pas' {frmBusquedaDomicilio},
  unAfiliaciones in '..\Afiliaciones\unAfiliaciones.pas',
  unEstablecimientosTrabajador in '..\Afiliaciones\unEstablecimientosTrabajador.pas' {frmEstablecimientosTrabajador},
  unManCCP_CUENTAPAGO in '..\Comunes\Forms\unManCCP_CUENTAPAGO.pas' {frmManCCP_CUENTAPAGO},
  unfraVendedores in '..\Comunes\FRAMES\unfraVendedores.pas' {fraVendedores: TFrame},
  unfraVendedoresCUIT in '..\Comunes\FRAMES\NEW\unfraVendedoresCUIT.pas' {fraVendedoresCUIT: TFrame},
  unAltaModifCCP_CUENTAPAGO in '..\Comunes\Forms\unAltaModifCCP_CUENTAPAGO.pas' {frmAltaModifCCP_CUENTAPAGO},
  unDlgBusSiniestro in 'unDlgBusSiniestro.pas' {frmDlgBusSiniestro},
  unConsulta in '..\Comunes\Forms\unConsulta.pas' {frmConsulta},
  unSiniestros in 'unSiniestros.pas',
  unFraSAU_AUTORIZACIONES in 'FRAMES\unFraSAU_AUTORIZACIONES.pas' {fraSAU_AUTORIZACIONES: TFrame},
  unFraSDA_DETALLEARCHIVO in '..\Comunes\FRAMES\unFraSDA_DETALLEARCHIVO.pas' {fraSDA_DETALLEARCHIVO: TFrame},
  unCustomSplash in '..\Comunes\REPOSIT\unCustomSplash.pas' {frmCustomSplash},
  unWelcomeSplash in '..\Comunes\Forms\unWelcomeSplash.pas' {frmWelcomeSplash},
  unExpediente in 'ADMSIN\unExpediente.pas' {frmExpediente},
  unFraCIE10 in '..\Comunes\FRAMES\unFraCIE10.pas' {fraCIE10: TFrame},
  VCLExtra in '..\..\Comunes\VCLExtra.pas',
  unDenunciaStandard in 'ADMSIN\unDenunciaStandard.pas' {frmDenunciaSTD: TFSForm},
  AnsiSql in '..\..\Comunes\AnsiSql.pas',
  DbFuncs in '..\..\Comunes\DbFuncs.pas',
  unSesion in '..\..\Comunes\unSesion.pas',
  CustomDlgs in '..\..\Comunes\CustomDlgs.pas',
  unDebug in '..\comunes\unDebug.pas' {frmDebug},
  unMoldeEnvioMail in '..\comunes\envio de mails\unMoldeEnvioMail.pas',
  unCustomForm in '..\comunes\unCustomForm.pas' {frmCustomForm},
  unFraToolbarRTF in '..\comunes\frames\unFraToolbarRTF.pas' {fraToolbarRTF: TFrame},
  unSeleccionDestinatarios in '..\comunes\unSeleccionDestinatarios.pas' {frmSeleccionDestinatarios: TFSForm},
  unLibretaDeDirecciones in '..\comunes\forms\unLibretaDeDirecciones.pas' {frmLibretaDeDirecciones: TFSForm},
  unElementosEnviados in '..\comunes\forms\unElementosEnviados.pas' {frmElementosEnviados: TFSForm},
  General in '..\..\Comunes\General.pas',
  unfraCuentaBancaria in '..\comunes\frames\new\unfraCuentaBancaria.pas' {fraCuentaBancaria: TFrame},
  unfraUsuarios in '..\comunes\frames\unfraUsuarios.pas' {fraUsuario: TFrame},
  unFraUsuario in '..\comunes\frames\new\unFraUsuario.pas' {fraUsuarios: TFrame},
  unParteIngreso in 'ADMSIN\unParteIngreso.pas' {frmParteIngreso: TFSForm},
  unParteEgreso in 'ADMSIN\unParteEgreso.pas' {frmParteEgreso: TFSForm},
  unFraSMC_MOTIVONOCARGA in 'FRAMES\unFraSMC_MOTIVONOCARGA.pas' {fraSMC_MOTIVONOCARGA: TFrame},
  unFraSTA_TIPOACCIDENTE in 'FRAMES\unFraSTA_TIPOACCIDENTE.pas' {fraSTA_TIPOACCIDENTE: TFrame},
  unFraSTC_TIPOGRAVEDAD_CIE10 in 'FRAMES\unFraSTC_TIPOGRAVEDAD_CIE10.pas' {fraSTC_TIPOGRAVEDAD_CIE10: TFrame},
  unFraStaticCodDesc in '..\comunes\frames\nuevos\unFraStaticCodDesc.pas' {fraStaticCodDesc: TFrame},
  unFraCodDesc in '..\comunes\frames\nuevos\unFraCodDesc.pas' {fraCodDesc: TFrame},
  unFraSTG_TIPOGRAVEDAD in 'FRAMES\unFraSTG_TIPOGRAVEDAD.pas' {fraSTG_TIPOGRAVEDAD: TFrame},
  unFraSLA_LESIONAGENTE in 'FRAMES\unFraSLA_LESIONAGENTE.pas' {fraSLA_LESIONAGENTE: TFrame},
  unFraSLF_LESIONFORMA in 'FRAMES\unFraSLF_LESIONFORMA.pas' {fraSLF_LESIONFORMA: TFrame},
  unFraSLN_LESIONNATURALEZA in 'FRAMES\unFraSLN_LESIONNATURALEZA.pas' {fraSLN_LESIONNATURALEZA: TFrame},
  unFraSLZ_LESIONZONA in 'FRAMES\unFraSLZ_LESIONZONA.pas' {fraSLZ_LESIONZONA: TFrame},
  unEspera in '..\comunes\forms\unEspera.pas' {frmEspera},
  unCITRIX in '..\..\Comunes\unCITRIX.pas',
  unFraCDG_DIAGNOSTICO in 'FRAMES\unFraCDG_DIAGNOSTICO.pas' {fraCDG_DIAGNOSTICO: TFrame},
  unFraCCI_CIUO in 'FRAMES\unFraCCI_CIUO.pas' {fraCCI_CIUO: TFrame},
  unResumen in 'ADMSIN\unResumen.pas' {frmResumen: TFSForm},
  unOtros in 'ADMSIN\unOtros.pas' {frmOtros: TFSForm},
  unParteAuditoria in 'ADMSIN\unParteAuditoria.pas' {frmParteAuditoria: TFSForm},
  DateTimeFuncs in '..\..\Comunes\DateTimeFuncs.pas',
  unDlgBusEstablecimiento in 'unDlgBusEstablecimiento.pas' {frmDlgBusEstablecimiento: TFSForm},
  unFraTelefono in '..\comunes\frames\new\unFraTelefono.pas' {fraTelefono: TFrame},
  unABMTelefonos in '..\comunes\forms\unABMTelefonos.pas' {frmTelefonos},
  unTelefonosCargaRapida in '..\comunes\forms\unTelefonosCargaRapida.pas' {frmTelefonosCargaRapida},
  unFraActividad in '..\comunes\frames\unFraActividad.pas' {fraActividad: TFrame},
  unCompatibilidad in '..\afiliaciones\unCompatibilidad.pas',
  unComunes in '..\..\comunes\unComunes.pas',
  unFraTipoSiniestro in 'FRAMES\unFraTipoSiniestro.pas' {fraTipoSiniestro: TFrame},
  unFraCPA_PAISES in '..\comunes\frames\new\unFraCPA_PAISES.pas' {fraCPA_PAISES: TFrame},
  unIncapacidadesPermanentes in 'unIncapacidadesPermanentes.pas' {frmIncapacidadesPermanentes},
  unRedPres in '..\..\Comunes\unRedPres.pas',
  unAlarmas in '..\..\Comunes\unAlarmas.pas',
  Cuit in '..\..\Comunes\Cuit.pas',
  strfuncs in '..\..\Comunes\strfuncs.pas',
  unEnvioMail in '..\..\Comunes\unEnvioMail.pas',
  unFraTipoEgreso in 'FRAMES\unFraTipoEgreso.pas' {fraTipoEgreso: TFrame},
  unFraTipoTratamiento in 'FRAMES\unFraTipoTratamiento.pas' {fraTipoTratamiento: TFrame},
  unVisualizador in '..\comunes\unVisualizador.pas' {frmVisualizador},
  unFraTipoAtencion in 'FRAMES\unFraTipoAtencion.pas' {fraTipoAtencion: TFrame},
  unFraMAU_AUDITORES in 'FRAMES\unFraMAU_AUDITORES.pas' {fraMAU_AUDITORES: TFrame},
  unFraMIM_IMPLANTES in 'FRAMES\unFraMIM_IMPLANTES.pas' {fraMIM_IMPLANTES: TFrame},
  unFraDomicilioEmpresa in '..\comunes\frames\new\unFraDomicilioEmpresa.pas' {fraDomicilioEmpresa: TFrame},
  unFraDomicilioTrabajador in '..\comunes\frames\new\unFraDomicilioTrabajador.pas' {fraDomicilioTrabajador: TFrame},
  unfraDelegacion in '..\comunes\frames\unfraDelegacion.pas' {fraDelegacion: TFrame},
  unCambioDelegacion in 'unCambioDelegacion.pas' {frmCambioDelegacion},
  unfraSectores in '..\comunes\frames\unfraSectores.pas' {fraSectores: TFrame},
  unEvolucionDeEstados in 'unEvolucionDeEstados.pas' {frmEvolucionDeEstados},
  unContratoContacto in '..\comunes\forms\unContratoContacto.pas' {frmContratoContacto},
  unfraContacto in '..\comunes\frames\unfraContacto.pas' {fraContacto: TFrame},
  SpoolFuncs in '..\..\Comunes\SpoolFuncs.pas',
  unFraPrestadorExtendido in '..\comunes\frames\new\unFraPrestadorExtendido.pas' {fraPrestadorExtendido: TFrame},
  unFraPrestadorFueraDeContrato in '..\comunes\frames\new\unFraPrestadorFueraDeContrato.pas' {fraPrestadorFueraDeContrato: TFrame},
  unConsultaNomina in 'unConsultaNomina.pas' {frmConsultaNomina: TFSForm},
  unConsultaEmpresa in 'unConsultaEmpresa.pas' {frmConsultaEmpresa: TFSForm},
  unConfidencial in '..\..\Comunes\unConfidencial.pas',
  unFraRTD_TIPODOCUMENTO in '..\comunes\frames\new\unFraRTD_TIPODOCUMENTO.pas' {fraRTD_TIPODOCUMENTO: TFrame},
  unVisualizadorDigitalizacion in '..\comunes\forms\unVisualizadorDigitalizacion.pas' {frmVisualizadorDigitalizacion: TFSForm},
  unFraVistaTIFF in '..\comunes\frames\new\unFraVistaTIFF.pas' {fraVistaTIFF: TFrame},
  libgfl in '..\..\Comunes\libgfl.pas',
  unFraDigitalizacion in '..\comunes\frames\new\unFraDigitalizacion.pas' {fraDigitalizacion: TFrame},
  ungrids in '..\..\Comunes\ungrids.pas',
  unFaxEnviados in '..\comunes\forms\unFaxEnviados.pas' {frmFaxEnviados: TFSForm},
  unConsFax in '..\Comunes\Forms\unConsFax.pas' {frmConsFax: TFSForm},
  unfraFFO_FAXFORMULARIO in '..\fax\faxclient_new\frames\unfraFFO_FAXFORMULARIO.pas' {fraFFO_FAXFORMULARIO: TFrame},
  unEstrategiaTIFF in '..\fax\faxclient_new\unEstrategiaTIFF.pas',
  unImageFunctions in '..\..\Comunes\unImageFunctions.pas',
  unFaxFuncs in '..\..\Comunes\unFaxFuncs.pas',
  unUbicacionDenuncia in 'unUbicacionDenuncia.pas' {frmUbicacionDenuncia},
  unFraCCO_PARTIDOS_CODIGOSPOSTALES in 'FRAMES\unFraCCO_PARTIDOS_CODIGOSPOSTALES.pas' {fraCCO_PARTIDOS_CODIGOSPOSTALES: TFrame},
  unRptResumen in 'REPORTS\unRptResumen.pas' {rptResumen: TQuickRep},
  unManRDO_DOCUMENTO in '..\archivo_new\abm\unManRDO_DOCUMENTO.pas' {frmManRDO_DOCUMENTO: TFSForm},
  unExportPDF in '..\..\Comunes\unExportPDF.pas',
  unLiqIncapacidades in '..\dinerarias\unLiqIncapacidades.pas' {frmLiqIncapacidades},
  unTercerizadoras in '..\..\Comunes\unTercerizadoras.pas',
  unDmFinancials in '..\comunes\oracle\unDmFinancials.pas' {dmFinancials: TDataModule},
  unCustomPrincipal in '..\comunes\reposit\unCustomPrincipal.pas' {frmCustomPrincipal},
  numeros in '..\..\Comunes\numeros.pas',
  unFraSFD_FORMADIAGNOSTICO in 'FRAMES\unFraSFD_FORMADIAGNOSTICO.pas' {fraSFD_FORMADIAGNOSTICO: TFrame},
  unFraSLM_LESIONAGENTEMATERIAL in 'FRAMES\unFraSLM_LESIONAGENTEMATERIAL.pas' {fraSLM_LESIONAGENTEMATERIAL: TFrame},
  unCierreExpedientes in 'unCierreExpedientes.pas' {frmCierreExpedientes},
  unfraEntidadCUIT in '..\comunes\frames\new\unfraEntidadCUIT.pas' {fraEntidadCUIT: TFrame},
  unNovedades in '..\..\Comunes\unNovedades.pas',
  unSegIncapacidades in 'unSegIncapacidades.pas' {frmSegIncapacidades: TFSForm},
  unManComisionesMedicas in 'unManComisionesMedicas.pas' {frmManComisionesMedicas},
  unManUbicIncap in 'unManUbicIncap.pas' {frmManUbicIncap},
  unEmisionFormularios in 'unEmisionFormularios.pas' {frmEmisionFormularios},
  unRptHistSiniestral in 'reports\unRptHistSiniestral.pas' {qrHistSiniestral: TQuickRep},
  unRptInfCodInca in 'reports\unRptInfCodInca.pas' {qrInfCodInca: TQuickRep},
  unRptAltaMedica in 'reports\unRptAltaMedica.pas' {qrAltaMedica: TQuickRep},
  unRptAcuerdoILPPD in 'reports\unRptAcuerdoILPPD.pas' {frmRptAcuerdoILPPD},
  unRptSolicitudIntervencion in 'reports\unRptSolicitudIntervencion.pas' {frmRptSolInt},
  unRptSolicitudPedidos in 'reports\unRptSolicitudPedidos.pas' {qrSolicitudPedidos: TQuickRep},
  unRptRevisionMedica in 'reports\unRptRevisionMedica.pas' {qrRevisionMedica: TQuickRep},
  unRptDocumentPrestDinerarias in 'reports\unRptDocumentPrestDinerarias.pas' {qrDocumentPrestDinerarias: TQuickRep},
  unRptEvolucion in '..\comunes\reports\unRptEvolucion.pas' {qrEvolucion: TQuickRep},
  unRptActaAcuedo in 'reports\unRptActaAcuedo.pas' {qrActaAcuerdo: TQuickRep},
  unListGralSegIncapacidades in 'unListGralSegIncapacidades.pas' {frmListGralSegIncapacidades: TFSForm},
  unListIncAprobadas in 'unListIncAprobadas.pas' {frmListIncAprobadas},
  unDatosSiniestro in '..\comunes\forms\unDatosSiniestro.pas' {frmDatosSiniestro},
  unRptParteAuditoriaGrave in 'reports\unRptParteAuditoriaGrave.pas' {rptParteAuditoriaGrave: TQuickRep},
  unRptParteAuditoriaLeve in 'reports\unRptParteAuditoriaLeve.pas' {rptParteAuditoriaLeve: TQuickRep},
  unRptConstanciaDomTrab in 'reports\unRptConstanciaDomTrab.pas' {qrConstanciaDomTrab: TQuickRep},
  unRptCartaAbandonoTto in 'reports\unRptCartaAbandonoTto.pas' {rptCartaAbandonoTto: TQuickRep},
  unRptDictamenFundMedicos in 'reports\unRptDictamenFundMedicos.pas' {qrDictamenFundMedicos: TQuickRep},
  unLiquidacionesAprobadas in 'unLiquidacionesAprobadas.pas' {frmLiquidacionesAprobadas},
  unRptNotaEntregaReq in 'reports\unRptNotaEntregaReq.pas',
  unFiltros in '..\..\Comunes\unFiltros.pas',
  unRptNotaRectificatoria in 'reports\unRptNotaRectificatoria.pas' {qrNotaRectificatoria: TQuickRep},
  unGestionImagenes in '..\comunes\digitalizacion\unGestionImagenes.pas' {frmGestionImagenes: TFSForm},
  unBajaPapeleria in 'unBajaPapeleria.pas' {frmBajaPapeleria},
  unRptParteEgreso in 'reports\unRptParteEgreso.pas' {rptParteEgreso: TQuickRep},
  unRptFormularioValidacionYRectificacionDatosEstablecimientos in '..\comunes\reports\unRptFormularioValidacionYRectificacionDatosEstablecimientos.pas' {qrFormularioValidacionYRectificacionDatosEstablecimientos: TQuickRep},
  unFormularioValidacionYRectificacionDatosEstablecimientos in '..\comunes\forms\unFormularioValidacionYRectificacionDatosEstablecimientos.pas' {frmFormularioValidacionYRectificacionDatosEstablecimientos},
  unMotivoCancelacionLiq in 'unMotivoCancelacionLiq.pas' {frmMotivoCancelacionLiq},
  unClassLiquidacion in '..\..\comunes\Clases\unClassLiquidacion.pas',
  unClassEmpresa in '..\..\comunes\Clases\unClassEmpresa.pas',
  unClassTrabajador in '..\..\comunes\Clases\unClassTrabajador.pas',
  unClassExpediente in '..\..\comunes\Clases\unClassExpediente.pas',
  unRptNotaBaja in 'reports\unRptNotaBaja.pas' {qrNotaBaja: TQuickRep},
  unfraInfoEmpresa in '..\comunes\frames\new\unfraInfoEmpresa.pas' {fraInfoEmpresa: TFrame},
  unfraInfoEmpresaExt in '..\comunes\frames\new\unfraInfoEmpresaExt.pas' {fraInfoEmpresaExt: TFrame},
  unConsultasAdicionales in '..\comunes\forms\unConsultasAdicionales.pas' {frmConsultasAdicionales},
  unOpcionesDeImpresion in '..\cobranzas\unOpcionesDeImpresion.pas' {frmOpcionesDeImpresion},
  unBaseAdministracionCartas in '..\comunes\forms\unBaseAdministracionCartas.pas' {frmBaseAdministracionCartas: TFSForm},
  unRptCartaDocHeader in '..\comunes\reports\unRptCartaDocHeader.pas' {rptCartaDocHeader: TQuickRep},
  unRptCartaDocumento in '..\comunes\reports\unRptCartaDocumento.pas' {rptCartaDocumento: TQuickRep},
  unImpoExpoWizard in '..\impoexpo\unImpoExpoWizard.pas' {frmImpoExpoWizard},
  unQrEstadoCuentaResumen in '..\cobranzas\reports\unQrEstadoCuentaResumen.pas' {frmEstadoCuentaResumen},
  unImpresionEstadoDeCuenta in '..\cobranzas\unImpresionEstadoDeCuenta.pas' {frmImpresionEstadodeCuenta},
  unQrEstadoCuentaDetalle in '..\cobranzas\reports\unQrEstadoCuentaDetalle.pas' {frmEstadoCuentaDetalle},
  unQRCartaDocIntimacion in '..\cobranzas\reports\unQRCartaDocIntimacion.pas' {QRCartaDocIntimacion: TQuickRep},
  unQRCartaDocIntimacionNuevaGrilla in '..\cobranzas\reports\unQRCartaDocIntimacionNuevaGrilla.pas' {QRCartaDocIntimacionNuevaGrilla: TQuickRep},
  unQRF801C in '..\cobranzas\reports\unQRF801C.pas' {QRF801C: TQuickRep},
  unQRF817 in '..\cobranzas\reports\unQRF817.pas' {QRF817: TQuickRep},
  unRptCartaDocCompensacion in '..\cobranzas\compensacion\reports\unRptCartaDocCompensacion.pas' {rptCartaDocCompensacion: TQuickRep},
  unEjecutivoCuenta in '..\comunes\forms\unEjecutivoCuenta.pas' {frmEjecutivoCuenta},
  unGestorCuenta in '..\comunes\forms\unGestorCuenta.pas' {frmGestorCuenta},
  unEstadoCuenta in '..\cobranzas\unEstadoCuenta.pas',
  unQrLibreDeuda in '..\cobranzas\reports\unQrLibreDeuda.pas' {qrLibreDeuda: TQuickRep},
  unVentanillaElectronica in '..\comunes\forms\unVentanillaElectronica.pas' {frmVentanillaElectronica: TFSForm},
  unRptGestionDeReclamos in '..\comunes\reports\unRptGestionDeReclamos.pas' {frmRptGestionDeReclamos},
  unRptReciboILT in '..\dinerarias\reports\unRptReciboILT.pas' {qrReciboILT: TQuickRep},
  unRptOrdenDePago in '..\dinerarias\reports\unRptOrdenDePago.pas' {qrOrdenDePago: TQuickRep},
  ABMDialog in '..\..\paquetes\abmdialog\ABMDialog.pas',
  SortDlg in '..\..\paquetes\sortdlg\SortDlg.pas',
  unAgendaTelefonica in '..\comunes\forms\unAgendaTelefonica.pas' {frmAgendaTelefonica: TFSForm},
  unFraNavegadorWEB in '..\comunes\frames\new\unFraNavegadorWEB.pas' {fraNavegadorWEB: TFrame},
  unGoogleMaps in '..\comunes\forms\unGoogleMaps.pas' {frmGoogleMaps},
  unFraDomicilioGIS in '..\comunes\frames\new\unFraDomicilioGIS.pas' {fraDomicilioGIS: TFrame},
  unManCGI_GIS in '..\comunes\forms\unManCGI_GIS.pas' {frmManCGI_GIS: TFSForm},
  unVisorPDF in '..\comunes\forms\unVisorPDF.pas' {frmVisorPDF},
  unListContCartasDoc in 'unListContCartasDoc.pas' {frmListContCartasDoc: TFSForm},
  unDatosLesion in 'unDatosLesion.pas' {frmDatosLesion},
  unListDictEnfNoList in 'unListDictEnfNoList.pas' {frmListDictEnfNoList: TFSForm},
  unRptLiqOtrosConceptos in 'reports\unRptLiqOtrosConceptos.pas' {qrLiqOtrosConceptos: TQuickRep},
  unRptReciboILP in '..\dinerarias\reports\unRptReciboILP.pas' {qrReciboILP: TQuickRep},
  unRptReciboOtrosConceptos in 'reports\unRptReciboOtrosConceptos.pas' {qrReciboOtrosConceptos: TQuickRep},
  unRptEstudiosCompl in 'reports\unRptEstudiosCompl.pas' {qrEstudiosCompl: TQuickRep},
  unLiqAprobacion in 'unLiqAprobacion.pas' {frmLiqAprobacion},
  unLiqAsigFam in '..\redpres\unLiqAsigFam.pas' {frmLiqAsigFam},
  unManAsigEspeciales in '..\redpres\unManAsigEspeciales.pas' {frmManAsigEspeciales},
  unManAsigHijos in '..\redpres\unManAsigHijos.pas' {frmManAsigHijos},
  unAnexoRes365 in '..\comunes\forms\unAnexoRes365.pas' {frmAnexoRes365},
  unRptAnexoRes365 in '..\comunes\reports\unRptAnexoRes365.pas' {qrAnexoRes365: TQuickRep},
  unManCAN_CHEQUEANOMBRE in '..\comunes\forms\unManCAN_CHEQUEANOMBRE.pas' {frmManCAN_CHEQUEANOMBRE: TFSForm},
  unRptEstadisticasRGRL in '..\comunes\reports\unRptEstadisticasRGRL.pas' {qrEstadisticasRGRL: TQuickRep},
  unRptRGRL in '..\comunes\reports\unRptRGRL.pas' {qrRGRL: TQuickRep},
  unRGRL in '..\comunes\forms\unRGRL.pas' {frmRGRL},
  unDigitalizacion in '..\..\comunes\unDigitalizacion.pas',
  unCompaniaSeguroRetiro in '..\redpres\unCompaniaSeguroRetiro.pas' {frmCompaniaSeguroRetiro},
  unRptResumenILP in '..\dinerarias\reports\unRptResumenILP.pas' {qrResumenILP: TQuickRep},
  unRptRemitoExpedientes in 'reports\unRptRemitoExpedientes.pas' {qrRemitoExpedientes: TQuickRep},
  unUtilsArchivo in '..\archivo_new\unUtilsArchivo.pas',
  unConstantArchivo in '..\archivo_new\unConstantArchivo.pas',
  unComunesArchivo in '..\archivo_new\unComunesArchivo.pas',
  unManCPG_PLAZOGUARDA in '..\comunes\forms\unManCPG_PLAZOGUARDA.pas' {frmManCPG_PLAZOGUARDA: TFSForm},
  unManCTA_TIPOACTIVOS in '..\comunes\forms\unManCTA_TIPOACTIVOS.pas' {frmManCTA_TIPOACTIVOS: TFSForm},
  unClasificacionActivos in '..\comunes\forms\unClasificacionActivos.pas' {frmClasificacionActivos: TFSForm},
  unfraCodigoDescripcionExt in '..\comunes\frames\unfraCodigoDescripcionExt.pas' {fraCodigoDescripcionExt: TFrame},
  unSeleccionMultiple in '..\comunes\forms\unSeleccionMultiple.pas' {frmSeleccionUsuarios: TFrame},
  unRptFormSelRetiro in '..\comunes\reports\unRptFormSelRetiro.pas' {rptFormSelRetiro: TQuickRep},
  unRptFormularioCotizacion in '..\dinerarias\reports\unRptFormularioCotizacion.pas' {rptFormularioCotizacion: TQuickRep},
  unRptIncapacidadRecibo in '..\dinerarias\reports\unRptIncapacidadRecibo.pas' {qrIncapacidadRecibo: TQuickRep},
  unRptLegajoSiniestro in 'reports\unRptLegajoSiniestro.pas' {qrLegajoSiniestro: TQuickRep},
  unRptDenunciaStandardS in 'reports\unRptDenunciaStandardS.pas' {qrDenunciaStandardS: TQuickRep},
  unListResumenDinerarias in '..\dinerarias\listados\unListResumenDinerarias.pas' {frmListResumenDinerarias: TFSForm},
  unImpoExpoUtils in '..\impoexpo\unImpoExpoUtils.pas',
  unRptSiniestroParaReingresar in 'reports\unRptSiniestroParaReingresar.pas' {qrSiniestroParaReingresar: TQuickRep},
  unRptEvalPrestacJuntaMed in 'reports\unRptEvalPrestacJuntaMed.pas' {qrEvalPrestacJuntaMed: TQuickRep},
  unRptParteIngreso in 'reports\unRptParteIngreso.pas' {qrParteIngreso: TQuickRep},
  unGeneracionIntereses in '..\dinerarias\admliq\unGeneracionIntereses.pas' {frmGeneracionIntereses},
  unGeneracionOPagos in '..\dinerarias\admliq\unGeneracionOPagos.pas' {frmGeneracionOPagos},
  unRPTPagoAdic in '..\dinerarias\reports\unRPTPagoAdic.pas' {qrPagoAdic: TQuickRep},
  unRptLiqReciboPagoUnico in '..\dinerarias\reports\unRptLiqReciboPagoUnico.pas' {frmRptReciboPagoUnico},
  unrptliq53 in '..\dinerarias\reports\unrptliq53.pas' {Rpt531: TQuickRep},
  unrptliq53b in '..\dinerarias\reports\unrptliq53b.pas' {rpt532: TQuickRep},
  unrptliq8 in '..\dinerarias\reports\unrptliq8.pas' {Rpt81: TQuickRep},
  unrptliq8b in '..\dinerarias\reports\unrptliq8b.pas' {rpt82: TQuickRep},
  unrptliq8Rep in '..\dinerarias\reports\unrptliq8Rep.pas' {Rpt8Rep: TQuickRep},
  unrptliq8repb in '..\dinerarias\reports\unrptliq8repb.pas' {rpt8rep2: TQuickRep},
  unDinerarias in '..\dinerarias\unDinerarias.pas',
  unRptNotaBase in 'reports\unRptNotaBase.pas' {qrNotaBase: TQuickRep},
  unGeneracionTasaJusticia in '..\dinerarias\admliq\unGeneracionTasaJusticia.pas' {frmGeneracionTasaJusticia},
  UnRptMoldeCarta in '..\comunes\reports\UnRptMoldeCarta.pas' {qrMoldeCarta: TQuickRep},
  unRptSiniestralidad in 'reports\unRptSiniestralidad.pas' {qrSiniestralidad: TQuickRep},
  unFiltroRptSiniestralidad in 'unFiltroRptSiniestralidad.pas' {frmFiltroRptSiniestralidad},
  OneSession in '..\..\comunes\OneSession.pas',
  unRptSiniestroParaRecalificar in 'reports\unRptSiniestroParaRecalificar.pas' {qrSiniestroParaRecalificar: TQuickRep},
  unRptFormularioCotizacionTot in '..\dinerarias\reports\unRptFormularioCotizacionTot.pas' {rptFormularioCotizacionTot: TQuickRep},
  unRptReciboRetiraDocum in '..\dinerarias\reports\unRptReciboRetiraDocum.pas' {rptReciboRetiraDocum: TQuickRep},
  unAgenda in '..\..\comunes\interfaces\unAgenda.pas',
  unfraContactoAGENDA in '..\comunes\frames\modulosAgenda\unfraContactoAGENDA.pas' {fraContactoAGENDA: TFrame},
  unfraContactoLibreAGENDA in '..\comunes\frames\modulosAgenda\unfraContactoLibreAGENDA.pas' {fraContactoLibreAGENDA: TFrame},
  unfraDomicilioAGENDA in '..\comunes\frames\modulosAgenda\unfraDomicilioAGENDA.pas' {fraDomicilioGISAGENDA: TFrame},
  unfraDomicilioEmpresaAGENDA in '..\comunes\frames\modulosAgenda\unfraDomicilioEmpresaAGENDA.pas' {fraDomicilioEmpresaAGENDA: TFrame},
  unfraDomicilioEstablecimientoAGENDA in '..\comunes\frames\modulosAgenda\unfraDomicilioEstablecimientoAGENDA.pas' {fraDomicilioEstablecimientoAGENDA: TFrame},
  unfraEmpresaAGENDA in '..\comunes\frames\modulosAgenda\unfraEmpresaAGENDA.pas' {fraEmpresaAGENDA: TFrame},
  unfraEntidadAGENDA in '..\comunes\frames\modulosAgenda\unfraEntidadAGENDA.pas' {fraEntidadAGENDA: TFrame},
  unfraEntidadVendedorAGENDA in '..\comunes\frames\modulosAgenda\unfraEntidadVendedorAGENDA.pas' {fraEntidadVendedorAGENDA: TFrame},
  unfraVendedorAGENDA in '..\comunes\frames\modulosAgenda\unfraVendedorAGENDA.pas' {fraVendedorAGENDA: TFrame},
  unfraTrabajadorSiniestroAGENDA in '..\comunes\frames\modulosAgenda\unfraTrabajadorSiniestroAGENDA.pas' {fraTrabajadorSiniestroAGENDA: TFrame},
  unfraTrabajadorAGENDA in '..\comunes\frames\modulosAgenda\unfraTrabajadorAGENDA.pas' {fraTrabajadorAGENDA: TFrame},
  unfraPrestadorAGENDA in '..\comunes\frames\modulosAgenda\unfraPrestadorAGENDA.pas' {fraPrestadorAGENDA: TFrame},
  unfraNumAutoAGENDA in '..\comunes\frames\modulosAgenda\unfraNumAutoAGENDA.pas' {fraNumAutoAGENDA: TFrame},
  unfraEstablecimientoAGENDA in '..\comunes\frames\modulosAgenda\unfraEstablecimientoAGENDA.pas' {fraEstablecimientoAGENDA: TFrame},
  unFraTitulo in '..\comunes\frames\nuevos\unFraTitulo.pas' {fraTitulo: TFrame},
  unAgendaCargaConsulta in '..\comunes\forms\unAgendaCargaConsulta.pas' {frmAgendaCargaConsulta},
  unFraUsuarioConSectorIntranet in '..\comunes\frames\new\unFraUsuarioConSectorIntranet.pas' {fraUsuarioConSectorIntranet: TFrame},
  unFraUsuarioConJerarquias in '..\comunes\frames\new\unFraUsuarioConJerarquias.pas' {fraUsuarioConJerarquias: TFrame},
  unFraValidacionDatosEmpresa in '..\comunes\frames\new\unFraValidacionDatosEmpresa.pas' {fraValidacionDatosEmpresa: TFrame},
  unArbolSectores in '..\usuarios\unArbolSectores.pas' {frmArbolSectores},
  unAyuda in '..\comunes\unAyuda.pas' {frmAyuda},
  unSeleccionTareas in '..\comunes\forms\unSeleccionTareas.pas' {frmSeleccionTareas},
  unABMAgendaBase in '..\comunes\forms\unABMAgendaBase.pas' {frmABMAgendaBase},
  unABMAgendaBaseEvento in '..\comunes\forms\unABMAgendaBaseEvento.pas' {frmABMAgendaBaseEvento},
  unABMAgendaBaseTarea in '..\comunes\forms\unABMAgendaBaseTarea.pas' {frmABMAgendaBaseTarea},
  unSeleccionResponsableHYS in '..\hys\unSeleccionResponsableHYS.pas' {frmSeleccionResponsableHYS: TFSForm},
  unInterfaces in '..\..\comunes\interfaces\unInterfaces.pas',
  unVisor in '..\comunes\forms\unVisor.pas' {frmVisor},
  unArchivoVisor in '..\comunes\unArchivoVisor.pas',
  unVisorExcel in '..\comunes\forms\unVisorExcel.pas' {frmVisorExcel},
  unFraCanal in '..\comunes\frames\new\unFraCanal.pas' {fraCanal: TFrame},
  unfraProspectosAGENDA in '..\comunes\frames\modulosagenda\unfraProspectosAGENDA.pas' {fraProspectosAGENDA: TFrame},
  unManSET_ESTABLECIMIENTO_TEMPORAL in 'unManSET_ESTABLECIMIENTO_TEMPORAL.pas' {frmManSET_ESTABLECIMIENTO_TEMPORAL: TFSForm},
  unfraArchJuicio in '..\archivo_new\frames\unfraArchJuicio.pas' {fraArchJuicio: TFrame},
  unfraProveedor in '..\comunes\frames\new\unfraProveedor.pas' {fraProveedor: TFrame},
  unCapturarCodigoBarras in '..\comunes\unCapturarCodigoBarras.pas' {frmCapturarCodigoBarras},
  unFraFiltroArchivo in '..\archivo_new\frames\unFraFiltroArchivo.pas' {fraFiltroArchivo: TFrame},
  unComisiones in '..\afiliaciones\comisiones\unComisiones.pas',
  unQrEtiquetasDocCarpetas in '..\archivo_new\unQrEtiquetasDocCarpetas.pas' {qrEtiquetasDocCarpetas: TQuickRep},
  unRptPlantillaRGRL in '..\comunes\reports\unRptPlantillaRGRL.pas' {qrPlantillaRGRL: TQuickRep},
  unControlVersion in '..\..\comunes\unControlVersion.pas',
  unfraVistaEventos in '..\comunes\frames\modulosagenda\unfraVistaEventos.pas' {fraVistaEventos: TFrame},
  unRptResumenILT in '..\dinerarias\reports\unRptResumenILT.pas' {qrResumenILT: TQuickRep},
  unAgendaVistaEmpresa in '..\comunes\forms\unAgendaVistaEmpresa.pas' {frmAgendaVistaEmpresa},
  unRptRemuneraciones in '..\dinerarias\reports\unRptRemuneraciones.pas' {qrRemuneraciones: TQuickRep},
  unListDenunciasGraves in 'unListDenunciasGraves.pas' {frmListDenunciasGraves: TFSForm},
  unRptCeseDeILT in '..\redpres\reports\unRptCeseDeILT.pas' {rptCeseDeILT: TQuickRep},
  unfraPrestador in '..\comunes\frames\unfraPrestador.pas' {fraPrestador: TFrame},
  unRptNotaDenunciaGrave in 'reports\unRptNotaDenunciaGrave.pas' {qrNotaDenunciaGrave: TQuickRep},
  PDFFuncs in '..\..\comunes\PDFFuncs.pas',
  unCargaDocumentosDigitaliz in '..\comunes\forms\unCargaDocumentosDigitaliz.pas' {frmCargaDocumentosDigitaliz},
  ProcFuncs in '..\..\comunes\ProcFuncs.pas',
  unArchivo in '..\archivo_new\unArchivo.pas',
  unFrmConsultaCarpetas in '..\archivo_new\unFrmConsultaCarpetas.pas' {FrmConsultaCarpetas: TFSForm},
  unFrmSolicitudCarpeta in '..\archivo_new\unFrmSolicitudCarpeta.pas' {FrmSolicitudCarpeta: TFSForm},
  unQrEtiquetasCarpetas in '..\archivo_new\unQrEtiquetasCarpetas.pas' {qrEtiquetasCarpetas: TQuickRep},
  unFraDetalleArchivo in '..\archivo_new\frames\unFraDetalleArchivo.pas' {fraDetalleArchivo: TFrame},
  unFrmDetalleArchivo in '..\archivo_new\unFrmDetalleArchivo.pas' {FrmDetalleArchivo},
  unMovimientoCarpetas in '..\archivo_new\unMovimientoCarpetas.pas' {frmMovimientoCarpetas},
  unFrmCargaDocumentacion in '..\archivo_new\unFrmCargaDocumentacion.pas' {frmCargaDocumentacion},
  unQrDetalleLoteEstudio in '..\archivo_new\unQrDetalleLoteEstudio.pas' {QrDetalleLoteEstudio},
  unReemplazoCarpetas in '..\archivo_new\unReemplazoCarpetas.pas' {frmReemplazoCarpetas},
  unfrmUbicacionActual in '..\archivo_new\unfrmUbicacionActual.pas' {FrmUbicacionActual},
  unRTTI in '..\..\comunes\unRTTI.pas',
  unTesoreria in '..\afiliaciones\tesoreria\unTesoreria.pas',
  unRptCitacionPresidencia in 'reports\unRptCitacionPresidencia.pas' {qrCitacionPresidencia: TQuickRep},
  unfraEmpresaSolicitudAGENDA in '..\comunes\frames\modulosagenda\unfraEmpresaSolicitudAGENDA.pas' {fraEmpresaSolicitudAGENDA: TFrame},
  unQrDetalleRemitoDevolucion in '..\archivo_new\unQrDetalleRemitoDevolucion.pas' {QrDetalleRemitoDevolucion},
  unfraFirmante in '..\comunes\frames\unfraFirmante.pas' {fraFirmante: TFrame},
  unManCVS_VENTANILLA_SUBTEMAS in '..\comunes\forms\unManCVS_VENTANILLA_SUBTEMAS.pas' {frmManCVS_VENTANILLA_SUBTEMAS: TFSForm},
  unfraDatoFechaAGENDA in '..\comunes\frames\modulosagenda\unfraDatoFechaAGENDA.pas' {fraDatoFecha: TFrame},
  unSIC in '..\..\comunes\unSIC.pas',
  unMensajeAlerta in '..\..\comunes\unMensajeAlerta.pas',
  unFrmArmadoLote in '..\archivo_new\unFrmArmadoLote.pas' {FrmArmadoLote: TFSForm},
  unQrDetalleLote in '..\archivo_new\unQrDetalleLote.pas' {QrDetalleLote},
  unRptResumenLotes in '..\archivo_new\unRptResumenLotes.pas' {qrResumenLotes: TQuickRep},
  unVerImagenes in '..\archivo_new\unVerImagenes.pas' {frmVerImagenes},
  unMensajeAlertaAGA in '..\archivo_new\unMensajeAlertaAGA.pas',
  unFraGIS_APIv3 in '..\comunes\frames\new\unFraGIS_APIv3.pas' {fraGIS_APIv3: TFrame},
  unGIS in '..\..\comunes\unGIS.pas',
  unFraWebBrowser in '..\comunes\frames\new\unFraWebBrowser.pas' {fraWebBrowser: TFrame},
  unEsperaSimple in '..\comunes\forms\unEsperaSimple.pas' {frmEsperaSimple},
  unSeleccionarCarpetaSRT in '..\afiliaciones\unSeleccionarCarpetaSRT.pas' {frmSeleccionarCarpetaSRT},
  unEnvioSMS in '..\comunes\forms\unEnvioSMS.pas' {frmEnvioSMS},
  unSMS in '..\..\comunes\unSMS.pas',
  unDireccionCDO in '..\dinerarias\unDireccionCDO.pas' {frmDireccionCDO},
  unRptRemitoCartas in '..\redpres\reports\unRptRemitoCartas.pas' {qrRemitoCartas: TQuickRep},
  unJustificacionILT in 'unJustificacionILT.pas' {frmJustificacionILT},
  unRptPedidoDocum in 'reports\unRptPedidoDocum.pas' {frmPedidoDocum},
  unImportCryptoSrt in '..\..\comunes\unImportCryptoSrt.pas',
  unRptNotaReqCarDef in 'reports\unRptNotaReqCarDef.pas' {rptNotaReqCarDef},
  unRptAntecedentesLabYMed in 'reports\unRptAntecedentesLabYMed.pas' {frmRptAntecedentesLabYMed},
  unRptReciboILPPerDef in '..\dinerarias\reports\unRptReciboILPPerDef.pas' {qrReciboILPPerDef: TQuickRep},
  unSeleccionarFechaFinTrat in 'unSeleccionarFechaFinTrat.pas' {frmSeleccionarFechaFinTrat},
  unFraTipoRegimen in '..\comunes\frames\new\unFraTipoRegimen.pas' {fraTipoRegimen: TFrame},
  unSiniestrosNoAutorizados in '..\dinerarias\unSiniestrosNoAutorizados.pas' {frmSiniestrosNoAutorizados: TFSForm},
  unWSTramitesMedicos in '..\comunes\unWSTramitesMedicos.pas',
  unAvisosDiarios in 'unAvisosDiarios.pas' {frmAvisosDiarios: TFSForm},
  unManUsuariosDeAvisos in 'unManUsuariosDeAvisos.pas' {frmManUsuariosDeAvisos: TFSForm},
  unCasosMortales in 'unCasosMortales.pas' {frmCasosMortales: TFSForm},
  unManUsuariosCasosMortales in 'unManUsuariosCasosMortales.pas' {frmUsuariosCasosMortales: TFSForm},
  unRptPlanillaMortales in 'reports\unRptPlanillaMortales.pas' {rptPlanillaMortales},
  unRptPlanillaMortalesPostFAcc in 'reports\unRptPlanillaMortalesPostFAcc.pas' {rptPlanillaMortalesPostFAcc},
  unConsultaTIFF in '..\dinerarias\unConsultaTIFF.pas' {frmConsultaTIFF},
  unSituacionDocumental in 'unSituacionDocumental.pas' {frmDocumentacion: TFSForm},
  unDocumentacion in '..\comunes\forms\unDocumentacion.pas' {frmDocumentacion: TFSForm},
  unRemitoDocumentacion in '..\comunes\forms\unRemitoDocumentacion.pas' {frmRemitoDocumentacion},
  unHistoricoDocumentacion in '..\comunes\forms\unHistoricoDocumentacion.pas' {frmHistoricoDocumentacion: TFSForm},
  unLstRemitosnoRecepcionados in '..\comunes\reports\unLstRemitosnoRecepcionados.pas' {frmLstRemitosnoRecepcionados},
  unAuditoriaILT in '..\comunes\forms\unAuditoriaILT.pas' {frmAuditoriaILT: TFSForm},
  unChat in '..\comunes\unChat.pas' {frmChat},
  unEnviosVentanillaElectronica in '..\comunes\forms\unEnviosVentanillaElectronica.pas' {frmEnviosVentanillaElectronica: TFSForm};

{$R *.RES}

begin
  OnlyOneInstance;
  Application.Initialize;
  Application.Title := 'Siniestros';

  with TfrmWelcomeSplash.Create(Application) do
  try
    ShowOnTop;
    Application.CreateForm(TdmFinancials, dmFinancials);
    Application.CreateForm(TdmPrincipal, dmPrincipal);
  if dmPrincipal.sdbPrincipal.Connected then
    begin
      OnlyOneSession;
      Application.CreateForm(TfrmPrincipal, frmPrincipal);
    end;
  finally
    Free;
  end;

  MostrarNovedades;
  Application.Run;
end.
