program Integrador;

uses
  OneInstance,
  Forms,
  Controls,
  Windows,
  unArt in '..\..\Comunes\unArt.pas',
  unCustomDataModule in '..\Comunes\unCustomDataModule.pas' {dmCustomDataModule: TDataModule},
  unDmPrincipal in '..\Comunes\ORACLE\unDmPrincipal.pas' {dmPrincipal: TDataModule},
  unCustomPrincipal in '..\comunes\reposit\unCustomPrincipal.pas' {frmCustomPrincipal},
  unArtFrame in '..\Comunes\REPOSIT\unArtFrame.pas' {ArtFrame: TFrame},
  unArtDBAwareFrame in '..\Comunes\REPOSIT\unArtDBAwareFrame.pas' {ArtDBAwareFrame: TFrame},
  unFraCodigoDescripcion in '..\Comunes\FRAMES\unFraCodigoDescripcion.pas' {fraCodigoDescripcion: TFrame},
  unFraCtbTablas in '..\Comunes\FRAMES\unFraCtbTablas.pas' {fraCtbTablas: TFrame},
  unArtDbFrame in '..\Comunes\REPOSIT\unArtDbFrame.pas' {ArtDbFrame: TFrame},
  unFraEmpresa in '..\Comunes\FRAMES\NEW\unFraEmpresa.pas' {fraEmpresa: TFrame},
  unFraEmpresaAfi in '..\Comunes\FRAMES\NEW\unFraEmpresaAfi.pas' {fraEmpresaAfi: TFrame},
  unFraEmpresaSolicitud in '..\Comunes\FRAMES\NEW\unFraEmpresaSolicitud.pas' {fraEmpresaSolicitud: TFrame},
  unCustomConsulta in '..\Comunes\REPOSIT\unCustomConsulta.pas' {frmCustomConsulta},
  unCustomPanelABM in '..\Comunes\REPOSIT\unCustomPanelABM.pas' {frmCustomPanelABM},
  unCustomGridABM in '..\Comunes\REPOSIT\unCustomGridABM.pas' {frmCustomGridABM},
  unAdmSiniestros in '..\Siniestros\unAdmSiniestros.pas' {frmAdmSiniestros},
  unFraTrabajador in '..\Comunes\FRAMES\NEW\unFraTrabajador.pas' {fraTrabajador: TFrame},
  unFraTrabajadorSiniestro in '..\Comunes\FRAMES\NEW\unFraTrabajadorSiniestro.pas' {fraTrabajadorSiniestro: TFrame},
  unDenunciaGrave in '..\Siniestros\ADMSIN\unDenunciaGrave.pas' {frmDenunciaGrave},
  unfraCPR_PRESTADOR in '..\Comunes\FRAMES\NEW\unfraCPR_PRESTADOR.pas' {fraCPR_PRESTADOR: TFrame},
  unFraStaticCodigoDescripcion in '..\Comunes\FRAMES\unFraStaticCodigoDescripcion.pas' {fraStaticCodigoDescripcion: TFrame},
  unFraStaticCTB_TABLAS in '..\Comunes\FRAMES\unFraStaticCTB_TABLAS.pas' {fraStaticCTB_TABLAS: TFrame},
  unParteEvolutivo in '..\Siniestros\ADMSIN\unParteEvolutivo.pas' {frmParteEvolutivo},
  unSinForm in '..\Siniestros\ADMSIN\unSinForm.pas' {SinForm},
  unSinFormNavigator in '..\Siniestros\ADMSIN\unSinFormNavigator.pas' {SinFormNavigator},
  unFraDomicilio in '..\Comunes\FRAMES\NEW\unFraDomicilio.pas' {fraDomicilio: TFrame},
  unFraDomicilioTrab in '..\Comunes\FRAMES\NEW\unFraDomicilioTrab.pas' {fraDomicilioTrab: TFrame},
  unFraEstablecimiento in '..\Comunes\FRAMES\NEW\unFraEstablecimiento.pas' {fraEstablecimiento: TFrame},
  unBusquedaDomicilio in '..\Comunes\Forms\unBusquedaDomicilio.pas' {frmBusquedaDomicilio},
  unAfiliaciones in '..\Afiliaciones\unAfiliaciones.pas',
  unManCCP_CUENTAPAGO in '..\Comunes\Forms\unManCCP_CUENTAPAGO.pas' {frmManCCP_CUENTAPAGO},
  unfraVendedores in '..\Comunes\FRAMES\unfraVendedores.pas' {fraVendedores: TFrame},
  unfraVendedoresCUIT in '..\Comunes\FRAMES\NEW\unfraVendedoresCUIT.pas' {fraVendedoresCUIT: TFrame},
  unAltaModifCCP_CUENTAPAGO in '..\Comunes\Forms\unAltaModifCCP_CUENTAPAGO.pas' {frmAltaModifCCP_CUENTAPAGO},
  unConsulta in '..\Comunes\Forms\unConsulta.pas' {frmConsulta},
  unSiniestros in '..\Siniestros\unSiniestros.pas',
  unFraSAU_AUTORIZACIONES in '..\Siniestros\FRAMES\unFraSAU_AUTORIZACIONES.pas' {fraSAU_AUTORIZACIONES: TFrame},
  unFraSDA_DETALLEARCHIVO in '..\Comunes\FRAMES\unFraSDA_DETALLEARCHIVO.pas' {fraSDA_DETALLEARCHIVO: TFrame},
  unCustomSplash in '..\Comunes\REPOSIT\unCustomSplash.pas' {frmCustomSplash},
  unWelcomeSplash in '..\Comunes\Forms\unWelcomeSplash.pas' {frmWelcomeSplash},
  unExpediente in '..\Siniestros\ADMSIN\unExpediente.pas' {frmExpediente},
  unFraCIE10 in '..\Comunes\FRAMES\unFraCIE10.pas' {fraCIE10: TFrame},
  VCLExtra in '..\..\Comunes\VCLExtra.pas',
  AnsiSql in '..\..\Comunes\AnsiSql.pas',
  DbFuncs in '..\..\Comunes\DbFuncs.pas',
  unSesion in '..\..\Comunes\unSesion.pas',
  CustomDlgs in '..\..\Comunes\CustomDlgs.pas',
  unDebug in '..\comunes\unDebug.pas' {frmDebug},
  unMoldeEnvioMail in '..\comunes\envio de mails\unMoldeEnvioMail.pas',
  unCustomForm in '..\comunes\unCustomForm.pas' {frmCustomForm},
  unFraToolbarRTF in '..\comunes\frames\unFraToolbarRTF.pas' {fraToolbarRTF: TFrame},
  unSeleccionDestinatarios in '..\comunes\unSeleccionDestinatarios.pas' {frmSeleccionDestinatarios: TFSForm},
  unLibretaDeDirecciones in '..\comunes\forms\unLibretaDeDirecciones.pas' {frmLibretaDeDirecciones: TFSForm},
  unElementosEnviados in '..\comunes\forms\unElementosEnviados.pas' {frmElementosEnviados: TFSForm},
  General in '..\..\Comunes\General.pas',
  unfraCuentaBancaria in '..\comunes\frames\new\unfraCuentaBancaria.pas' {fraCuentaBancaria: TFrame},
  unfraUsuarios in '..\comunes\frames\unfraUsuarios.pas' {fraUsuario: TFrame},
  unFraUsuario in '..\comunes\frames\new\unFraUsuario.pas' {fraUsuarios: TFrame},
  unParteIngreso in '..\Siniestros\ADMSIN\unParteIngreso.pas' {frmParteIngreso: TFSForm},
  unParteEgreso in '..\Siniestros\ADMSIN\unParteEgreso.pas' {frmParteEgreso: TFSForm},
  unFraSMC_MOTIVONOCARGA in '..\Siniestros\FRAMES\unFraSMC_MOTIVONOCARGA.pas' {fraSMC_MOTIVONOCARGA: TFrame},
  unFraSTA_TIPOACCIDENTE in '..\Siniestros\FRAMES\unFraSTA_TIPOACCIDENTE.pas' {fraSTA_TIPOACCIDENTE: TFrame},
  unFraSTC_TIPOGRAVEDAD_CIE10 in '..\Siniestros\FRAMES\unFraSTC_TIPOGRAVEDAD_CIE10.pas' {fraSTC_TIPOGRAVEDAD_CIE10: TFrame},
  unFraStaticCodDesc in '..\comunes\frames\nuevos\unFraStaticCodDesc.pas' {fraStaticCodDesc: TFrame},
  unFraCodDesc in '..\comunes\frames\nuevos\unFraCodDesc.pas' {fraCodDesc: TFrame},
  unFraSTG_TIPOGRAVEDAD in '..\Siniestros\FRAMES\unFraSTG_TIPOGRAVEDAD.pas' {fraSTG_TIPOGRAVEDAD: TFrame},
  unFraSLA_LESIONAGENTE in '..\Siniestros\FRAMES\unFraSLA_LESIONAGENTE.pas' {fraSLA_LESIONAGENTE: TFrame},
  unFraSLF_LESIONFORMA in '..\Siniestros\FRAMES\unFraSLF_LESIONFORMA.pas' {fraSLF_LESIONFORMA: TFrame},
  unFraSLN_LESIONNATURALEZA in '..\Siniestros\FRAMES\unFraSLN_LESIONNATURALEZA.pas' {fraSLN_LESIONNATURALEZA: TFrame},
  unFraSLZ_LESIONZONA in '..\Siniestros\FRAMES\unFraSLZ_LESIONZONA.pas' {fraSLZ_LESIONZONA: TFrame},
  unEspera in '..\comunes\forms\unEspera.pas' {frmEspera},
  unCITRIX in '..\..\Comunes\unCITRIX.pas',
  unFraCDG_DIAGNOSTICO in '..\Siniestros\FRAMES\unFraCDG_DIAGNOSTICO.pas' {fraCDG_DIAGNOSTICO: TFrame},
  unFraCCI_CIUO in '..\Siniestros\FRAMES\unFraCCI_CIUO.pas' {fraCCI_CIUO: TFrame},
  unResumen in '..\Siniestros\ADMSIN\unResumen.pas' {frmResumen: TFSForm},
  unOtros in '..\Siniestros\ADMSIN\unOtros.pas' {frmOtros: TFSForm},
  unParteAuditoria in '..\Siniestros\ADMSIN\unParteAuditoria.pas' {frmParteAuditoria: TFSForm},
  DateTimeFuncs in '..\..\Comunes\DateTimeFuncs.pas',
  unDlgBusEstablecimiento in '..\Siniestros\unDlgBusEstablecimiento.pas' {frmDlgBusEstablecimiento: TFSForm},
  unFraTelefono in '..\comunes\frames\new\unFraTelefono.pas' {fraTelefono: TFrame},
  unABMTelefonos in '..\comunes\forms\unABMTelefonos.pas' {frmTelefonos},
  unTelefonosCargaRapida in '..\comunes\forms\unTelefonosCargaRapida.pas' {frmTelefonosCargaRapida},
  unCompatibilidad in '..\afiliaciones\unCompatibilidad.pas',
  uncomunes in '..\..\comunes\uncomunes.pas',
  unFraTipoSiniestro in '..\Siniestros\FRAMES\unFraTipoSiniestro.pas' {fraTipoSiniestro: TFrame},
  unFraCPA_PAISES in '..\comunes\frames\new\unFraCPA_PAISES.pas' {fraCPA_PAISES: TFrame},
  unIncapacidadesPermanentes in '..\Siniestros\unIncapacidadesPermanentes.pas' {frmIncapacidadesPermanentes},
  unRedPres in '..\..\Comunes\unRedPres.pas',
  unAlarmas in '..\..\Comunes\unAlarmas.pas',
  Cuit in '..\..\Comunes\Cuit.pas',
  strfuncs in '..\..\Comunes\strfuncs.pas',
  unEnvioMail in '..\..\Comunes\unEnvioMail.pas',
  unFraTipoEgreso in '..\Siniestros\FRAMES\unFraTipoEgreso.pas' {fraTipoEgreso: TFrame},
  unFraTipoTratamiento in '..\Siniestros\FRAMES\unFraTipoTratamiento.pas' {fraTipoTratamiento: TFrame},
  unVisualizador in '..\comunes\unVisualizador.pas' {frmVisualizador},
  unFraTipoAtencion in '..\Siniestros\FRAMES\unFraTipoAtencion.pas' {fraTipoAtencion: TFrame},
  unFraMAU_AUDITORES in '..\Siniestros\FRAMES\unFraMAU_AUDITORES.pas' {fraMAU_AUDITORES: TFrame},
  unFraMIM_IMPLANTES in '..\Siniestros\FRAMES\unFraMIM_IMPLANTES.pas' {fraMIM_IMPLANTES: TFrame},
  unFraDomicilioTrabajador in '..\comunes\frames\new\unFraDomicilioTrabajador.pas' {fraDomicilioTrabajador: TFrame},
  unfraDelegacion in '..\comunes\frames\unfraDelegacion.pas' {fraDelegacion: TFrame},
  unCambioDelegacion in '..\Siniestros\unCambioDelegacion.pas' {frmCambioDelegacion},
  unfraSectores in '..\comunes\frames\unfraSectores.pas' {fraSectores: TFrame},
  unEvolucionDeEstados in '..\Siniestros\unEvolucionDeEstados.pas' {frmEvolucionDeEstados},
  unContratoContacto in '..\comunes\forms\unContratoContacto.pas' {frmContratoContacto},
  unfraContacto in '..\comunes\frames\unfraContacto.pas' {fraContacto: TFrame},
  SpoolFuncs in '..\..\Comunes\SpoolFuncs.pas',
  unFraPrestadorExtendido in '..\comunes\frames\new\unFraPrestadorExtendido.pas' {fraPrestadorExtendido: TFrame},
  unFraPrestadorFueraDeContrato in '..\comunes\frames\new\unFraPrestadorFueraDeContrato.pas' {fraPrestadorFueraDeContrato: TFrame},
  unConsultaNomina in '..\Siniestros\unConsultaNomina.pas' {frmConsultaNomina: TFSForm},
  unConsultaEmpresa in '..\Siniestros\unConsultaEmpresa.pas' {frmConsultaEmpresa: TFSForm},
  unConfidencial in '..\..\Comunes\unConfidencial.pas',
  unFraRTD_TIPODOCUMENTO in '..\comunes\frames\new\unFraRTD_TIPODOCUMENTO.pas' {fraRTD_TIPODOCUMENTO: TFrame},
  unVisualizadorDigitalizacion in '..\comunes\forms\unVisualizadorDigitalizacion.pas' {frmVisualizadorDigitalizacion: TFSForm},
  unFraVistaTIFF in '..\comunes\frames\new\unFraVistaTIFF.pas' {fraVistaTIFF: TFrame},
  libgfl in '..\..\Comunes\libgfl.pas',
  unFraDigitalizacion in '..\comunes\frames\new\unFraDigitalizacion.pas' {fraDigitalizacion: TFrame},
  ungrids in '..\..\Comunes\ungrids.pas',
  unFaxEnviados in '..\comunes\forms\unFaxEnviados.pas' {frmFaxEnviados: TFSForm},
  unConsFax in '..\Comunes\Forms\unConsFax.pas' {frmConsFax: TFSForm},
  unfraFFO_FAXFORMULARIO in '..\fax\faxclient_new\frames\unfraFFO_FAXFORMULARIO.pas' {fraFFO_FAXFORMULARIO: TFrame},
  unEstrategiaTIFF in '..\fax\faxclient_new\unEstrategiaTIFF.pas',
  unImageFunctions in '..\..\Comunes\unImageFunctions.pas',
  unFaxFuncs in '..\..\Comunes\unFaxFuncs.pas',
  unUbicacionDenuncia in '..\Siniestros\unUbicacionDenuncia.pas' {frmUbicacionDenuncia},
  unFraCCO_PARTIDOS_CODIGOSPOSTALES in '..\Siniestros\FRAMES\unFraCCO_PARTIDOS_CODIGOSPOSTALES.pas' {fraCCO_PARTIDOS_CODIGOSPOSTALES: TFrame},
  unRptResumen in '..\Siniestros\REPORTS\unRptResumen.pas' {rptResumen: TQuickRep},
  unManRDO_DOCUMENTO in '..\archivo_new\abm\unManRDO_DOCUMENTO.pas' {frmManRDO_DOCUMENTO: TFSForm},
  unExportPDF in '..\..\Comunes\unExportPDF.pas',
  unIntegrador in 'unIntegrador.pas' {frmIntegrador},
  unfraInfoEmpresa in '..\comunes\frames\new\unfraInfoEmpresa.pas' {fraInfoEmpresa: TFrame},
  unConsultasAdicionales in '..\comunes\forms\unConsultasAdicionales.pas' {frmConsultasAdicionales},
  unOpcionesDeImpresion in '..\cobranzas\unOpcionesDeImpresion.pas' {frmOpcionesDeImpresion},
  unBaseAdministracionCartas in '..\comunes\forms\unBaseAdministracionCartas.pas' {frmBaseAdministracionCartas: TFSForm},
  unRptCartaDocHeader in '..\comunes\reports\unRptCartaDocHeader.pas' {rptCartaDocHeader: TQuickRep},
  unRptCartaDocumento in '..\comunes\reports\unRptCartaDocumento.pas' {rptCartaDocumento: TQuickRep},
  unImpoExpoWizard in '..\impoexpo\unImpoExpoWizard.pas' {frmImpoExpoWizard},
  unQRCartaDocIntimacion in '..\cobranzas\reports\unQRCartaDocIntimacion.pas',
  unQRF817 in '..\cobranzas\reports\unQRF817.pas',
  unRptCartaDocCompensacion in '..\cobranzas\compensacion\reports\unRptCartaDocCompensacion.pas',
  unImpresionEstadoDeCuenta in '..\cobranzas\unImpresionEstadoDeCuenta.pas',
  unQrEstadoCuentaDetalle in '..\cobranzas\reports\unQrEstadoCuentaDetalle.pas' {frmEstadoCuentaDetalle},
  unQrEstadoCuentaResumen in '..\cobranzas\reports\unQrEstadoCuentaResumen.pas' {frmEstadoCuentaResumen},
  unQRF801C in '..\cobranzas\reports\unQRF801C.pas' {QRF801C: TQuickRep},
  unEjecutivoCuenta in '..\comunes\forms\unEjecutivoCuenta.pas' {frmEjecutivoCuenta},
  unGestorCuenta in '..\comunes\forms\unGestorCuenta.pas' {frmGestorCuenta},
  unFraCanal in '..\comunes\frames\new\unFraCanal.pas' {fraCanal: TFrame},
  unfraEntidadCUIT in '..\comunes\frames\new\unfraEntidadCUIT.pas' {fraEntidadCUIT: TFrame},
  unFraDomicilioExtendido in '..\comunes\frames\new\unFraDomicilioExtendido.pas' {fraDomicilioExtendido: TFrame},
  unFraABMFrame in '..\comunes\frames\nuevos\unFraABMFrame.pas' {ART_ABMFrame: TFrame},
  unFraABM_ACT_CONTACTO in '..\comunes\frames\new\unFraABM_ACT_CONTACTO.pas' {fraABM_ACT_CONTACTO: TFrame},
  unNominaPeriodos in '..\comunes\forms\unNominaPeriodos.pas' {frmNominaPeriodos: TFSForm},
  UnRptMoldeCarta in '..\comunes\reports\UnRptMoldeCarta.pas' {qrMoldeCarta: TQuickRep},
  unRptCartaConfirmacionAlicuota in 'unRptCartaConfirmacionAlicuota.pas' {qrCartaConfirmacionAlicuota: TQuickRep},
  unLiqIncapacidades in '..\Dinerarias\unLiqIncapacidades.pas' {frmLiqIncapacidades},
  unDmFinancials in '..\comunes\oracle\unDmFinancials.pas' {dmFinancials: TDataModule},
  unRptDDJJSinPresentar in 'unRptDDJJSinPresentar.pas' {qrDDJJSinPresentar: TQuickRep},
  unTercerizadoras in '..\..\Comunes\unTercerizadoras.pas',
  unEstadoCuenta in '..\cobranzas\unEstadoCuenta.pas',
  unPrincipal in 'unPrincipal.pas' {frmPrincipal},
  unEmisionCertificados in '..\afiliaciones\unEmisionCertificados.pas' {frmEmisionCertificados: TFSForm},
  UnRptCertificados in '..\afiliaciones\reports\UnRptCertificados.pas' {rptCertificados},
  unRptRepNom in '..\afiliaciones\reports\unRptRepNom.pas' {rptRepNom: TQuickRep},
  unFraEmpresaHolding in '..\comunes\frames\new\unFraEmpresaHolding.pas' {fraEmpresaHolding: TFrame},
  unABMAgenda in '..\licitaciones\unABMAgenda.pas' {frmABMAgenda: TFSForm},
  unConsultaLicitacion in '..\licitaciones\unConsultaLicitacion.pas' {frmConsultaLicitacion: TFSForm},
  unGestion in '..\licitaciones\unGestion.pas' {frmGestion},
  unRptLicitacion in '..\licitaciones\unRptLicitacion.pas' {rptLicitacion: TQuickRep},
  unVisualizaPliegos in '..\licitaciones\unVisualizaPliegos.pas' {frmVisualizaPliegos},
  unDenunciaStandard in '..\Siniestros\ADMSIN\unDenunciaStandard.pas' {frmDenunciaSTD: TFSForm},
  unAyuda in '..\comunes\unAyuda.pas' {frmAyuda},
  unImpoExpoUtils in '..\impoexpo\unImpoExpoUtils.pas',
  unFraSMD_MODODETECCION in '..\Siniestros\FRAMES\unFraSMD_MODODETECCION.pas' {fraSMD_MODODETECCION: TFrame},
  unFraSLM_LESIONAGENTEMATERIAL in '..\Siniestros\FRAMES\unFraSLM_LESIONAGENTEMATERIAL.pas' {fraSLM_LESIONAGENTEMATERIAL: TFrame},
  ArchFuncs in '..\..\Comunes\ArchFuncs.pas',
  unfraPrestador in '..\comunes\frames\unfraPrestador.pas' {fraPrestador: TFrame},
  unSegIncapacidades in '..\Siniestros\unSegIncapacidades.pas' {frmSegIncapacidades: TFSForm},
  unCuadroTarifarioContrato in '..\afiliaciones\unCuadroTarifarioContrato.pas' {frmContratoTarifa},
  unfraStaticActividad in '..\comunes\frames\unfraStaticActividad.pas' {fraStaticActividad: TFrame},
  unAfiGeneracionCartas in '..\afiliaciones\unAfiGeneracionCartas.pas' {frmAfiGeneracionCartas},
  unQRReporte in '..\afiliaciones\reports\unQRReporte.pas' {QRReporte: TQuickRep},
  unAfiCartasDoc in '..\afiliaciones\unAfiCartasDoc.pas',
  unQREndosoBase in '..\afiliaciones\reports\unQREndosoBase.pas' {qrEndosoBase: TQuickRep},
  unQREndoso1 in '..\afiliaciones\reports\unQREndoso1.pas' {qrEndoso1: TQuickRep},
  unQREndoso0 in '..\afiliaciones\reports\unQREndoso0.pas' {qrEndoso0: TQuickRep},
  unrptCartaDocTarifa in '..\afiliaciones\reports\unrptCartaDocTarifa.pas' {rptCartaDocTarifa: TQuickRep},
  unRptCartDocTraspasoEgreso2 in '..\afiliaciones\reports\unRptCartDocTraspasoEgreso2.pas' {rptCartDocTraspasoEgreso2: TQuickRep},
  unRptCartDocTraspasoEgreso in '..\afiliaciones\reports\unRptCartDocTraspasoEgreso.pas' {rptCartDocTraspasoEgreso: TQuickRep},
  unRptCartDocTraspasoIngreso in '..\afiliaciones\reports\unRptCartDocTraspasoIngreso.pas' {rptCartDocTraspasoIngreso: TQuickRep},
  unRptParteAuditoriaLeve in '..\Siniestros\REPORTS\unRptParteAuditoriaLeve.pas' {rptParteAuditoriaLeve: TQuickRep},
  unRptParteAuditoriaGrave in '..\Siniestros\REPORTS\unRptParteAuditoriaGrave.pas' {rptParteAuditoriaGrave: TQuickRep},
  unNovedades in '..\..\Comunes\unNovedades.pas',
  unRptNotaEntregaReq in '..\Siniestros\REPORTS\unRptNotaEntregaReq.pas' {qrNotaEntregaReq: TQuickRep},
  unRptNotaRectificatoria in '..\Siniestros\REPORTS\unRptNotaRectificatoria.pas' {qrNotaRectificatoria: TQuickRep},
  unConfirmaTarifa in '..\afiliaciones\unConfirmaTarifa.pas' {frmConfirmaTarifa: TFSForm},
  unAgendaTelefonica in '..\comunes\forms\unAgendaTelefonica.pas' {frmAgendaTelefonica: TFSForm},
  unRptParteEgreso in '..\siniestros\reports\unRptParteEgreso.pas' {rptParteEgreso: TQuickRep},
  unQrLibreDeuda in '..\cobranzas\reports\unQrLibreDeuda.pas' {qrLibreDeuda: TQuickRep},
  unQRCartaDocIntimacionNuevaGrilla in '..\cobranzas\reports\unQRCartaDocIntimacionNuevaGrilla.pas' {QRCartaDocIntimacionNuevaGrilla: TQuickRep},
  unRptIncapacidadRecibo in '..\dinerarias\reports\unRptIncapacidadRecibo.pas' {qrIncapacidadRecibo: TQuickRep},
  unRptNotaBaja in '..\siniestros\reports\unRptNotaBaja.pas' {qrNotaBaja: TQuickRep},
  unMotivoCancelacionLiq in '..\dinerarias\unMotivoCancelacionLiq.pas' {frmMotivoCancelacionLiq},
  unRptRemuneraciones in '..\dinerarias\reports\unRptRemuneraciones.pas' {qrRemuneraciones: TQuickRep},
  unRptReciboILT in '..\dinerarias\reports\unRptReciboILT.pas' {qrReciboILT: TQuickRep},
  unRptReciboILP in '..\dinerarias\reports\unRptReciboILP.pas' {qrReciboILP: TQuickRep},
  unRptOrdenDePago in '..\dinerarias\reports\unRptOrdenDePago.pas' {qrOrdenDePago: TQuickRep},
  unRptGestionDeReclamos in '..\comunes\reports\unRptGestionDeReclamos.pas' {frmRptGestionDeReclamos},
  unVentanillaElectronica in '..\comunes\forms\unVentanillaElectronica.pas' {frmVentanillaElectronica: TFSForm},
  unFormularioValidacionYRectificacionDatosEstablecimientos in '..\comunes\forms\unFormularioValidacionYRectificacionDatosEstablecimientos.pas' {frmFormularioValidacionYRectificacionDatosEstablecimientos},
  unRptFormularioValidacionYRectificacionDatosEstablecimientos in '..\comunes\reports\unRptFormularioValidacionYRectificacionDatosEstablecimientos.pas' {qrFormularioValidacionYRectificacionDatosEstablecimientos: TQuickRep},
  unDatosLesion in '..\siniestros\unDatosLesion.pas' {frmDatosLesion},
  unClassExpediente in '..\..\comunes\Clases\unClassExpediente.pas',
  unClassLiquidacion in '..\..\comunes\Clases\unClassLiquidacion.pas',
  unAnalisisCliente in '..\comunes\forms\unAnalisisCliente.pas' {frmAnalisisCliente},
  unDigitalizacion in '..\..\comunes\unDigitalizacion.pas',
  unExcel in '..\..\comunes\unExcel.pas',
  unFraNavegadorWEB in '..\comunes\frames\new\unFraNavegadorWEB.pas' {fraNavegadorWEB: TFrame},
  unGoogleMaps in '..\comunes\forms\unGoogleMaps.pas' {frmGoogleMaps},
  unFraDomicilioGIS in '..\comunes\frames\new\unFraDomicilioGIS.pas' {fraDomicilioGIS: TFrame},
  unManCGI_GIS in '..\comunes\forms\unManCGI_GIS.pas' {frmManCGI_GIS: TFSForm},
  unRptLiqOtrosConceptos in '..\siniestros\reports\unRptLiqOtrosConceptos.pas' {qrLiqOtrosConceptos: TQuickRep},
  unRptReciboOtrosConceptos in '..\siniestros\reports\unRptReciboOtrosConceptos.pas' {qrReciboOtrosConceptos: TQuickRep},
  OneSession in '..\..\comunes\OneSession.pas',
  unLiqAsigFam in '..\dinerarias\unLiqAsigFam.pas' {frmLiqAsigFam},
  unManAsigEspeciales in '..\dinerarias\ABM\unManAsigEspeciales.pas' {frmManAsigEspeciales},
  unManAsigHijos in '..\dinerarias\ABM\unManAsigHijos.pas' {frmManAsigHijos},
  unAnexoRes365 in '..\comunes\forms\unAnexoRes365.pas' {frmAnexoRes365},
  unRptAnexoRes365 in '..\comunes\reports\unRptAnexoRes365.pas' {qrAnexoRes365: TQuickRep},
  unRptEstudiosCompl in '..\siniestros\reports\unRptEstudiosCompl.pas' {qrEstudiosCompl: TQuickRep},
  unRptEstadisticasRGRL in '..\comunes\reports\unRptEstadisticasRGRL.pas' {qrEstadisticasRGRL: TQuickRep},
  unRptRGRL in '..\comunes\reports\unRptRGRL.pas' {qrRGRL: TQuickRep},
  unRGRL in '..\comunes\forms\unRGRL.pas' {frmRGRL},
  unCompaniaSeguroRetiro in '..\dinerarias\unCompaniaSeguroRetiro.pas' {frmCompaniaSeguroRetiro},
  unListContCartasDoc in '..\siniestros\unListContCartasDoc.pas' {frmListContCartasDoc: TFSForm},
  unRptRemitoExpedientes in '..\siniestros\reports\unRptRemitoExpedientes.pas' {qrRemitoExpedientes: TQuickRep},
  UnListConsPrest in '..\redpres\UnListConsPrest.pas' {frmConsPrest},
  unClasificacionActivos in '..\comunes\forms\unClasificacionActivos.pas' {frmClasificacionActivos: TFSForm},
  unManCPG_PLAZOGUARDA in '..\comunes\forms\unManCPG_PLAZOGUARDA.pas' {frmManCPG_PLAZOGUARDA: TFSForm},
  unManCTA_TIPOACTIVOS in '..\comunes\forms\unManCTA_TIPOACTIVOS.pas' {frmManCTA_TIPOACTIVOS: TFSForm},
  UnRepManPrestador in '..\redpres\UnRepManPrestador.pas' {rptManPrestador: TQuickRep},
  unFiltros in '..\..\comunes\unFiltros.pas',
  unfraMotivoEndoso in '..\comunes\frames\new\unfraMotivoEndoso.pas' {fraMotivoEndoso: TFrame},
  unUtilsArchivo in '..\archivo_new\unUtilsArchivo.pas',
  unfraCodigoDescripcionExt in '..\comunes\frames\unfraCodigoDescripcionExt.pas' {fraCodigoDescripcionExt: TFrame},
  unSeleccionMultiple in '..\comunes\forms\unSeleccionMultiple.pas' {frmSeleccionUsuarios: TFrame},
  unRptLegajoSiniestro in '..\siniestros\reports\unRptLegajoSiniestro.pas' {qrLegajoSiniestro: TQuickRep},
  unRptDenunciaStandardS in '..\siniestros\reports\unRptDenunciaStandardS.pas' {qrDenunciaStandardS: TQuickRep},
  unRptFormularioCotizacion in '..\dinerarias\reports\unRptFormularioCotizacion.pas' {rptFormularioCotizacion: TQuickRep},
  unRptFormSelRetiro in '..\comunes\reports\unRptFormSelRetiro.pas' {rptFormSelRetiro: TQuickRep},
  unRptSiniestroParaReingresar in '..\siniestros\reports\unRptSiniestroParaReingresar.pas' {qrSiniestroParaReingresar: TQuickRep},
  unClassEmpresa in '..\..\comunes\Clases\unClassEmpresa.pas',
  unRptResumenIncapacidad in '..\dinerarias\reports\unRptResumenIncapacidad.pas' {qrResumenIncapacidad: TQuickRep},
  unRptResumenILP in '..\dinerarias\reports\unRptResumenILP.pas' {qrResumenILP: TQuickRep},
  unGeneracionTasaJusticia in '..\dinerarias\admliq\unGeneracionTasaJusticia.pas' {frmGeneracionTasaJusticia},
  unDinerarias in '..\dinerarias\unDinerarias.pas',
  unRptParteIngreso in '..\siniestros\reports\unRptParteIngreso.pas' {qrParteIngreso: TQuickRep},
  unRptNotaBase in '..\siniestros\reports\unRptNotaBase.pas' {qrNotaBase: TQuickRep},
  unGeneracionOPagos in '..\dinerarias\admliq\unGeneracionOPagos.pas' {frmGeneracionOPagos},
  unGeneracionIntereses in '..\dinerarias\admliq\unGeneracionIntereses.pas' {frmGeneracionIntereses},
  unRPTPagoAdic in '..\dinerarias\reports\unRPTPagoAdic.pas' {qrPagoAdic: TQuickRep},
  unrptliq8 in '..\dinerarias\reports\unrptliq8.pas' {Rpt81: TQuickRep},
  unrptliq8b in '..\dinerarias\reports\unrptliq8b.pas' {rpt82: TQuickRep},
  unrptliq8Rep in '..\dinerarias\reports\unrptliq8Rep.pas' {Rpt8Rep: TQuickRep},
  unrptliq8repb in '..\dinerarias\reports\unrptliq8repb.pas' {rpt8rep2: TQuickRep},
  unrptliq53 in '..\dinerarias\reports\unrptliq53.pas' {Rpt531: TQuickRep},
  unrptliq53b in '..\dinerarias\reports\unrptliq53b.pas' {rpt532: TQuickRep},
  unRptLiqReciboPagoUnico in '..\dinerarias\reports\unRptLiqReciboPagoUnico.pas' {frmRptReciboPagoUnico},
  unRptSiniestroParaRecalificar in '..\siniestros\reports\unRptSiniestroParaRecalificar.pas' {qrSiniestroParaRecalificar: TQuickRep},
  unRptReciboRetiraDocum in '..\dinerarias\reports\unRptReciboRetiraDocum.pas' {rptReciboRetiraDocum: TQuickRep},
  unRptFormularioCotizacionTot in '..\dinerarias\reports\unRptFormularioCotizacionTot.pas' {rptFormularioCotizacionTot: TQuickRep},
  unManDEL_DELEGACION in '..\afiliaciones\abm\unManDEL_DELEGACION.pas' {frmManDEL_DELEGACION: TFSForm},
  unInformesSiniestralidad in '..\comunes\forms\unInformesSiniestralidad.pas' {frmInformesSiniestralidad},
  unInfSiniestralidad in '..\comunes\unInfSiniestralidad.pas',
  unVisor in '..\comunes\forms\unVisor.pas' {frmVisor},
  unVisorPDF in '..\comunes\forms\unVisorPDF.pas' {frmVisorPDF},
  unArchivoVisor in '..\comunes\unArchivoVisor.pas',
  unVisorExcel in '..\comunes\forms\unVisorExcel.pas' {frmVisorExcel},
  unRptEvolucion in '..\comunes\reports\unRptEvolucion.pas' {qrEvolucion: TQuickRep},
  unQrEtiquetasDocCarpetas in '..\archivo_new\unQrEtiquetasDocCarpetas.pas' {qrEtiquetasDocCarpetas: TQuickRep},
  unEmisionFormularios in '..\siniestros\unEmisionFormularios.pas' {frmEmisionFormularios},
  unRptHistSiniestral in '..\siniestros\reports\unRptHistSiniestral.pas' {qrHistSiniestral: TQuickRep},
  unRptSolicitudIntervencion in '..\siniestros\reports\unRptSolicitudIntervencion.pas' {frmRptSolInt},
  unRptSolicitudPedidos in '..\siniestros\reports\unRptSolicitudPedidos.pas' {qrSolicitudPedidos: TQuickRep},
  unRptActaAcuedo in '..\siniestros\reports\unRptActaAcuedo.pas' {qrActaAcuerdo: TQuickRep},
  unRptAcuerdoILPPD in '..\siniestros\reports\unRptAcuerdoILPPD.pas' {frmRptAcuerdoILPPD},
  unRptAltaMedica in '..\siniestros\reports\unRptAltaMedica.pas' {qrAltaMedica: TQuickRep},
  unRptInfCodInca in '..\siniestros\reports\unRptInfCodInca.pas' {qrInfCodInca: TQuickRep},
  unRptEvalPrestacJuntaMed in '..\siniestros\reports\unRptEvalPrestacJuntaMed.pas' {qrEvalPrestacJuntaMed: TQuickRep},
  unRptRevisionMedica in '..\siniestros\reports\unRptRevisionMedica.pas' {qrRevisionMedica: TQuickRep},
  unRptCartaAbandonoTto in '..\siniestros\reports\unRptCartaAbandonoTto.pas' {rptCartaAbandonoTto: TQuickRep},
  unRptDictamenFundMedicos in '..\siniestros\reports\unRptDictamenFundMedicos.pas' {qrDictamenFundMedicos: TQuickRep},
  unRptDocumentPrestDinerarias in '..\siniestros\reports\unRptDocumentPrestDinerarias.pas' {qrDocumentPrestDinerarias: TQuickRep},
  unRptConstanciaDomTrab in '..\siniestros\reports\unRptConstanciaDomTrab.pas' {qrConstanciaDomTrab: TQuickRep},
  unRptPlantillaRGRL in '..\comunes\reports\unRptPlantillaRGRL.pas' {qrPlantillaRGRL: TQuickRep},
  unfraVistaEventos in '..\comunes\frames\modulosAgenda\unfraVistaEventos.pas' {fraVistaEventos: TFrame},
  unABMAgendaBase in '..\comunes\forms\unABMAgendaBase.pas' {frmABMAgendaBase},
  unfraContactoAGENDA in '..\comunes\frames\modulosAgenda\unfraContactoAGENDA.pas' {fraContactoAGENDA: TFrame},
  unfraContactoLibreAGENDA in '..\comunes\frames\modulosAgenda\unfraContactoLibreAGENDA.pas' {fraContactoLibreAGENDA: TFrame},
  unfraDomicilioAGENDA in '..\comunes\frames\modulosAgenda\unfraDomicilioAGENDA.pas' {fraDomicilioGISAGENDA: TFrame},
  unfraDomicilioEmpresaAGENDA in '..\comunes\frames\modulosAgenda\unfraDomicilioEmpresaAGENDA.pas' {fraDomicilioEmpresaAGENDA: TFrame},
  unfraDomicilioEstablecimientoAGENDA in '..\comunes\frames\modulosAgenda\unfraDomicilioEstablecimientoAGENDA.pas' {fraDomicilioEstablecimientoAGENDA: TFrame},
  unfraEmpresaAGENDA in '..\comunes\frames\modulosAgenda\unfraEmpresaAGENDA.pas' {fraEmpresaAGENDA: TFrame},
  unfraEntidadAGENDA in '..\comunes\frames\modulosAgenda\unfraEntidadAGENDA.pas' {fraEntidadAGENDA: TFrame},
  unfraEntidadVendedorAGENDA in '..\comunes\frames\modulosAgenda\unfraEntidadVendedorAGENDA.pas' {fraEntidadVendedorAGENDA: TFrame},
  unfraEstablecimientoAGENDA in '..\comunes\frames\modulosAgenda\unfraEstablecimientoAGENDA.pas' {fraEstablecimientoAGENDA: TFrame},
  unfraNumAutoAGENDA in '..\comunes\frames\modulosAgenda\unfraNumAutoAGENDA.pas' {fraNumAutoAGENDA: TFrame},
  unfraPrestadorAGENDA in '..\comunes\frames\modulosAgenda\unfraPrestadorAGENDA.pas' {fraPrestadorAGENDA: TFrame},
  unfraProspectosAGENDA in '..\comunes\frames\modulosAgenda\unfraProspectosAGENDA.pas' {fraProspectosAGENDA: TFrame},
  unfraTrabajadorAGENDA in '..\comunes\frames\modulosAgenda\unfraTrabajadorAGENDA.pas' {fraTrabajadorAGENDA: TFrame},
  unfraTrabajadorSiniestroAGENDA in '..\comunes\frames\modulosAgenda\unfraTrabajadorSiniestroAGENDA.pas' {fraTrabajadorSiniestroAGENDA: TFrame},
  unfraVendedorAGENDA in '..\comunes\frames\modulosAgenda\unfraVendedorAGENDA.pas' {fraVendedorAGENDA: TFrame},
  unABMAgendaBaseTarea in '..\comunes\forms\unABMAgendaBaseTarea.pas' {frmABMAgendaBaseTarea},
  unABMAgendaBaseEvento in '..\comunes\forms\unABMAgendaBaseEvento.pas' {frmABMAgendaBaseEvento},
  unContratoTrabajador in '..\afiliaciones\unContratoTrabajador.pas' {frmContratoTrabajador},
  unFraActividad in '..\comunes\frames\unFraActividad.pas' {fraActividad: TFrame},
  unfraInfoEmpresaExt in '..\comunes\frames\new\unfraInfoEmpresaExt.pas' {fraInfoEmpresaExt: TFrame},
  unFraDomicilioEmpresa in '..\comunes\frames\new\unFraDomicilioEmpresa.pas' {fraDomicilioEmpresa: TFrame},
  unFraValidacionDatosEmpresa in '..\comunes\frames\new\unFraValidacionDatosEmpresa.pas' {fraValidacionDatosEmpresa: TFrame},
  unFraTitulo in '..\comunes\frames\nuevos\unFraTitulo.pas' {fraTitulo: TFrame},
  unFraUsuarioConJerarquias in '..\comunes\frames\new\unFraUsuarioConJerarquias.pas' {fraUsuarioConJerarquias: TFrame},
  unFraUsuarioConSectorIntranet in '..\comunes\frames\new\unFraUsuarioConSectorIntranet.pas' {fraUsuarioConSectorIntranet: TFrame},
  unArbolSectores in '..\usuarios\unArbolSectores.pas' {frmArbolSectores},
  unEstablecimientosTrabajador in '..\afiliaciones\unEstablecimientosTrabajador.pas' {frmEstablecimientosTrabajador},
  unDlgBusSiniestro in '..\siniestros\unDlgBusSiniestro.pas' {frmDlgBusSiniestro: TFSForm},
  unAgendaVistaEmpresa in '..\comunes\forms\unAgendaVistaEmpresa.pas' {frmAgendaVistaEmpresa},
  unAgendaCargaConsulta in '..\comunes\forms\unAgendaCargaConsulta.pas' {frmAgendaCargaConsulta},
  unInterfaces in '..\..\comunes\interfaces\unInterfaces.pas',
  unAgenda in '..\..\comunes\interfaces\unAgenda.pas',
  unSIC in '..\..\comunes\unSIC.pas',
  unSeleccionTareas in '..\comunes\forms\unSeleccionTareas.pas' {frmSeleccionTareas},
  unDatosSiniestro in '..\comunes\forms\unDatosSiniestro.pas' {frmDatosSiniestro},
  unSeleccionResponsableHYS in '..\hys\unSeleccionResponsableHYS.pas' {frmSeleccionResponsableHYS: TFSForm},
  unRptResumenILT in '..\dinerarias\reports\unRptResumenILT.pas' {qrResumenILT: TQuickRep},
  unFraFiltroArchivo in '..\archivo_new\frames\unFraFiltroArchivo.pas' {fraFiltroArchivo: TFrame},
  unfraArchJuicio in '..\archivo_new\frames\unfraArchJuicio.pas' {fraArchJuicio: TFrame},
  unfraProveedor in '..\comunes\frames\new\unfraProveedor.pas' {fraProveedor: TFrame},
  unRptNotaDenunciaGrave in '..\siniestros\reports\unRptNotaDenunciaGrave.pas' {qrNotaDenunciaGrave: TQuickRep},
  unRptCeseDeILT in '..\redpres\reports\unRptCeseDeILT.pas' {rptCeseDeILT: TQuickRep},
  unCapturarCodigoBarras in '..\comunes\unCapturarCodigoBarras.pas' {frmCapturarCodigoBarras},
  unCargaDocumentosDigitaliz in '..\comunes\forms\unCargaDocumentosDigitaliz.pas' {frmCargaDocumentosDigitaliz},
  unConstantArchivo in '..\archivo_new\unConstantArchivo.pas',
  unArchivo in '..\archivo_new\unArchivo.pas',
  unFrmConsultaCarpetas in '..\archivo_new\unFrmConsultaCarpetas.pas' {FrmConsultaCarpetas: TFSForm},
  unFrmSolicitudCarpeta in '..\archivo_new\unFrmSolicitudCarpeta.pas' {FrmSolicitudCarpeta: TFSForm},
  unQrEtiquetasCarpetas in '..\archivo_new\unQrEtiquetasCarpetas.pas' {qrEtiquetasCarpetas: TQuickRep},
  unFraDetalleArchivo in '..\archivo_new\frames\unFraDetalleArchivo.pas' {fraDetalleArchivo: TFrame},
  unFrmDetalleArchivo in '..\archivo_new\unFrmDetalleArchivo.pas' {FrmDetalleArchivo},
  unMovimientoCarpetas in '..\archivo_new\unMovimientoCarpetas.pas' {frmMovimientoCarpetas},
  unFrmCargaDocumentacion in '..\archivo_new\unFrmCargaDocumentacion.pas' {frmCargaDocumentacion},
  unQrDetalleLoteEstudio in '..\archivo_new\unQrDetalleLoteEstudio.pas' {QrDetalleLoteEstudio},
  unReemplazoCarpetas in '..\archivo_new\unReemplazoCarpetas.pas' {frmReemplazoCarpetas},
  unfrmUbicacionActual in '..\archivo_new\unfrmUbicacionActual.pas' {FrmUbicacionActual},
  unManEmpresasVIP in 'unManEmpresasVIP.pas' {frmManEmpresasVIP: TFSForm},
  SqlFuncs in '..\..\comunes\SqlFuncs.pas',
  unManCMV_MOTIVOEMPRESAVIP in 'unManCMV_MOTIVOEMPRESAVIP.pas' {frmManCMV_MOTIVOEMPRESAVIP: TFSForm},
  unComisiones in '..\afiliaciones\comisiones\unComisiones.pas',
  unTesoreria in '..\afiliaciones\tesoreria\unTesoreria.pas',
  unRptCitacionPresidencia in '..\siniestros\reports\unRptCitacionPresidencia.pas' {qrCitacionPresidencia: TQuickRep},
  unImprimeContrato in '..\afiliaciones\unImprimeContrato.pas' {frmImprimeContrato},
  unQRAnexoA in '..\afiliaciones\reports\unQRAnexoA.pas' {QRAnexoA: TQuickRep},
  unQRContrato in '..\afiliaciones\reports\unQRContrato.pas' {QRContrato: TQuickRep},
  unQRContrato2 in '..\afiliaciones\reports\unQRContrato2.pas' {QRContrato2: TQuickRep},
  unQRContrato3 in '..\afiliaciones\reports\unQRContrato3.pas' {QRContrato3: TQuickRep},
  unQrDetalleRemitoDevolucion in '..\archivo_new\unQrDetalleRemitoDevolucion.pas' {QrDetalleRemitoDevolucion},
  unfraEmpresaSolicitudAGENDA in '..\comunes\frames\modulosagenda\unfraEmpresaSolicitudAGENDA.pas' {fraEmpresaSolicitudAGENDA: TFrame},
  unQRContratoNomina in '..\afiliaciones\reports\unQRContratoNomina.pas' {qrContratoNomina: TQuickRep},
  unfraFirmante in '..\comunes\frames\unfraFirmante.pas' {fraFirmante: TFrame},
  unFraEntidades in '..\Comunes\FRAMES\unFraEntidades.pas' {fraEntidades: TFrame},
  unfraSucursal in '..\Comunes\FRAMES\NEW\unfraSucursal.pas' {fraSucursal: TFrame},
  unContratoVendedor2 in 'unContratoVendedor2.pas' {frmContratoVendedor},
  unManCVS_VENTANILLA_SUBTEMAS in '..\comunes\forms\unManCVS_VENTANILLA_SUBTEMAS.pas' {frmManCVS_VENTANILLA_SUBTEMAS: TFSForm},
  unManSEC_EMPRESASCOMPENSABLES in 'unManSEC_EMPRESASCOMPENSABLES.pas' {frmManSEC_EMPRESASCOMPENSABLES: TFSForm},
  unfraDatoFechaAGENDA in '..\comunes\frames\modulosagenda\unfraDatoFechaAGENDA.pas' {fraDatoFecha: TFrame},
  unFrmArmadoLote in '..\archivo_new\unFrmArmadoLote.pas' {FrmArmadoLote: TFSForm},
  unQrDetalleLote in '..\archivo_new\unQrDetalleLote.pas' {QrDetalleLote},
  unRptResumenLotes in '..\archivo_new\unRptResumenLotes.pas' {qrResumenLotes: TQuickRep},
  unAvisosContrato in '..\redpres\abm\unAvisosContrato.pas' {frmAvisosContrato: TFSForm},
  unVerImagenes in '..\archivo_new\unVerImagenes.pas' {frmVerImagenes},
  unMensajeAlertaAGA in '..\archivo_new\unMensajeAlertaAGA.pas',
  unMensajeAlerta in '..\..\comunes\unMensajeAlerta.pas',
  unQREntregaMaterial in '..\afiliaciones\reports\unQREntregaMaterial.pas' {QREntregaMaterial},
  unFraWebBrowser in '..\comunes\frames\new\unFraWebBrowser.pas' {fraWebBrowser: TFrame},
  unFraGIS_APIv3 in '..\comunes\frames\new\unFraGIS_APIv3.pas' {fraGIS_APIv3: TFrame},
  unGenerarMultiplesCartasPorContrato in '..\afiliaciones\unGenerarMultiplesCartasPorContrato.pas' {frmGenerarMultiplesCartasPorContrato: TFSForm},
  unAfiAdministracionCartas in '..\afiliaciones\unAfiAdministracionCartas.pas' {frmAfiAdministracionCartas: TFSForm},
  unImportCryptoSrt in '..\..\comunes\unImportCryptoSrt.pas',
  unSeleccionarCarpetaSRT in '..\afiliaciones\unSeleccionarCarpetaSRT.pas' {frmSeleccionarCarpetaSRT},
  unGenerarMultiplesCartas in '..\afiliaciones\unGenerarMultiplesCartas.pas' {frmGenerarMultiplesCartas: TFSForm},
  unQRAvisoRecibo in '..\afiliaciones\unQRAvisoRecibo.pas' {rptAvisoRecibo: TQuickRep},
  unEnvioSMS in '..\comunes\forms\unEnvioSMS.pas' {frmEnvioSMS},
  unEsperaSimple in '..\comunes\forms\unEsperaSimple.pas' {frmEsperaSimple},
  unCargaTablasSin in '..\controller\unCargaTablasSin.pas' {frmCargaTablasSin},
  IArtMail in '..\comunes\IArtMail.pas',
  unRptRemitoCartas in '..\redpres\reports\unRptRemitoCartas.pas' {qrRemitoCartas: TQuickRep},
  unDireccionCDO in '..\dinerarias\unDireccionCDO.pas' {frmDireccionCDO},
  unJustificacionILT in '..\siniestros\unJustificacionILT.pas' {frmJustificacionILT},
  unRptPedidoDocum in '..\siniestros\reports\unRptPedidoDocum.pas' {frmPedidoDocum},
  unRptAntecedentesLabYMed in '..\siniestros\reports\unRptAntecedentesLabYMed.pas' {frmRptAntecedentesLabYMed},
  unRptNotaReqCarDef in '..\siniestros\reports\unRptNotaReqCarDef.pas' {rptNotaReqCarDef},
  unRptReciboILPPerDef in '..\dinerarias\reports\unRptReciboILPPerDef.pas' {frmReciboILPPerDef},
  unQRContratoPCP in '..\afiliaciones\reports\unQRContratoPCP.pas' {QRContratoPCP: TQuickRep},
  unQRAnexoPCP in '..\afiliaciones\reports\unQRAnexoPCP.pas' {QRAnexoPCP: TQuickRep},
  unManCEN_ENCUESTA in '..\comunes\forms\unManCEN_ENCUESTA.pas' {frmManCEN_ENCUESTA: TFSForm},
  unManCEC_ENCUESTACATEGORIA in '..\comunes\forms\unManCEC_ENCUESTACATEGORIA.pas' {frmManCEN_ENCUESTACATEGORIA: TFSForm},
  unManCEP_ENCUESTAPREGUNTA in '..\comunes\forms\unManCEP_ENCUESTAPREGUNTA.pas' {frmManCEN_ENCUESTAPREGUNTA: TFSForm},
  unGestionDeEncuestas in '..\comunes\forms\unGestionDeEncuestas.pas' {frmGestionDeEncuestas: TFSForm},
  unSeleccionarFechaFinTrat in '..\siniestros\unSeleccionarFechaFinTrat.pas' {frmSeleccionarFechaFinTrat},
  unFraTipoRegimen in '..\comunes\frames\new\unFraTipoRegimen.pas' {fraTipoRegimen: TFrame},
  unFraPreguntas in '..\comunes\frames\new\unFraPreguntas.pas' {fraPreguntas: TFrame},
  unFraPregunta in '..\comunes\frames\new\unFraPregunta.pas' {fraPregunta: TFrame},
  unRptEncuesta in '..\comunes\reports\unRptEncuesta.pas' {qrEncuesta: TQuickRep},
  unEncuesta in '..\..\comunes\unEncuesta.pas',
  unRptEncuestaEstadistica in '..\comunes\reports\unRptEncuestaEstadistica.pas' {qrEncuestaEstadistica: TQuickRep},
  unFiltroEncuestaEstadistica in '..\comunes\forms\unFiltroEncuestaEstadistica.pas' {frmFiltroEncuestaEstadistica},
  unManCVS_VISITA in '..\comunes\forms\unManCVS_VISITA.pas' {frmManCVS_VISITA: TFSForm},
  unManCVC_VISITACATEGORIA in '..\comunes\forms\unManCVC_VISITACATEGORIA.pas' {frmManCVC_VISITACATEGORIA: TFSForm},
  unManCVT_VISITATEMA in '..\comunes\forms\unManCVT_VISITATEMA.pas' {frmManCVT_VISITATEMA: TFSForm},
  unFraTema in '..\comunes\frames\new\unFraTema.pas' {fraTema: TFrame},
  unVisita in '..\..\comunes\unVisita.pas',
  unGestionDeVisitas in '..\comunes\forms\unGestionDeVisitas.pas' {frmGestionDeVisitas: TFSForm},
  unRptVisita in '..\comunes\reports\unRptVisita.pas' {qrVisita: TQuickRep},
  unFraTemas in '..\comunes\frames\new\unFraTemas.pas' {fraTemas: TFrame},
  unTexto in '..\comunes\unTexto.pas' {frmTexto},
  numeros in '..\..\comunes\numeros.pas',
  unGIS in '..\..\comunes\unGIS.pas',
  unCobranzas in '..\..\comunes\unCobranzas.pas',
  unWSTramitesMedicos in '..\comunes\unWSTramitesMedicos.pas' {$R *.RES},
  unDocumentacion in '..\comunes\forms\unDocumentacion.pas' {frmDocumentacion: TFSForm},
  unRemitoDocumentacion in '..\comunes\forms\unRemitoDocumentacion.pas' {frmRemitoDocumentacion},
  unHistoricoDocumentacion in '..\comunes\forms\unHistoricoDocumentacion.pas' {frmHistoricoDocumentacion: TFSForm},
  unLstRemitosnoRecepcionados in '..\comunes\reports\unLstRemitosnoRecepcionados.pas' {frmLstRemitosnoRecepcionados},
  unSituacionDocumental in '..\siniestros\unSituacionDocumental.pas' {frmDocumentacion: TFSForm},
  unChat in '..\comunes\unChat.pas' {frmChat},
  unEnviosVentanillaElectronica in '..\comunes\forms\unEnviosVentanillaElectronica.pas' {frmEnviosVentanillaElectronica: TFSForm},
  unRptHistoriaEmpresa in '..\comunes\reports\unRptHistoriaEmpresa.pas' {frmRptHistoriaEmpresa};

{$R *.RES}
{$R *.dres}

begin
  OnlyOneInstance;
  Application.Initialize;
  Application.Title := 'Integrador';
  with TfrmWelcomeSplash.Create(Application) do
  try
    ShowOnTop;
    Application.CreateForm(TdmPrincipal, dmPrincipal);
    Application.CreateForm(TdmFinancials, dmFinancials);
    if dmPrincipal.sdbPrincipal.Connected then
      Application.CreateForm(TfrmPrincipal, frmPrincipal);
  finally
    Free;
  end;
  MostrarNovedades();
  OnlyOneSession;
  Application.Run;
end.
