program Tickets;

{$R *.dres}

uses
  Forms,
  Controls,
  Windows,
  unCustomDataModule in '..\Comunes\unCustomDataModule.pas' {dmCustomDataModule: TDataModule},
  unDmPrincipal in '..\Comunes\ORACLE\unDmPrincipal.pas' {dmPrincipal: TDataModule},
  unCustomConsulta in '..\Comunes\REPOSIT\unCustomConsulta.pas' {frmCustomConsulta},
  unCustomSplash in '..\comunes\reposit\unCustomSplash.pas' {frmCustomSplash},
  unWelcomeSplash in '..\comunes\forms\unWelcomeSplash.pas' {frmWelcomeSplash},
  General in '..\..\comunes\General.pas',
  unCustomForm in '..\comunes\unCustomForm.pas' {frmCustomForm},
  unDebug in '..\comunes\unDebug.pas' {frmDebug},
  OneSession in '..\..\comunes\OneSession.pas',
  unSesion in '..\..\Comunes\unSesion.pas',
  unCustomPanelABM in '..\comunes\reposit\unCustomPanelABM.pas' {frmCustomPanelABM: TFSForm},
  unArtFrame in '..\Comunes\REPOSIT\unArtFrame.pas' {ArtFrame: TFrame},
  unArtDBAwareFrame in '..\Comunes\REPOSIT\unArtDBAwareFrame.pas' {ArtDBAwareFrame: TFrame},
  unFraCodigoDescripcion in '..\Comunes\FRAMES\unFraCodigoDescripcion.pas' {fraCodigoDescripcion: TFrame},
  unFraStaticCodigoDescripcion in '..\Comunes\FRAMES\unFraStaticCodigoDescripcion.pas' {fraStaticCodigoDescripcion: TFrame},
  unFraStaticCTB_TABLAS in '..\Comunes\FRAMES\unFraStaticCTB_TABLAS.pas' {fraStaticCTB_TABLAS: TFrame},
  unFraCodDesc in '..\Comunes\FRAMES\NUEVOS\unFraCodDesc.pas' {fraCodDesc: TFrame},
  unArtDbFrame in '..\Comunes\REPOSIT\unArtDbFrame.pas' {ArtDbFrame: TFrame},
  unCustomGridABM in '..\Comunes\REPOSIT\unCustomGridABM.pas' {frmCustomGridABM},
  unEspera in '..\Comunes\Forms\unEspera.pas' {frmEspera},
  unContratoContacto in '..\Afiliaciones\unContratoContacto.pas' {frmContratoContacto},
  unSeleccionDestinatarios in '..\comunes\unSeleccionDestinatarios.pas' {frmSeleccionDestinatarios},
  unfraContacto in '..\Comunes\FRAMES\unfraContacto.pas' {fraContacto: TFrame},
  unFraTelefono in '..\Comunes\FRAMES\NEW\unFraTelefono.pas' {fraTelefono: TFrame},
  unABMTelefonos in '..\Comunes\Forms\unABMTelefonos.pas' {frmTelefonos},
  unTelefonosCargaRapida in '..\Comunes\Forms\unTelefonosCargaRapida.pas' {frmTelefonosCargaRapida},
  unMoldeEnvioMail in '..\Comunes\Envio de Mails\unMoldeEnvioMail.pas',
  unLibretaDeDirecciones in '..\Comunes\Forms\unLibretaDeDirecciones.pas' {frmLibretaDeDirecciones},
  unFraUsuario in '..\Comunes\FRAMES\NEW\unFraUsuario.pas' {fraUsuarios: TFrame},
  unFraToolbarRTF in '..\comunes\frames\unFraToolbarRTF.pas' {fraToolbarRTF: TFrame},
  unRptCartaDocHeader in '..\Comunes\REPORTS\unRptCartaDocHeader.pas' {rptCartaDocHeader: TQuickRep},
  unRptCartaDocumento in '..\Comunes\REPORTS\unRptCartaDocumento.pas' {rptCartaDocumento: TQuickRep},
  unVisualizador in '..\Comunes\unVisualizador.pas' {frmVisualizador},
  unComunes in '..\..\comunes\unComunes.pas',
  unCustomPrincipal in '..\comunes\reposit\unCustomPrincipal.pas' {frmCustomPrincipal},
  unPrincipal in 'unPrincipal.pas' {frmPrincipal},
  unBusquedaDomicilio in '..\Comunes\Forms\unBusquedaDomicilio.pas' {frmBusquedaDomicilio},
  unClasificacionActivos in '..\comunes\forms\unClasificacionActivos.pas' {frmClasificacionActivos: TFSForm},
  unfraUsuarios in '..\Comunes\FRAMES\unfraUsuarios.pas' {fraUsuario: TFrame},
  unFraCtbTablas in '..\Comunes\FRAMES\unFraCtbTablas.pas' {fraCtbTablas: TFrame},
  unFraVistaTIFF in '..\comunes\frames\new\unFraVistaTIFF.pas' {fraVistaTIFF: TFrame},
  unFraRTD_TIPODOCUMENTO in '..\comunes\frames\new\unFraRTD_TIPODOCUMENTO.pas' {fraRTD_TIPODOCUMENTO: TFrame},
  unFraTrabajador in '..\Comunes\FRAMES\NEW\unFraTrabajador.pas' {fraTrabajador: TFrame},
  unFraEmpresa in '..\Comunes\FRAMES\NEW\unFraEmpresa.pas' {fraEmpresa: TFrame},
  unFraEstablecimiento in '..\Comunes\FRAMES\NEW\unFraEstablecimiento.pas' {fraEstablecimiento: TFrame},
  unfraVendedores in '..\Comunes\FRAMES\unfraVendedores.pas' {fraVendedores: TFrame},
  unfraVendedoresCUIT in '..\Comunes\FRAMES\NEW\unfraVendedoresCUIT.pas' {fraVendedoresCUIT: TFrame},
  unFraDigitalizacion in '..\comunes\frames\new\unFraDigitalizacion.pas' {fraDigitalizacion: TFrame},
  unVisualizadorDigitalizacion in '..\comunes\forms\unVisualizadorDigitalizacion.pas' {frmVisualizadorDigitalizacion},
  unVisor in '..\comunes\forms\unVisor.pas' {frmVisor},
  unArchivoVisor in '..\comunes\unArchivoVisor.pas',
  unVisorPDF in '..\comunes\forms\unVisorPDF.pas' {frmVisorPDF},
  unVisorExcel in '..\comunes\forms\unVisorExcel.pas' {frmVisorExcel},
  unfraEntidadCUIT in '..\Comunes\FRAMES\NEW\unfraEntidadCUIT.pas' {fraEntidadCUIT: TFrame},
  unfraCPR_PRESTADOR in '..\comunes\frames\new\unfraCPR_PRESTADOR.pas' {fraCPR_PRESTADOR: TFrame},
  unfraCuentaBancariaRemesa in '..\Comunes\FRAMES\NEW\unfraCuentaBancariaRemesa.pas' {fraCuentaBancariaRemesa: TFrame},
  unElementosEnviados in '..\Comunes\Forms\unElementosEnviados.pas' {frmElementosEnviados},
  unFaxEnviados in '..\comunes\forms\unFaxEnviados.pas' {frmFaxEnviados},
  unfraFFO_FAXFORMULARIO in '..\comunes\frames\unfraFFO_FAXFORMULARIO.pas' {fraFFO_FAXFORMULARIO: TFrame},
  unManRDO_DOCUMENTO in '..\archivo_new\abm\unManRDO_DOCUMENTO.pas' {frmManRDO_DOCUMENTO: TFSForm},
  unManCGI_GIS in '..\comunes\forms\unManCGI_GIS.pas' {frmManCGI_GIS: TFSForm},
  unAnexoRes365 in '..\comunes\forms\unAnexoRes365.pas' {frmAnexoRes365},
  unFormularioValidacionYRectificacionDatosEstablecimientos in '..\comunes\forms\unFormularioValidacionYRectificacionDatosEstablecimientos.pas' {frmFormularioValidacionYRectificacionDatosEstablecimientos},
  unRptFormularioValidacionYRectificacionDatosEstablecimientos in '..\comunes\reports\unRptFormularioValidacionYRectificacionDatosEstablecimientos.pas' {qrFormularioValidacionYRectificacionDatosEstablecimientos: TQuickRep},
  unfraCuentaBancaria in '..\Comunes\FRAMES\NEW\unfraCuentaBancaria.pas' {fraCuentaBancaria: TFrame},
  unRptAnexoRes365 in '..\comunes\reports\unRptAnexoRes365.pas' {qrAnexoRes365: TQuickRep},
  unFraTrabajadorSiniestro in '..\comunes\frames\new\unFraTrabajadorSiniestro.pas' {fraTrabajadorSiniestro: TFrame},
  unfraDelegacion in '..\comunes\frames\unfraDelegacion.pas' {fraDelegacion: TFrame},
  unRptGestionDeReclamos in '..\comunes\reports\unRptGestionDeReclamos.pas' {frmRptGestionDeReclamos},
  unVentanillaElectronica in '..\comunes\forms\unVentanillaElectronica.pas' {frmVentanillaElectronica: TFSForm},
  unAgendaTelefonica in '..\comunes\forms\unAgendaTelefonica.pas' {frmAgendaTelefonica: TFSForm},
  unFraNavegadorWEB in '..\comunes\frames\new\unFraNavegadorWEB.pas' {fraNavegadorWEB: TFrame},
  unFraDomicilioGIS in '..\comunes\frames\new\unFraDomicilioGIS.pas' {fraDomicilioGIS: TFrame},
  unGoogleMaps in '..\comunes\forms\unGoogleMaps.pas' {frmGoogleMaps},
  unFraEmpresaAfi in '..\comunes\frames\new\unFraEmpresaAfi.pas' {fraEmpresaAfi: TFrame},
  unRptRGRL in '..\comunes\reports\unRptRGRL.pas' {qrRGRL: TQuickRep},
  unRGRL in '..\comunes\forms\unRGRL.pas' {frmRGRL},
  unRptEstadisticasRGRL in '..\comunes\reports\unRptEstadisticasRGRL.pas' {qrEstadisticasRGRL: TQuickRep},
  unFraDomicilio in '..\Comunes\FRAMES\NEW\unFraDomicilio.pas' {fraDomicilio: TFrame},
  unManCPG_PLAZOGUARDA in '..\comunes\forms\unManCPG_PLAZOGUARDA.pas' {frmManCPG_PLAZOGUARDA: TFSForm},
  unManCTA_TIPOACTIVOS in '..\comunes\forms\unManCTA_TIPOACTIVOS.pas' {frmManCTA_TIPOACTIVOS: TFSForm},
  unfraCodigoDescripcionExt in '..\comunes\frames\unfraCodigoDescripcionExt.pas' {fraCodigoDescripcionExt: TFrame},
  unSeleccionMultiple in '..\comunes\forms\unSeleccionMultiple.pas' {frmSeleccionUsuarios: TFrame},
  unConsFax in '..\comunes\forms\unConsFax.pas' {frmConsFax: TFSForm},
  unEstrategiaTIFF in '..\fax\faxclient_new\unEstrategiaTIFF.pas',
  unArt in '..\..\comunes\unArt.pas',
  unNovedades in '..\..\comunes\unNovedades.pas',
  unRptPlantillaRGRL in '..\comunes\reports\unRptPlantillaRGRL.pas' {qrPlantillaRGRL: TQuickRep},
  unArchivo in '..\archivo_new\unArchivo.pas',
  unFrmConsultaCarpetas in '..\archivo_new\unFrmConsultaCarpetas.pas' {FrmConsultaCarpetas: TFSForm},
  unFrmSolicitudCarpeta in '..\archivo_new\unFrmSolicitudCarpeta.pas' {FrmSolicitudCarpeta: TFSForm},
  unQrEtiquetasCarpetas in '..\archivo_new\unQrEtiquetasCarpetas.pas' {qrEtiquetasCarpetas: TQuickRep},
  unFraDetalleArchivo in '..\archivo_new\frames\unFraDetalleArchivo.pas' {fraDetalleArchivo: TFrame},
  unFrmDetalleArchivo in '..\archivo_new\unFrmDetalleArchivo.pas' {FrmDetalleArchivo},
  unMovimientoCarpetas in '..\archivo_new\unMovimientoCarpetas.pas' {frmMovimientoCarpetas},
  unFrmCargaDocumentacion in '..\archivo_new\unFrmCargaDocumentacion.pas' {frmCargaDocumentacion},
  unQrDetalleLoteEstudio in '..\archivo_new\unQrDetalleLoteEstudio.pas' {QrDetalleLoteEstudio},
  unReemplazoCarpetas in '..\archivo_new\unReemplazoCarpetas.pas' {frmReemplazoCarpetas},
  unfrmUbicacionActual in '..\archivo_new\unfrmUbicacionActual.pas' {FrmUbicacionActual},
  unFraFiltroArchivo in '..\archivo_new\frames\unFraFiltroArchivo.pas' {fraFiltroArchivo: TFrame},
  unfraArchJuicio in '..\archivo_new\frames\unfraArchJuicio.pas' {fraArchJuicio: TFrame},
  unfraSectores in '..\Comunes\Frames\unfraSectores.pas' {fraSectores: TFrame},
  unfraProveedor in '..\comunes\frames\new\unfraProveedor.pas' {fraProveedor: TFrame},
  unCapturarCodigoBarras in '..\comunes\unCapturarCodigoBarras.pas' {frmCapturarCodigoBarras},
  unImpoExpoWizard in '..\impoexpo\unImpoExpoWizard.pas' {frmImpoExpoWizard},
  unQrEtiquetasDocCarpetas in '..\archivo_new\unQrEtiquetasDocCarpetas.pas' {qrEtiquetasDocCarpetas: TQuickRep},
  unGestionSistemas in '..\usuarios\unGestionSistemas.pas' {frmGestionSistemas: TFSForm},
  unSistemas in '..\usuarios\unSistemas.pas',
  unManCMS_MOTIVOSOLICITUD in '..\usuarios\unManCMS_MOTIVOSOLICITUD.pas' {frmManCMS_MOTIVOSOLICITUD: TFSForm},
  unArbolSectores in '..\usuarios\unArbolSectores.pas' {frmArbolSectores},
  unEstadisticas in '..\usuarios\unEstadisticas.pas' {frmEstadisticas: TFSForm},
  UnRptMoldeCarta in '..\comunes\reports\UnRptMoldeCarta.pas' {qrMoldeCarta: TQuickRep},
  unRptTicket in '..\usuarios\reports\unRptTicket.pas' {qrTicket: TQuickRep},
  unfraPrestador in '..\comunes\frames\unfraPrestador.pas' {fraPrestador: TFrame},
  unElementosEnviadosGlobal in '..\sistemas\unElementosEnviadosGlobal.pas' {frmElementosEnviadosGlobal: TFSForm},
  VCLExtra in '..\..\comunes\VCLExtra.pas',
  unUtilsArchivo in '..\archivo_new\unUtilsArchivo.pas',
  unSiniestros in '..\siniestros\unSiniestros.pas',
  unComisiones in '..\afiliaciones\comisiones\unComisiones.pas',
  CustomDlgs in '..\..\comunes\CustomDlgs.pas',
  unAfiliaciones in '..\afiliaciones\unAfiliaciones.pas',
  unManEquipos in '..\usuarios\unManEquipos.pas' {frmManEquipos: TFSForm},
  unAltaSolicitudesCambioExe in '..\usuarios\unAltaSolicitudesCambioExe.pas' {frmAltaSolicitudesCambioExe},
  unManCVS_VENTANILLA_SUBTEMAS in '..\comunes\forms\unManCVS_VENTANILLA_SUBTEMAS.pas' {frmManCVS_VENTANILLA_SUBTEMAS: TFSForm},
  unSolicitudesCambioExe in '..\usuarios\unSolicitudesCambioExe.pas' {frmSolicitudesCambioExe: TFSForm},
  unRptSolicitudCambioExe in '..\usuarios\reports\unRptSolicitudCambioExe.pas' {qrSolicitudCambioExe: TQuickRep},
  unQrDetalleRemitoDevolucion in '..\archivo_new\unQrDetalleRemitoDevolucion.pas' {QrDetalleRemitoDevolucion},
  unCargaDocumentosDigitaliz in '..\comunes\forms\unCargaDocumentosDigitaliz.pas' {frmCargaDocumentosDigitaliz},
  unFrmArmadoLote in '..\archivo_new\unFrmArmadoLote.pas' {FrmArmadoLote: TFSForm},
  unQrDetalleLote in '..\archivo_new\unQrDetalleLote.pas' {QrDetalleLote},
  unRptResumenLotes in '..\archivo_new\unRptResumenLotes.pas' {qrResumenLotes: TQuickRep},
  unVerImagenes in '..\archivo_new\unVerImagenes.pas' {frmVerImagenes},
  unMensajeAlertaAGA in '..\archivo_new\unMensajeAlertaAGA.pas',
  unMensajeAlerta in '..\..\comunes\unMensajeAlerta.pas',
  unTesoreria in '..\afiliaciones\tesoreria\unTesoreria.pas',
  unEsperaSimple in '..\comunes\forms\unEsperaSimple.pas' {frmEsperaSimple},
  unFraWebBrowser in '..\comunes\frames\new\unFraWebBrowser.pas' {fraWebBrowser: TFrame},
  unFraGIS_APIv3 in '..\comunes\frames\new\unFraGIS_APIv3.pas' {fraGIS_APIv3: TFrame},
  unEnvioSMS in '..\comunes\forms\unEnvioSMS.pas' {frmEnvioSMS},
  unSMS in '..\..\comunes\unSMS.pas' {$R *.RES},
  unDocumentacion in '..\comunes\forms\unDocumentacion.pas' {frmDocumentacion: TFSForm},
  unRemitoDocumentacion in '..\comunes\forms\unRemitoDocumentacion.pas' {frmRemitoDocumentacion},
  unHistoricoDocumentacion in '..\comunes\forms\unHistoricoDocumentacion.pas' {frmHistoricoDocumentacion: TFSForm},
  unLstRemitosnoRecepcionados in '..\comunes\reports\unLstRemitosnoRecepcionados.pas' {frmLstRemitosnoRecepcionados},
  unFraActividad in '..\comunes\frames\unFraActividad.pas' {fraActividad: TFrame},
  unFraDomicilioTrab in '..\Comunes\FRAMES\NEW\unFraDomicilioTrab.pas' {fraDomicilioTrab: TFrame},
  unManCCP_CUENTAPAGO in '..\Comunes\Forms\unManCCP_CUENTAPAGO.pas' {frmManCCP_CUENTAPAGO},
  unAltaModifCCP_CUENTAPAGO in '..\Comunes\Forms\unAltaModifCCP_CUENTAPAGO.pas' {frmAltaModifCCP_CUENTAPAGO},
  unDlgBusSiniestro in '..\siniestros\unDlgBusSiniestro.pas' {frmDlgBusSiniestro: TFSForm},
  unEstablecimientosTrabajador in '..\Afiliaciones\unEstablecimientosTrabajador.pas' {frmEstablecimientosTrabajador},
  unContratoTrabajador in '..\afiliaciones\unContratoTrabajador.pas' {frmContratoTrabajador},
  unSMS_BandejaEntrada in '..\comunes\forms\unSMS_BandejaEntrada.pas' {frmSMS_BandejaEntrada: TFSForm};

{$R *.RES}

begin
  Application.Initialize;
  Application.Title := 'Administración de Tickets';
  with TfrmWelcomeSplash.Create(Application) do
  try
    ShowOnTop;
    Application.CreateForm(TdmPrincipal, dmPrincipal);
  Invalidate;
    if dmPrincipal.sdbPrincipal.Connected then
      Application.CreateForm(TfrmPrincipal, frmPrincipal);
    Invalidate;
    OnlyOneSession;
    Invalidate;
  finally
    Free;
  end;

  MostrarNovedades;
  Application.Run;
end.
