unit unConstFet;

interface

const
  TIPO_FORMULARIO_PRS = 1;
  TIPO_FORMULARIO_PAPE = 2;

  FORMULARIO_TIPO_A = 1;
  FORMULARIO_TIPO_B = 2;
  FORMULARIO_TIPO_C = 3;

  OBSERVACION_PUNTO_NO_CONTESTADO = 1;
  OBSERVACION_PUNTO_SIN_FECHA_REGULARIZACION = 2;

  OBSERVACION_FALTA_ANEXO_A = 3;
  OBSERVACION_FALTA_ANEXO_B = 4;
  OBSERVACION_FALTA_ANEXO_C = 5;

  OBSERVACION_ANEXO_A_INCOMPLETO = 6;
  OBSERVACION_ANEXO_B_INCOMPLETO = 7;
  OBSERVACION_ANEXO_C_INCOMPLETO = 8;

  OBSERVACION_ANEXO_A_NO = 9;
  OBSERVACION_ANEXO_B_NO = 10;
  OBSERVACION_ANEXO_C_NO = 11;

  OBSERVACION_ANEXO_A_SI = 12;
  OBSERVACION_ANEXO_B_SI = 13;
  OBSERVACION_ANEXO_C_SI = 14;

  OBSERVACION_FALTA_RESPONSABLE = 15;
  OBSERVACION_RESPONSABLE_DATOS_INVAL = 16;
  OBSERVACION_FALTA_RESPONSABLE_HYS = 17;
  OBSERVACION_FALTA_RESPONSABLE_ML = 18;

  OBSERVACION_RESP_HYS_DATOS_INVAL = 19;
  OBSERVACION_RESP_ML_DATOS_INVAL = 20;

  OBSERVACION_AUSENCIA_DATO_EMPLEADOS_ESTAB = 21;

  TIPO_EMPRESA_PREV_ET     = 1;
  TIPO_EMPRESA_PREV_EP     = 2;
  TIPO_EMPRESA_PREV_EAD    = 3;
  TIPO_EMPRESA_PREV_EADS   = 4;
  TIPO_EMPRESA_PREV_GB     = 5;
  TIPO_EMPRESA_PREV_CO     = 6;

implementation


end.
